// apps/vue/components/CodeTabs.vue
<script setup lang="ts">
import { Tabs } from '@/components/ui/tabs'

const installationType = ref<'cli' | 'manual'>('cli')

function handleValueChange(value: string) {
  installationType.value = value as 'cli' | 'manual'
}
</script>

<template>
  <Tabs
    :model-value="installationType"
    class="relative mt-6 w-full"
    @update:model-value="handleValueChange"
  >
    <slot />
  </Tabs>
</template>

// apps/www/components/code-tabs.tsx
"use client"

import * as React from "react"

import { useConfig } from "@/hooks/use-config"
import { Tabs } from "@/components/ui/tabs"

export function CodeTabs({ children }: React.ComponentProps<typeof Tabs>) {
  const [config, setConfig] = useConfig()

  const installationType = React.useMemo(() => {
    return config.installationType || "cli"
  }, [config])

  return (
    <Tabs
      value={installationType}
      onValueChange={(value) =>
        setConfig({ ...config, installationType: value as "cli" | "manual" })
      }
      className="relative mt-6 w-full "
    >
      {children}
    </Tabs>
  )
}
