// apps/vue/components/ComponentPreviewTabs.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'

interface Props {
  class?: string
  align?: 'center' | 'start' | 'end'
  hideCode?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  align: 'center',
  hideCode: false,
})

const tab = ref('preview')
</script>

<template>
  <div
    :class="cn('group relative mt-4 mb-12 flex flex-col gap-2', props.class)"
  >
    <Tabs
      v-model="tab"
      class="relative mr-auto w-full"
    >
      <div class="flex items-center justify-between">
        <TabsList v-if="!hideCode">
          <TabsTrigger value="preview">Preview</TabsTrigger>
          <TabsTrigger value="code">Code</TabsTrigger>
        </TabsList>
      </div>
    </Tabs>
    <div
      :data-tab="tab"
      class="data-[tab=code]:border-code relative rounded-lg border md:-mx-1"
    >
      <div v-if="tab === 'preview'" data-slot="preview">
        <div
          :data-align="align"
          :class="cn(
            'preview flex overflow-y-auto min-h-[650px] w-full justify-center md:p-10 data-[align=center]:items-center data-[align=end]:items-end data-[align=start]:items-start',
          )"
        >
          <slot name="component" />
        </div>
      </div>
      <div v-else data-slot="code" class="overflow-auto **:[figure]:!m-0">
        <slot name="source" />
      </div>
    </div>
  </div>
</template>

// apps/www/components/component-preview-tabs.tsx
"use client";

import * as React from "react";

import { cn } from "@/lib/utils";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";

export function ComponentPreviewTabs({
	className,
	align = "center",
	hideCode = false,
	component,
	source,
	...props
}: React.ComponentProps<"div"> & {
	align?: "center" | "start" | "end";
	hideCode?: boolean;
	component: React.ReactNode;
	source: React.ReactNode;
}) {
	const [tab, setTab] = React.useState("preview");

	return (
		<div
			className={cn("group relative mt-4 mb-12 flex flex-col gap-2", className)}
			{...props}
		>
			<Tabs
				className="relative mr-auto w-full"
				value={tab}
				onValueChange={setTab}
			>
				<div className="flex items-center justify-between">
					{!hideCode && (
						<TabsList>
							<TabsTrigger value="preview">Preview</TabsTrigger>
							<TabsTrigger value="code">Code</TabsTrigger>
						</TabsList>
					)}
				</div>
			</Tabs>
			<div
				data-tab={tab}
				className="data-[tab=code]:border-code relative rounded-lg border md:-mx-1"
			>
				{tab === "preview" ? (
					<div data-slot="preview">
						<div
							data-align={align}
							className={cn(
								"preview flex overflow-y-auto min-h-[650px] w-full justify-center md:p-10 data-[align=center]:items-center data-[align=end]:items-end data-[align=start]:items-start ",
							)}
						>
							{component}
						</div>
					</div>
				) : (
					<div data-slot="code" className="overflow-auto **:[figure]:!m-0">
						{source}
					</div>
				)}
			</div>
		</div>
	);
}
