// apps/vue/components/DocsToc.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'

interface TocItem {
  title: string
  url: string
  children?: Array<{
    title: string
    url: string
  }>
}

defineProps<{
  toc: TocItem[]
}>()
</script>

<template>
  <div class="space-y-2">
    <h4 class="text-sm font-medium">On this page</h4>
    <ul class="space-y-1">
      <li v-for="item in toc" :key="item.url">
        <a
          :href="item.url"
          :class="cn(
            'block text-sm text-muted-foreground hover:text-foreground transition-colors'
          )"
        >
          {{ item.title }}
        </a>
        <ul v-if="item.children" class="ml-4 mt-1 space-y-1">
          <li v-for="child in item.children" :key="child.url">
            <a
              :href="child.url"
              :class="cn(
                'block text-sm text-muted-foreground hover:text-foreground transition-colors'
              )"
            >
              {{ child.title }}
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</template>

// apps/www/components/docs-toc.tsx
"use client"

import { cn } from "@/lib/utils"

interface DocsTableOfContentsProps {
  toc: Array<{
    title: string
    url: string
    children?: Array<{
      title: string
      url: string
    }>
  }>
}

export function DocsTableOfContents({ toc }: DocsTableOfContentsProps) {
  return (
    <div className="space-y-2">
      <h4 className="text-sm font-medium">On this page</h4>
      <ul className="space-y-1">
        {toc.map((item) => (
          <li key={item.url}>
            <a
              href={item.url}
              className={cn(
                "block text-sm text-muted-foreground hover:text-foreground transition-colors"
              )}
            >
              {item.title}
            </a>
            {item.children && (
              <ul className="ml-4 mt-1 space-y-1">
                {item.children.map((child) => (
                  <li key={child.url}>
                    <a
                      href={child.url}
                      className={cn(
                        "block text-sm text-muted-foreground hover:text-foreground transition-colors"
                      )}
                    >
                      {child.title}
                    </a>
                  </li>
                ))}
              </ul>
            )}
          </li>
        ))}
      </ul>
    </div>
  )
}
