// apps/vue/components/theme/StyleWrapper.vue
<script setup lang="ts">
import { useConfig } from '@/composables/useConfig'
import type { Style } from '@/registry/styles'

const props = defineProps<{
  styleName?: Style['name']
}>()

const config = useConfig()

const shouldRender = computed(() => {
  return !props.styleName || config.value.style === props.styleName
})
</script>

<template>
  <slot v-if="shouldRender" />
</template>

// apps/www/components/style-wrapper.tsx
"use client";

import * as React from "react";

import { useConfig } from "@/hooks/use-config";
import { Style } from "@/registry/styles";

interface StyleWrapperProps extends React.HTMLAttributes<HTMLDivElement> {
  styleName?: Style["name"];
}

export function StyleWrapper({ styleName, children }: StyleWrapperProps) {
  const [config] = useConfig();

  if (!styleName || config.style === styleName) {
    return <>{children}</>;
  }

  return null;
}
