// apps/vue/components/theme/ThemeSwitcher.vue
<script setup lang="ts">
import { watch } from 'vue'
import { useConfig } from '@/composables/useConfig'

const config = useConfig()
const route = useRoute()

watch(
  [() => route.path, () => config.value.theme],
  () => {
    document.body.classList.forEach((className) => {
      if (className.match(/^theme.*/)) {
        document.body.classList.remove(className)
      }
    })

    const theme = route.path === '/themes' ? config.value.theme : null
    if (theme) {
      document.body.classList.add(`theme-${theme}`)
    }
  },
  { immediate: true },
)
</script>

<template>
  <div />
</template>

// apps/www/components/theme-switcher.tsx
"use client";

import { useSelectedLayoutSegment } from "next/navigation";
import * as React from "react";

import { useConfig } from "@/hooks/use-config";

export function ThemeSwitcher() {
  const [config] = useConfig();
  const segment = useSelectedLayoutSegment();

  React.useEffect(() => {
    document.body.classList.forEach((className) => {
      if (className.match(/^theme.*/)) {
        document.body.classList.remove(className);
      }
    });

    const theme = segment === "themes" ? config.theme : null;
    if (theme) {
      return document.body.classList.add(`theme-${theme}`);
    }
  }, [segment, config]);

  return null;
}
