// apps/www/components/ui/label.tsx
"use client";

import * as LabelPrimitive from "@radix-ui/react-label";
import { cva, type VariantProps } from "class-variance-authority";
import * as React from "react";

import { cn } from "@/lib/utils";

const labelVariants = cva(
  "text-sm leading-none font-medium peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
);

const Label = React.forwardRef<
  React.ElementRef<typeof LabelPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof LabelPrimitive.Root> &
    VariantProps<typeof labelVariants>
>(({ className, ...props }, ref) => (
  <LabelPrimitive.Root
    ref={ref}
    className={cn(labelVariants(), className)}
    {...props}
  />
));
Label.displayName = LabelPrimitive.Root.displayName;

export { Label };

// apps/vue/components/ui/Label.vue
<script lang="ts">
import { cva, type VariantProps } from "class-variance-authority"

export const labelVariants = cva(
  "text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
)

export type LabelVariants = VariantProps<typeof labelVariants>
</script>

<script setup lang="ts">
import { Label as LabelPrimitive } from "radix-vue"
import { cn } from "~/lib/utils"

const props = defineProps<{
  class?: string
  for?: string
}>()
</script>

<template>
  <LabelPrimitive
    :for="props.for"
    :class="cn(labelVariants(), props.class)"
  >
    <slot />
  </LabelPrimitive>
</template>
