// apps/www/components/ui/toggle-group.tsx
"use client";

import * as ToggleGroupPrimitive from "@radix-ui/react-toggle-group";
import { type VariantProps } from "class-variance-authority";
import * as React from "react";

import { toggleVariants } from "@/components/ui/toggle";
import { cn } from "@/lib/utils";

const ToggleGroupContext = React.createContext<
  VariantProps<typeof toggleVariants>
>({
  size: "default",
  variant: "default",
});

const ToggleGroup = React.forwardRef<
  React.ElementRef<typeof ToggleGroupPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ToggleGroupPrimitive.Root> &
    VariantProps<typeof toggleVariants>
>(({ className, variant, size, children, ...props }, ref) => (
  <ToggleGroupPrimitive.Root
    ref={ref}
    className={cn("flex items-center justify-center gap-1", className)}
    {...props}
  >
    <ToggleGroupContext.Provider value={{ variant, size }}>
      {children}
    </ToggleGroupContext.Provider>
  </ToggleGroupPrimitive.Root>
));

ToggleGroup.displayName = ToggleGroupPrimitive.Root.displayName;

const ToggleGroupItem = React.forwardRef<
  React.ElementRef<typeof ToggleGroupPrimitive.Item>,
  React.ComponentPropsWithoutRef<typeof ToggleGroupPrimitive.Item> &
    VariantProps<typeof toggleVariants>
>(({ className, children, variant, size, ...props }, ref) => {
  const context = React.useContext(ToggleGroupContext);

  return (
    <ToggleGroupPrimitive.Item
      ref={ref}
      className={cn(
        toggleVariants({
          variant: context.variant || variant,
          size: context.size || size,
        }),
        className
      )}
      {...props}
    >
      {children}
    </ToggleGroupPrimitive.Item>
  );
});

ToggleGroupItem.displayName = ToggleGroupPrimitive.Item.displayName;

export { ToggleGroup, ToggleGroupItem };

// apps/vue/components/ui/ToggleGroup.vue
<script setup lang="ts">
import { ToggleGroupRoot } from "radix-vue"
import { provide } from "vue"
import { cn } from "@/lib/utils"
import type { ToggleVariants } from "./Toggle.vue"

defineOptions({ name: "ToggleGroup" })

const props = withDefaults(
  defineProps<{
    class?: string
    type?: "single" | "multiple"
    variant?: NonNullable<ToggleVariants["variant"]>
    size?: NonNullable<ToggleVariants["size"]>
    modelValue?: string | string[]
    defaultValue?: string | string[]
    disabled?: boolean
  }>(),
  {
    type: "single",
    variant: "default",
    size: "default",
  }
)

const emit = defineEmits<{
  "update:modelValue": [value: string | string[]]
}>()

provide("toggleGroupContext", {
  variant: props.variant,
  size: props.size,
})
</script>

<template>
  <ToggleGroupRoot
    :type="type!"
    :model-value="modelValue"
    :default-value="defaultValue"
    :disabled="disabled"
    :class="cn('flex items-center justify-center gap-1', props.class)"
    @update:model-value="emit('update:modelValue', $event)"
  >
    <slot />
  </ToggleGroupRoot>
</template>
