// apps/www/components/style-switcher.tsx
"use client"

import * as React from "react"
import { type SelectTriggerProps } from "@radix-ui/react-select"

import { cn } from "@/lib/utils"
import { useConfig } from "@/hooks/use-config"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Style, styles } from "@/registry/styles"

export function StyleSwitcher({ className, ...props }: SelectTriggerProps) {
  const [config, setConfig] = useConfig()

  return (
    <Select
      value={config.style}
      onValueChange={(value: Style["name"]) =>
        setConfig({
          ...config,
          style: value,
        })
      }
    >
      <SelectTrigger
        className={cn("h-7 w-[145px] text-xs [&_svg]:size-4", className)}
        {...props}
      >
        <span className="text-muted-foreground">Style: </span>
        <SelectValue placeholder="Select style" />
      </SelectTrigger>
      <SelectContent>
        {styles.map((style) => (
          <SelectItem key={style.name} value={style.name} className="text-xs">
            {style.label}
          </SelectItem>
        ))}
      </SelectContent>
    </Select>
  )
}

// apps/vue/components/theme/StyleSwitcher.vue
<script setup lang="ts">
import { useConfig } from '@/composables/useConfig'
import { styles, type Style } from '@/registry/styles'
import { cn } from '@/lib/utils'

defineProps<{
  class?: string
}>()

const config = useConfig()
</script>

<template>
  <Select v-model="config.style">
    <SelectTrigger :class="cn('h-7 w-[145px] text-xs [&_svg]:size-4', $props.class)">
      <span class="text-muted-foreground">Style: </span>
      <SelectValue placeholder="Select style" />
    </SelectTrigger>
    <SelectContent>
      <SelectItem
        v-for="style in styles"
        :key="style.name"
        :value="style.name"
        class="text-xs"
      >
        {{ style.label }}
      </SelectItem>
    </SelectContent>
  </Select>
</template>
