// apps/www/components/theme-wrapper.tsx
"use client";

import { useConfig } from "@/hooks/use-config";
import { cn } from "@/lib/utils";

interface ThemeWrapperProps extends React.ComponentProps<"div"> {
  defaultTheme?: string;
}

export function ThemeWrapper({
  defaultTheme,
  children,
  className,
}: ThemeWrapperProps) {
  const [config] = useConfig();

  return (
    <div
      className={cn(
        `theme-${defaultTheme || config.theme}`,
        "w-full",
        className
      )}
      style={
        {
          "--radius": `${defaultTheme ? 0.5 : config.radius}rem`,
        } as React.CSSProperties
      }
    >
      {children}
    </div>
  );
}

// apps/vue/components/theme/ThemeWrapper.vue
<script setup lang="ts">
import { cn } from '@/lib/utils'
import { useConfig } from '@/composables/useConfig'

const props = withDefaults(defineProps<{
  defaultTheme?: string
  class?: string
}>(), {
  defaultTheme: undefined,
  class: undefined,
})

const config = useConfig()
</script>

<template>
  <div
    :class="cn(
      `theme-${defaultTheme || config.theme}`,
      'w-full',
      props.class,
    )"
    :style="{ '--radius': `${defaultTheme ? 0.5 : config.radius}rem` }"
  >
    <slot />
  </div>
</template>
