// apps/www/components/main-nav.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { ExternalLink } from "lucide-react";

import { siteConfig } from "@/config/site";
import { cn } from "@/lib/utils";
import { Icons } from "@/components/icons";

export function MainNav() {
	const pathname = usePathname();

	return (
		<div className="mr-4 hidden md:flex ">
			<Link href="/" className="mr-6 flex items-center space-x-2">
				<Icons.cultLogoBasic className="size-6 fill-black dark:fill-white " />
				<span className="hidden text-lg font-bold sm:inline-block">
					cult ui
				</span>
				<span className="sr-only">{siteConfig.name}</span>
			</Link>
			<nav className="flex items-center gap-4 text-sm lg:gap-6">
				<Link
					href="/docs/components/hero-color-panels"
					className={cn(
						"text-sm font-semibold transition-colors hover:text-foreground/80",
						pathname?.startsWith("/docs/components")
							? "text-foreground"
							: "text-foreground/60",
					)}
				>
					Components
				</Link>

				<a
					href="https://aisdkagents.com/patterns"
					{/* biome-ignore lint/security/noBlankTarget: we want to open the link in a new tab */}
					target="_blank"
					// rel="noopener noreferrer"
					className={cn(
						"flex items-center gap-2 text-sm font-semibold transition-colors hover:text-foreground/80",
						pathname?.startsWith("/examples")
							? "text-foreground"
							: "text-foreground/60",
					)}
				>
					Blocks{" "}
					<span className="text-[10px] font-pixel-square shadow-inner text-black bg-[#ADFA1B] border px-1 border-black/20">
						100 new
					</span>
					<ExternalLink className="size-3" />
				</a>
				{/* <a
          href="https://aisdkagents.com/patterns"
          target="_blank"
          rel="noopener noreferrer"
          className={cn(
            "flex items-center gap-2 text-sm font-semibold transition-colors hover:text-foreground/80",
            pathname?.startsWith("/examples")
              ? "text-foreground"
              : "text-foreground/60"
          )}
        >
          AI Agents <span className="text-xs text-pink-500">(72 new)</span>
          <ExternalLink className="size-3" />
        </a> */}
				{/* <a
					href="https://pro.cult-ui.com/blocks"
					target="_blank"
					rel="noopener noreferrer"
					className={cn(
						"flex items-center gap-2 text-sm font-semibold transition-colors hover:text-foreground/80",
						pathname?.startsWith("/examples")
							? "text-foreground"
							: "text-foreground/60",
					)}
				>
					Blocks <span className="text-xs text-pink-500">(8 new)</span>
					<ExternalLink className="size-3" />
				</a> */}
				{/* Temporarily disabled */}
				{/* <a
          href="https://pro.cult-ui.com/sections"
          target="_blank"
          rel="noopener noreferrer"
          className={cn(
            "flex items-center gap-2 text-sm font-semibold transition-colors hover:text-foreground/80",
            pathname?.startsWith("/examples")
              ? "text-foreground"
              : "text-foreground/60"
          )}
        >
          Sections <span className="text-xs text-pink-500">(10 new)</span>
          <ExternalLink className="size-3" />
        </a> */}
				<a
					href="https://aisdkagents.com/templates"
					{/* biome-ignore lint/security/noBlankTarget: we want to open the link in a new tab */}
					target="_blank"
					// rel="noopener noreferrer"
					className={cn(
						"flex items-center gap-2 text-sm font-semibold transition-colors hover:text-foreground/80",
						pathname?.startsWith("/examples")
							? "text-foreground"
							: "text-foreground/60",
					)}
				>
					Templates{" "}
					<span className="text-[10px] font-pixel-square text-black shadow-inner bg-[#ADFA1B] border px-1 border-black/20">
						4 new
					</span>
					<ExternalLink className="size-3" />
				</a>
				{/* <a
					href="https://pro.cult-ui.com/templates"
					target="_blank"
					rel="noopener noreferrer"
					className={cn(
						"flex items-center gap-2 text-sm font-semibold transition-colors hover:text-foreground/80",
						pathname?.startsWith("/examples")
							? "text-foreground"
							: "text-foreground/60",
					)}
				>
					Templates <span className="text-xs text-pink-500">(1 new)</span>
					<ExternalLink className="size-3" />
				</a> */}
			</nav>
		</div>
	);
}

// apps/vue/components/site/MainNav.vue
<script setup lang="ts">
import { useRoute } from "vue-router"
import { siteConfig } from "~/config/site"
import { cn } from "~/lib/utils"

const route = useRoute()
</script>

<template>
  <div class="mr-4 hidden md:flex">
    <NuxtLink to="/" class="mr-6 flex items-center space-x-2">
      <span class="hidden text-lg font-bold sm:inline-block">cult ui</span>
      <span class="sr-only">{{ siteConfig.name }}</span>
    </NuxtLink>
    <nav class="flex items-center gap-4 text-sm lg:gap-6">
      <NuxtLink
        to="/docs/components/hero-color-panels"
        :class="
          cn(
            'text-sm font-semibold transition-colors hover:text-foreground/80',
            route.path.startsWith('/docs/components')
              ? 'text-foreground'
              : 'text-foreground/60',
          )
        "
      >
        Components
      </NuxtLink>

      <a
        href="https://aisdkagents.com/patterns"
        target="_blank"
        class="flex items-center gap-2 text-sm font-semibold transition-colors hover:text-foreground/80 text-foreground/60"
      >
        Blocks
        <span
          class="text-[10px] font-pixel-square shadow-inner text-black bg-[#ADFA1B] border px-1 border-black/20"
          >100 new</span
        >
      </a>

      <a
        href="https://aisdkagents.com/templates"
        target="_blank"
        class="flex items-center gap-2 text-sm font-semibold transition-colors hover:text-foreground/80 text-foreground/60"
      >
        Templates
        <span
          class="text-[10px] font-pixel-square text-black shadow-inner bg-[#ADFA1B] border px-1 border-black/20"
          >4 new</span
        >
      </a>
    </nav>
  </div>
</template>
