// apps/vue/components/ui/Progress.vue
<script setup lang="ts">
import { ProgressIndicator, ProgressRoot } from "radix-vue"
import { cn } from "@/lib/utils"

defineOptions({ name: "Progress" })

const props = withDefaults(
  defineProps<{
    class?: string
    modelValue?: number | null
    max?: number
  }>(),
  { modelValue: 0, max: 100 }
)
</script>

<template>
  <ProgressRoot
    :model-value="modelValue"
    :max="max"
    :class="
      cn(
        'relative h-2 w-full overflow-hidden rounded-full bg-primary/20',
        props.class
      )
    "
    v-bind="$attrs"
  >
    <ProgressIndicator
      class="h-full w-full flex-1 bg-primary transition-all"
      :style="{ transform: `translateX(-${100 - (modelValue || 0)}%)` }"
    />
  </ProgressRoot>
</template>

// apps/www/components/ui/progress.tsx
"use client";

import * as ProgressPrimitive from "@radix-ui/react-progress";
import * as React from "react";

import { cn } from "@/lib/utils";

const Progress = React.forwardRef<
  React.ElementRef<typeof ProgressPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof ProgressPrimitive.Root>
>(({ className, value, ...props }, ref) => (
  <ProgressPrimitive.Root
    ref={ref}
    className={cn(
      "bg-primary/20 relative h-2 w-full overflow-hidden rounded-full",
      className
    )}
    {...props}
  >
    <ProgressPrimitive.Indicator
      className="bg-primary h-full w-full flex-1 transition-all"
      style={{ transform: `translateX(-${100 - (value || 0)}%)` }}
    />
  </ProgressPrimitive.Root>
));
Progress.displayName = ProgressPrimitive.Root.displayName;

export { Progress };
