// apps/www/registry/default/ui/feature-voting.tsx
"use client";

import { useControllableState } from "@radix-ui/react-use-controllable-state";
import {
  Children,
  createContext,
  isValidElement,
  useCallback,
  useContext,
  useMemo,
  type ComponentProps,
  type MouseEvent,
} from "react";

/* -----------------------------------------------------------------------------
 * Types
 * -------------------------------------------------------------------------- */

export type FeatureVotingValue = Record<string, number>;

export interface FeatureVotingRootProps extends Omit<
  ComponentProps<"ul">,
  "defaultValue"
> {
  /** Current vote counts (controlled) */
  value?: FeatureVotingValue;
  /** Initial vote counts (uncontrolled) */
  defaultValue?: FeatureVotingValue;
  /** Callback when votes change */
  onValueChange?: (value: FeatureVotingValue) => void;
  /** Set of feature IDs the current user has voted for */
  votedFeatures?: Set<string>;
  /** Default voted features (uncontrolled) */
  defaultVotedFeatures?: Set<string>;
  /** Callback when user votes/unvotes */
  onVotedFeaturesChange?: (votedFeatures: Set<string>) => void;
  /** Whether voting is disabled */
  disabled?: boolean;
}

export interface FeatureVotingItemProps extends ComponentProps<"li"> {
  /** Unique identifier for this feature */
  value: string;
  /** Whether this specific item is disabled */
  disabled?: boolean;
}

export type FeatureVotingTriggerProps = ComponentProps<"button">;

export type FeatureVotingCountProps = ComponentProps<"span">;

export type FeatureVotingTitleProps = ComponentProps<"span">;

export type FeatureVotingDescriptionProps = ComponentProps<"span">;

export interface FeatureVotingGroupProps extends ComponentProps<"div"> {
  /** Sort items by vote count */
  sortBy?: "votes-asc" | "votes-desc" | "none";
}

/* -----------------------------------------------------------------------------
 * Context
 * -------------------------------------------------------------------------- */

interface FeatureVotingContextValue {
  votes: FeatureVotingValue;
  votedFeatures: Set<string>;
  disabled: boolean;
  vote: (featureId: string) => void;
  unvote: (featureId: string) => void;
  toggleVote: (featureId: string) => void;
  getVoteCount: (featureId: string) => number;
  hasVoted: (featureId: string) => boolean;
}

const FeatureVotingContext = createContext<FeatureVotingContextValue | null>(
  null
);

function useFeatureVotingContext() {
  const context = useContext(FeatureVotingContext);
  if (!context) {
    throw new Error(
      "FeatureVoting components must be used within FeatureVoting.Root"
    );
  }
  return context;
}

interface FeatureVotingItemContextValue {
  featureId: string;
  disabled: boolean;
}

const FeatureVotingItemContext =
  createContext<FeatureVotingItemContextValue | null>(null);

function useFeatureVotingItemContext() {
  const context = useContext(FeatureVotingItemContext);
  if (!context) {
    throw new Error(
      "FeatureVoting.Item sub-components must be used within FeatureVoting.Item"
    );
  }
  return context;
}

/* -----------------------------------------------------------------------------
 * Root
 * -------------------------------------------------------------------------- */

function FeatureVotingRoot({
  value: controlledValue,
  defaultValue = {},
  onValueChange,
  votedFeatures: controlledVotedFeatures,
  defaultVotedFeatures,
  onVotedFeaturesChange,
  disabled = false,
  children,
  ...props
}: FeatureVotingRootProps) {
  const [votes, setVotes] = useControllableState<FeatureVotingValue>({
    prop: controlledValue,
    defaultProp: defaultValue,
    onChange: onValueChange,
  });

  const [votedFeaturesArray, setVotedFeaturesArray] = useControllableState({
    prop: controlledVotedFeatures
      ? Array.from(controlledVotedFeatures)
      : undefined,
    defaultProp: defaultVotedFeatures ? Array.from(defaultVotedFeatures) : [],
    onChange: (arr) => onVotedFeaturesChange?.(new Set(arr)),
  });

  const votedFeatures = useMemo(
    () => new Set(votedFeaturesArray),
    [votedFeaturesArray]
  );

  const vote = useCallback(
    (featureId: string) => {
      if (disabled || votedFeatures.has(featureId)) {
        return;
      }

      setVotes((prev) => ({
        ...prev,
        [featureId]: (prev?.[featureId] ?? 0) + 1,
      }));
      setVotedFeaturesArray((prev) => [...(prev ?? []), featureId]);
    },
    [disabled, votedFeatures, setVotes, setVotedFeaturesArray]
  );

  const unvote = useCallback(
    (featureId: string) => {
      if (disabled || !votedFeatures.has(featureId)) {
        return;
      }

      setVotes((prev) => ({
        ...prev,
        [featureId]: Math.max((prev?.[featureId] ?? 0) - 1, 0),
      }));
      setVotedFeaturesArray((prev) =>
        (prev ?? []).filter((id) => id !== featureId)
      );
    },
    [disabled, votedFeatures, setVotes, setVotedFeaturesArray]
  );

  const toggleVote = useCallback(
    (featureId: string) => {
      if (votedFeatures.has(featureId)) {
        unvote(featureId);
      } else {
        vote(featureId);
      }
    },
    [votedFeatures, vote, unvote]
  );

  const getVoteCount = useCallback(
    (featureId: string) => votes?.[featureId] ?? 0,
    [votes]
  );

  const hasVoted = useCallback(
    (featureId: string) => votedFeatures.has(featureId),
    [votedFeatures]
  );

  const contextValue = useMemo(
    () => ({
      votes: votes ?? {},
      votedFeatures,
      disabled,
      vote,
      unvote,
      toggleVote,
      getVoteCount,
      hasVoted,
    }),
    [
      votes,
      votedFeatures,
      disabled,
      vote,
      unvote,
      toggleVote,
      getVoteCount,
      hasVoted,
    ]
  );

  return (
    <FeatureVotingContext.Provider value={contextValue}>
      <ul
        aria-label="Feature voting list"
        data-disabled={disabled ? true : undefined}
        {...props}
      >
        {children}
      </ul>
    </FeatureVotingContext.Provider>
  );
}

/* -----------------------------------------------------------------------------
 * Group (optional sorting wrapper)
 * -------------------------------------------------------------------------- */

function FeatureVotingGroup({
  sortBy = "none",
  children,
  ...props
}: FeatureVotingGroupProps) {
  const { votes } = useFeatureVotingContext();

  const sortedChildren = useMemo(() => {
    if (sortBy === "none") {
      return children;
    }

    const childArray = Children.toArray(children);

    return childArray.sort((a, b) => {
      if (!(isValidElement(a) && isValidElement(b))) {
        return 0;
      }

      const aValue = (a.props as FeatureVotingItemProps).value;
      const bValue = (b.props as FeatureVotingItemProps).value;
      const aVotes = votes[aValue] ?? 0;
      const bVotes = votes[bValue] ?? 0;

      return sortBy === "votes-desc" ? bVotes - aVotes : aVotes - bVotes;
    });
  }, [children, sortBy, votes]);

  return <div {...props}>{sortedChildren}</div>;
}

/* -----------------------------------------------------------------------------
 * Item
 * -------------------------------------------------------------------------- */

function FeatureVotingItem({
  value,
  disabled: itemDisabled = false,
  children,
  ...props
}: FeatureVotingItemProps) {
  const {
    disabled: rootDisabled,
    hasVoted,
    getVoteCount,
  } = useFeatureVotingContext();
  const disabled = rootDisabled || itemDisabled;
  const voted = hasVoted(value);
  const voteCount = getVoteCount(value);

  const itemContextValue = useMemo(
    () => ({ featureId: value, disabled }),
    [value, disabled]
  );

  return (
    <FeatureVotingItemContext.Provider value={itemContextValue}>
      <li
        data-disabled={disabled ? true : undefined}
        data-feature={value}
        data-slot="feature-voting-item"
        data-vote-count={voteCount}
        data-voted={voted ? true : undefined}
        {...props}
      >
        {children}
      </li>
    </FeatureVotingItemContext.Provider>
  );
}

/* -----------------------------------------------------------------------------
 * Trigger
 * -------------------------------------------------------------------------- */

function FeatureVotingTrigger({
  children,
  onClick,
  ...props
}: FeatureVotingTriggerProps) {
  const {
    toggleVote,
    hasVoted,
    disabled: rootDisabled,
  } = useFeatureVotingContext();
  const { featureId, disabled: itemDisabled } = useFeatureVotingItemContext();

  const disabled = rootDisabled || itemDisabled;
  const voted = hasVoted(featureId);

  const handleClick = useCallback(
    (event: MouseEvent<HTMLButtonElement>) => {
      onClick?.(event);
      if (!(event.defaultPrevented || disabled)) {
        toggleVote(featureId);
      }
    },
    [onClick, disabled, toggleVote, featureId]
  );

  return (
    <button
      aria-label={voted ? "Remove vote for feature" : "Vote for feature"}
      aria-pressed={voted}
      data-slot="feature-voting-trigger"
      data-state={voted ? "voted" : "idle"}
      disabled={disabled}
      onClick={handleClick}
      type="button"
      {...props}
    >
      {children}
    </button>
  );
}

/* -----------------------------------------------------------------------------
 * Count
 * -------------------------------------------------------------------------- */

function FeatureVotingCount({ children, ...props }: FeatureVotingCountProps) {
  const { getVoteCount } = useFeatureVotingContext();
  const { featureId } = useFeatureVotingItemContext();

  const count = getVoteCount(featureId);

  return (
    <span data-slot="feature-voting-count" {...props}>
      {children ?? count}
    </span>
  );
}

/* -----------------------------------------------------------------------------
 * Title
 * -------------------------------------------------------------------------- */

function FeatureVotingTitle({ children, ...props }: FeatureVotingTitleProps) {
  return (
    <span data-slot="feature-voting-title" {...props}>
      {children}
    </span>
  );
}

/* -----------------------------------------------------------------------------
 * Description
 * -------------------------------------------------------------------------- */

function FeatureVotingDescription({
  children,
  ...props
}: FeatureVotingDescriptionProps) {
  return (
    <span data-slot="feature-voting-description" {...props}>
      {children}
    </span>
  );
}

/* -----------------------------------------------------------------------------
 * Hook for external access
 * -------------------------------------------------------------------------- */

export function useFeatureVoting() {
  return useFeatureVotingContext();
}

/* -----------------------------------------------------------------------------
 * Export
 * -------------------------------------------------------------------------- */

export const FeatureVoting = {
  Root: FeatureVotingRoot,
  Group: FeatureVotingGroup,
  Item: FeatureVotingItem,
  Trigger: FeatureVotingTrigger,
  Count: FeatureVotingCount,
  Title: FeatureVotingTitle,
  Description: FeatureVotingDescription,
};

export {
  FeatureVotingRoot,
  FeatureVotingGroup,
  FeatureVotingItem,
  FeatureVotingTrigger,
  FeatureVotingCount,
  FeatureVotingTitle,
  FeatureVotingDescription,
};

// apps/vue/registry/default/ui/FeatureVoting.vue
<script setup lang="ts">
import { ref, computed, provide, inject, type InjectionKey, type Ref } from 'vue'

// Types
export type FeatureVotingValue = Record<string, number>

interface FeatureVotingContext {
  votes: Ref<FeatureVotingValue>
  votedFeatures: Ref<Set<string>>
  disabled: boolean
  vote: (featureId: string) => void
  unvote: (featureId: string) => void
  toggleVote: (featureId: string) => void
  getVoteCount: (featureId: string) => number
  hasVoted: (featureId: string) => boolean
}

interface FeatureVotingItemContext {
  featureId: string
  disabled: boolean
}

const FEATURE_VOTING_KEY: InjectionKey<FeatureVotingContext> = Symbol('feature-voting')
const FEATURE_VOTING_ITEM_KEY: InjectionKey<FeatureVotingItemContext> = Symbol('feature-voting-item')

export function useFeatureVoting() {
  const ctx = inject(FEATURE_VOTING_KEY)
  if (!ctx) throw new Error('FeatureVoting components must be used within FeatureVotingRoot')
  return ctx
}

export function useFeatureVotingItem() {
  const ctx = inject(FEATURE_VOTING_ITEM_KEY)
  if (!ctx) throw new Error('FeatureVoting.Item sub-components must be used within FeatureVoting.Item')
  return ctx
}

// Props
interface Props {
  modelValue?: FeatureVotingValue
  defaultValue?: FeatureVotingValue
  votedFeatures?: Set<string>
  defaultVotedFeatures?: Set<string>
  disabled?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: undefined,
  defaultValue: () => ({}),
  votedFeatures: undefined,
  defaultVotedFeatures: undefined,
  disabled: false,
})

const emit = defineEmits<{
  'update:modelValue': [value: FeatureVotingValue]
  'update:votedFeatures': [features: Set<string>]
}>()

// State
const internalVotes = ref<FeatureVotingValue>(props.defaultValue)
const internalVotedFeatures = ref<Set<string>>(props.defaultVotedFeatures ?? new Set())

const votes = computed(() => props.modelValue ?? internalVotes.value)
const votedFeaturesSet = computed(() => props.votedFeatures ?? internalVotedFeatures.value)

function vote(featureId: string) {
  if (props.disabled || votedFeaturesSet.value.has(featureId)) return

  const newVotes = { ...votes.value, [featureId]: (votes.value[featureId] ?? 0) + 1 }
  if (props.modelValue !== undefined) {
    emit('update:modelValue', newVotes)
  } else {
    internalVotes.value = newVotes
  }

  const newVoted = new Set(votedFeaturesSet.value)
  newVoted.add(featureId)
  if (props.votedFeatures !== undefined) {
    emit('update:votedFeatures', newVoted)
  } else {
    internalVotedFeatures.value = newVoted
  }
}

function unvote(featureId: string) {
  if (props.disabled || !votedFeaturesSet.value.has(featureId)) return

  const newVotes = { ...votes.value, [featureId]: Math.max((votes.value[featureId] ?? 0) - 1, 0) }
  if (props.modelValue !== undefined) {
    emit('update:modelValue', newVotes)
  } else {
    internalVotes.value = newVotes
  }

  const newVoted = new Set(votedFeaturesSet.value)
  newVoted.delete(featureId)
  if (props.votedFeatures !== undefined) {
    emit('update:votedFeatures', newVoted)
  } else {
    internalVotedFeatures.value = newVoted
  }
}

function toggleVote(featureId: string) {
  if (votedFeaturesSet.value.has(featureId)) {
    unvote(featureId)
  } else {
    vote(featureId)
  }
}

function getVoteCount(featureId: string) {
  return votes.value[featureId] ?? 0
}

function hasVoted(featureId: string) {
  return votedFeaturesSet.value.has(featureId)
}

provide(FEATURE_VOTING_KEY, {
  votes: computed(() => votes.value) as unknown as Ref<FeatureVotingValue>,
  votedFeatures: computed(() => votedFeaturesSet.value) as unknown as Ref<Set<string>>,
  disabled: props.disabled,
  vote,
  unvote,
  toggleVote,
  getVoteCount,
  hasVoted,
})
</script>

<template>
  <ul
    aria-label="Feature voting list"
    :data-disabled="disabled ? true : undefined"
  >
    <slot
      :votes="votes"
      :voted-features="votedFeaturesSet"
      :vote="vote"
      :unvote="unvote"
      :toggle-vote="toggleVote"
      :get-vote-count="getVoteCount"
      :has-voted="hasVoted"
    />
  </ul>
</template>
