// apps/www/components/fade-in.tsx
"use client";

import { motion, useReducedMotion } from "motion/react";
import { createContext, useContext } from "react";

const FadeInStaggerContext = createContext(false);

const viewport = { once: true, margin: "0px 0px -200px" };

export function FadeIn(props: any) {
  let shouldReduceMotion = useReducedMotion();
  let isInStaggerGroup = useContext(FadeInStaggerContext);

  return (
    <motion.div
      variants={{
        hidden: { opacity: 0, y: shouldReduceMotion ? 0 : 24 },
        visible: { opacity: 1, y: 0 },
      }}
      transition={{ duration: 0.5 }}
      {...(isInStaggerGroup
        ? {}
        : {
            initial: "hidden",
            whileInView: "visible",
            viewport,
          })}
      {...props}
    />
  );
}

export function FadeInStagger({ faster = false, ...props }) {
  return (
    <FadeInStaggerContext.Provider value={true}>
      <motion.div
        initial="hidden"
        whileInView="visible"
        viewport={viewport}
        transition={{ staggerChildren: faster ? 0.12 : 0.2 }}
        {...props}
      />
    </FadeInStaggerContext.Provider>
  );
}

// apps/vue/components/FadeIn.vue
<script setup lang="ts">
import { inject, provide, ref } from 'vue'
import { Motion, useReducedMotion } from 'motion-v'

const isInStaggerGroup = inject<boolean>('fadeInStaggerGroup', false)
const shouldReduceMotion = useReducedMotion()

const viewport = { once: true, margin: '0px 0px -200px' }

interface Props {
  class?: string
}

defineProps<Props>()
</script>

<template>
  <Motion
    :class="props.class"
    :variants="{
      hidden: { opacity: 0, y: shouldReduceMotion ? 0 : 24 },
      visible: { opacity: 1, y: 0 },
    }"
    :transition="{ duration: 0.5 }"
    v-bind="
      isInStaggerGroup
        ? {}
        : {
            initial: 'hidden',
            whileInView: 'visible',
            viewport,
          }
    "
  >
    <slot />
  </Motion>
</template>
