// apps/www/components/texture-wrapper.tsx
import React, { ReactNode } from "react"

interface BackgroundWrapperProps {
  children: ReactNode
  url: string
}

const BgNoiseWrapper: React.FC<BackgroundWrapperProps> = ({
  children,
  url,
}) => {
  return (
    <div className="relative">
      <div
        className="fixed inset-0 mix-blend-hard-light pointer-events-none"
        style={{ backgroundImage: `url('${url}')` }}
      ></div>
      <div className="relative">{children}</div>
    </div>
  )
}

export default BgNoiseWrapper

// apps/vue/components/TextureWrapper.vue
<script setup lang="ts">
interface Props {
  url: string
}

defineProps<Props>()
</script>

<template>
  <div class="relative">
    <div
      class="pointer-events-none fixed inset-0 mix-blend-hard-light"
      :style="{ backgroundImage: `url('${url}')` }"
    />
    <div class="relative">
      <slot />
    </div>
  </div>
</template>
