// apps/www/registry/default/example/animated-number-demo.tsx
"use client";

import { Minus, Plus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { AnimatedNumber } from "@/registry/default/ui/animated-number";
import { GradientHeading } from "@/registry/default/ui/gradient-heading";
import {
  TextureCardContent,
  TextureCardHeader,
  TextureCardStyled,
} from "@/registry/default/ui/texture-card";

function PrecisionExample() {
  const [value, setValue] = useState(14.5678);

  return (
    <TextureCardStyled>
      <TextureCardHeader className="pl-3">
        <GradientHeading size="xxs">Precision</GradientHeading>
      </TextureCardHeader>
      <TextureCardContent>
        <div className="flex gap-2">
          <div
            className="text-2xl font-bold"
            style={{ minWidth: "80px", textAlign: "left" }}
          >
            <AnimatedNumber value={value} precision={2} />
          </div>
          <Button
            size="sm"
            variant="ghost"
            className="border-primary/10 ml-auto rounded-full border py-5"
            onClick={() => setValue(value + 13.456)}
          >
            <Plus className="h-4 w-4" />
          </Button>
        </div>
      </TextureCardContent>
    </TextureCardStyled>
  );
}

function FormatExample() {
  const [value, setValue] = useState(10);

  const customFormat = (num: number) => `$${num.toFixed(2)}`;

  return (
    <TextureCardStyled>
      <TextureCardHeader className="pl-3">
        <GradientHeading size="xxs">Format</GradientHeading>
      </TextureCardHeader>
      <TextureCardContent>
        <div className="flex gap-2">
          <div
            className="text-2xl font-bold"
            style={{ minWidth: "120px", textAlign: "left" }}
          >
            <AnimatedNumber value={value} format={customFormat} />
          </div>
          <Button
            size="sm"
            variant="ghost"
            className="border-primary/10 ml-auto rounded-full border py-5"
            onClick={() => setValue(value + 50)}
          >
            <Plus className="h-4 w-4" />
          </Button>
        </div>
      </TextureCardContent>
    </TextureCardStyled>
  );
}

function HooksExample() {
  const [value, setValue] = useState(10);

  const handleAnimationStart = () => {
    toast("🏁 Animation started ");
  };

  const handleAnimationComplete = () => {
    toast("✅ Animation completed ");
  };

  return (
    <TextureCardStyled>
      <TextureCardHeader className="pl-3">
        <GradientHeading size="xxs">Callbacks</GradientHeading>
      </TextureCardHeader>
      <TextureCardContent>
        <div className="flex gap-2">
          <div
            className="text-2xl font-bold"
            style={{ minWidth: "50px", textAlign: "left" }}
          >
            <AnimatedNumber
              value={value}
              onAnimationStart={handleAnimationStart}
              onAnimationComplete={handleAnimationComplete}
            />
          </div>
          <Button
            size="sm"
            variant="ghost"
            className="border-primary/10 ml-auto rounded-full border py-5"
            onClick={() => setValue(value + 20)}
          >
            <Plus className="h-4 w-4" />
          </Button>
        </div>
      </TextureCardContent>
    </TextureCardStyled>
  );
}

function CustomSpringExample() {
  const [value, setValue] = useState(1000);
  const [mass, setMass] = useState(1);
  const [stiffness, setStiffness] = useState(100);
  const [damping, setDamping] = useState(40);

  const handleValueChange =
    (setter: (value: number) => void, minValue: number) =>
    (values: number[]) => {
      const newValue = Math.max(values[0], minValue);
      setter(newValue);
    };

  return (
    <TextureCardStyled className="w-full">
      <TextureCardHeader className="px-3">
        <GradientHeading size="sm">Custom Spring Properties</GradientHeading>
      </TextureCardHeader>
      <TextureCardContent className="flex flex-col items-center justify-between gap-8 sm:flex-row">
        <div
          className="mr-auto flex text-6xl font-bold"
          style={{ minWidth: "150px", textAlign: "right" }}
        >
          <AnimatedNumber
            value={value}
            mass={mass}
            stiffness={stiffness}
            damping={damping}
          />
        </div>

        <div className="flex flex-col gap-3 px-2">
          <Button
            className="border-primary/10 rounded-full border py-5"
            onClick={() => setValue(value + 500)}
          >
            <Plus className="mr-2 h-4 w-4" />
            Increase
          </Button>
          <Button
            className="border-primary/10 rounded-full border py-5"
            disabled={value <= 500}
            onClick={() => setValue(value - 300)}
          >
            <Minus className="mr-2 h-4 w-4" />
            Decrease
          </Button>
        </div>
        <div className="ml-auto w-full">
          <div className="flex flex-col gap-4">
            <div className="ml-auto w-full">
              <label>Mass: {mass}</label>
              <Slider
                defaultValue={[mass]}
                max={5}
                step={0.1}
                onValueChange={handleValueChange(setMass, 0.1)}
              />
            </div>
            <div className="ml-auto w-full">
              <label>Stiffness: {stiffness}</label>
              <Slider
                defaultValue={[stiffness]}
                max={200}
                step={1}
                onValueChange={handleValueChange(setStiffness, 1)}
              />
            </div>
            <div className="ml-auto w-full">
              <label>Damping: {damping}</label>
              <Slider
                defaultValue={[damping]}
                max={50}
                step={1}
                onValueChange={handleValueChange(setDamping, 1)}
              />
            </div>
          </div>
        </div>
      </TextureCardContent>
    </TextureCardStyled>
  );
}

export default function AnimatedNumberExamples() {
  return (
    <div className="mx-auto max-w-xl gap-4 py-6">
      <div className="flex w-full flex-col justify-between gap-2">
        <CustomSpringExample />
        <div className="flex flex-col gap-2 sm:flex-row">
          <PrecisionExample />
          <FormatExample />
          <HooksExample />
        </div>
      </div>
    </div>
  );
}

// apps/vue/registry/default/example/AnimatedNumberDemo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Minus, Plus } from 'lucide-vue-next'
import { AnimatedNumber } from '@/registry/default/ui/animated-number'
import { GradientHeading } from '@/registry/default/ui/gradient-heading'
import {
  TextureCardContent,
  TextureCardHeader,
  TextureCardStyled,
} from '@/registry/default/ui/texture-card'
</script>

<template>
  <div class="max-w-xl gap-4 py-6 mx-auto">
    <div class="w-full flex flex-col gap-2 justify-between">
      <CustomSpringExample />
      <div class="flex flex-col sm:flex-row gap-2">
        <PrecisionExample />
        <FormatExample />
        <HooksExample />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, h } from 'vue'

const PrecisionExample = defineComponent({
  setup() {
    const value = ref(14.5678)
    return () =>
      h(TextureCardStyled, null, () =>
        [
          h(TextureCardHeader, { class: 'pl-3' }, () =>
            h(GradientHeading, { size: 'xxs' }, () => 'Precision')
          ),
          h(TextureCardContent, null, () =>
            h('div', { class: 'flex gap-2' }, [
              h('div', { class: 'text-2xl font-bold', style: { minWidth: '80px', textAlign: 'left' } }, [
                h(AnimatedNumber, { value: value.value, precision: 2 }),
              ]),
              h('button', {
                class: 'border border-primary/10 rounded-full ml-auto py-5 px-3',
                onClick: () => { value.value += 13.456 },
              }, [h(Plus, { class: 'h-4 w-4' })]),
            ])
          ),
        ]
      )
  },
})

const FormatExample = defineComponent({
  setup() {
    const value = ref(10)
    const customFormat = (num: number) => `$${num.toFixed(2)}`
    return () =>
      h(TextureCardStyled, null, () =>
        [
          h(TextureCardHeader, { class: 'pl-3' }, () =>
            h(GradientHeading, { size: 'xxs' }, () => 'Format')
          ),
          h(TextureCardContent, null, () =>
            h('div', { class: 'flex gap-2' }, [
              h('div', { class: 'text-2xl font-bold', style: { minWidth: '120px', textAlign: 'left' } }, [
                h(AnimatedNumber, { value: value.value, format: customFormat }),
              ]),
              h('button', {
                class: 'border border-primary/10 rounded-full ml-auto py-5 px-3',
                onClick: () => { value.value += 50 },
              }, [h(Plus, { class: 'h-4 w-4' })]),
            ])
          ),
        ]
      )
  },
})

const HooksExample = defineComponent({
  setup() {
    const value = ref(10)
    return () =>
      h(TextureCardStyled, null, () =>
        [
          h(TextureCardHeader, { class: 'pl-3' }, () =>
            h(GradientHeading, { size: 'xxs' }, () => 'Callbacks')
          ),
          h(TextureCardContent, null, () =>
            h('div', { class: 'flex gap-2' }, [
              h('div', { class: 'text-2xl font-bold', style: { minWidth: '50px', textAlign: 'left' } }, [
                h(AnimatedNumber, { value: value.value }),
              ]),
              h('button', {
                class: 'border border-primary/10 rounded-full ml-auto py-5 px-3',
                onClick: () => { value.value += 20 },
              }, [h(Plus, { class: 'h-4 w-4' })]),
            ])
          ),
        ]
      )
  },
})

const CustomSpringExample = defineComponent({
  setup() {
    const value = ref(1000)
    const mass = ref(1)
    const stiffness = ref(100)
    const damping = ref(40)
    return () =>
      h(TextureCardStyled, { class: 'w-full' }, () =>
        [
          h(TextureCardHeader, { class: 'px-3' }, () =>
            h(GradientHeading, { size: 'sm' }, () => 'Custom Spring Properties')
          ),
          h(TextureCardContent, { class: 'flex flex-col sm:flex-row justify-between items-center gap-8' }, () => [
            h('div', { class: 'text-6xl font-bold mr-auto flex', style: { minWidth: '150px', textAlign: 'right' } }, [
              h(AnimatedNumber, { value: value.value, mass: mass.value, stiffness: stiffness.value, damping: damping.value }),
            ]),
            h('div', { class: 'flex flex-col gap-3 px-2' }, [
              h('button', { class: 'border border-primary/10 rounded-full py-5 px-4', onClick: () => { value.value += 500 } }, [
                h(Plus, { class: 'h-4 w-4 mr-2' }), 'Increase',
              ]),
              h('button', {
                class: 'border border-primary/10 rounded-full py-5 px-4',
                disabled: value.value <= 500,
                onClick: () => { value.value -= 300 },
              }, [h(Minus, { class: 'h-4 w-4 mr-2' }), 'Decrease']),
            ]),
            h('div', { class: 'ml-auto w-full' }, [
              h('div', { class: 'flex flex-col gap-4' }, [
                h('div', { class: 'ml-auto w-full' }, [
                  h('label', null, `Mass: ${mass.value}`),
                  h('input', { type: 'range', min: 0.1, max: 5, step: 0.1, value: mass.value, class: 'w-full', onInput: (e: Event) => { mass.value = Number((e.target as HTMLInputElement).value) } }),
                ]),
                h('div', { class: 'ml-auto w-full' }, [
                  h('label', null, `Stiffness: ${stiffness.value}`),
                  h('input', { type: 'range', min: 1, max: 200, step: 1, value: stiffness.value, class: 'w-full', onInput: (e: Event) => { stiffness.value = Number((e.target as HTMLInputElement).value) } }),
                ]),
                h('div', { class: 'ml-auto w-full' }, [
                  h('label', null, `Damping: ${damping.value}`),
                  h('input', { type: 'range', min: 1, max: 50, step: 1, value: damping.value, class: 'w-full', onInput: (e: Event) => { damping.value = Number((e.target as HTMLInputElement).value) } }),
                ]),
              ]),
            ]),
          ]),
        ]
      )
  },
})

export default defineComponent({
  components: { PrecisionExample, FormatExample, HooksExample, CustomSpringExample },
})
</script>
