// apps/www/registry/default/example/bg-image-texture-demo.tsx
"use client"

import { useState } from "react"
import { Download } from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Slider } from "@/components/ui/slider"
import { BackgroundImageTexture } from "@/registry/default/ui/bg-image-texture"
import type { TextureVariant } from "@/registry/default/ui/bg-image-texture"

const textureVariants: TextureVariant[] = [
  "fabric-of-squares",
  "grid-noise",
  "inflicted",
  "debut-light",
  "groovepaper",
  "none",
]

const textureMap: Record<Exclude<TextureVariant, "none">, string> = {
  "fabric-of-squares": "/textures/fabric-of-squares.png",
  "grid-noise": "/textures/grid-noise.png",
  inflicted: "/textures/inflicted.png",
  "debut-light": "/textures/debut-light.png",
  groovepaper: "/textures/groovepaper.png",
}

async function downloadTexture(variant: Exclude<TextureVariant, "none">) {
  const url = textureMap[variant]
  try {
    const response = await fetch(url)
    const blob = await response.blob()
    const blobUrl = window.URL.createObjectURL(blob)
    const link = document.createElement("a")
    link.href = blobUrl
    link.download = `${variant}.png`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(blobUrl)
  } catch {
    // Fallback to direct link if fetch fails
    const link = document.createElement("a")
    link.href = url
    link.download = `${variant}.png`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }
}

export default function BackgroundImageTextureDemo() {
  const [selectedVariant, setSelectedVariant] =
    useState<TextureVariant>("fabric-of-squares")
  const [opacity, setOpacity] = useState([0.5])

  return (
    <div className="space-y-8 p-6">
      {/* Controls */}
      <Card>
        <CardHeader>
          <CardTitle>Texture Controls</CardTitle>
          <CardDescription>
            Select a texture variant and adjust the opacity
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label>Texture Variant</Label>
            <div className="flex flex-wrap gap-2">
              {textureVariants.map((variant) => (
                <Button
                  key={variant}
                  variant={selectedVariant === variant ? "default" : "outline"}
                  size="sm"
                  onClick={() => setSelectedVariant(variant)}
                >
                  {variant === "none" ? "None" : variant}
                </Button>
              ))}
            </div>
          </div>
          <div className="space-y-2">
            <Label>Opacity: {opacity[0].toFixed(2)}</Label>
            <Slider
              value={opacity}
              onValueChange={setOpacity}
              min={0}
              max={1}
              step={0.01}
              className="w-full"
            />
          </div>
        </CardContent>
      </Card>

      {/* Preview with Content */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Preview with Content</CardTitle>
              <CardDescription>
                See how the texture looks with content on top
              </CardDescription>
            </div>
            {selectedVariant !== "none" && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => downloadTexture(selectedVariant)}
                className="gap-2"
              >
                <Download className="h-4 w-4" />
                Download Texture
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent>
          <BackgroundImageTexture
            variant={selectedVariant}
            opacity={opacity[0]}
            className="border-border min-h-[400px] rounded-lg border p-8"
          >
            <div className="space-y-6">
              <div>
                <h3 className="text-foreground mb-2 text-3xl font-bold">
                  Texture Background
                </h3>
                <p className="text-muted-foreground text-lg">
                  This content sits on top of the texture layer. Adjust the
                  opacity slider to see how the texture affects the background.
                  The texture is fully interactive and customizable.
                </p>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="bg-card/50 border-border rounded-lg border p-4">
                  <h4 className="mb-2 font-semibold">Feature 1</h4>
                  <p className="text-muted-foreground text-sm">
                    Content with texture background
                  </p>
                </div>
                <div className="bg-card/50 border-border rounded-lg border p-4">
                  <h4 className="mb-2 font-semibold">Feature 2</h4>
                  <p className="text-muted-foreground text-sm">
                    More content examples
                  </p>
                </div>
              </div>
            </div>
          </BackgroundImageTexture>
        </CardContent>
      </Card>

      {/* All Variants Showcase */}
      <div className="space-y-4">
        <h3 className="text-2xl font-semibold">All Texture Variants</h3>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
          {textureVariants
            .filter((v) => v !== "none")
            .map((variant) => (
              <Card key={variant}>
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <CardTitle className="text-lg capitalize">
                      {variant.replace(/-/g, " ")}
                    </CardTitle>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => downloadTexture(variant)}
                      className="h-8 w-8 p-0"
                      title={`Download ${variant}.png`}
                    >
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                </CardHeader>
                <CardContent>
                  <BackgroundImageTexture
                    variant={variant}
                    opacity={0.5}
                    className="border-border flex h-48 items-center justify-center rounded-lg border p-6"
                  >
                    <div className="text-center">
                      <p className="text-foreground text-sm font-medium">
                        {variant}
                      </p>
                      <p className="text-muted-foreground mt-1 text-xs">
                        Opacity: 0.5
                      </p>
                    </div>
                  </BackgroundImageTexture>
                </CardContent>
              </Card>
            ))}
        </div>
      </div>

      {/* Opacity Variations */}
      <div className="space-y-4">
        <h3 className="text-2xl font-semibold">Opacity Variations</h3>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          {[0.2, 0.5, 0.8].map((opacityValue) => (
            <Card key={opacityValue}>
              <CardHeader>
                <CardTitle className="text-lg">
                  Opacity: {opacityValue}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <BackgroundImageTexture
                  variant="grid-noise"
                  opacity={opacityValue}
                  className="border-border flex h-48 items-center justify-center rounded-lg border p-6"
                >
                  <div className="text-center">
                    <p className="text-foreground text-sm font-medium">
                      grid-noise texture
                    </p>
                    <p className="text-muted-foreground mt-1 text-xs">
                      Opacity: {opacityValue}
                    </p>
                  </div>
                </BackgroundImageTexture>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* Use Case Examples */}
      <div className="space-y-4">
        <h3 className="text-2xl font-semibold">Use Case Examples</h3>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
          {/* Card with Texture */}
          <Card>
            <CardHeader>
              <CardTitle>Card with Texture</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <BackgroundImageTexture
                variant="debut-light"
                opacity={0.3}
                className="rounded-b-lg p-6"
              >
                <div className="space-y-2">
                  <h4 className="font-semibold">Beautiful Card</h4>
                  <p className="text-muted-foreground text-sm">
                    Cards look great with subtle texture backgrounds
                  </p>
                </div>
              </BackgroundImageTexture>
            </CardContent>
          </Card>

          {/* Hero Section */}
          <Card>
            <CardHeader>
              <CardTitle>Hero Section</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
              <BackgroundImageTexture
                variant="groovepaper"
                opacity={0.4}
                className="flex min-h-[200px] items-center justify-center rounded-b-lg p-6"
              >
                <div className="space-y-2 text-center">
                  <h4 className="text-2xl font-bold">Hero Title</h4>
                  <p className="text-muted-foreground text-sm">
                    Perfect for hero sections and banners
                  </p>
                </div>
              </BackgroundImageTexture>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

// apps/vue/registry/default/example/BgImageTextureDemo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Download } from 'lucide-vue-next'
import { BackgroundImageTexture } from '@/registry/default/ui/bg-image-texture'
import type { TextureVariant } from '@/registry/default/ui/bg-image-texture'

const textureVariants: TextureVariant[] = [
  'fabric-of-squares',
  'grid-noise',
  'inflicted',
  'debut-light',
  'groovepaper',
  'none',
]

const textureMap: Record<Exclude<TextureVariant, 'none'>, string> = {
  'fabric-of-squares': '/textures/fabric-of-squares.png',
  'grid-noise': '/textures/grid-noise.png',
  inflicted: '/textures/inflicted.png',
  'debut-light': '/textures/debut-light.png',
  groovepaper: '/textures/groovepaper.png',
}

const selectedVariant = ref<TextureVariant>('fabric-of-squares')
const opacity = ref(0.5)

async function downloadTexture(variant: Exclude<TextureVariant, 'none'>) {
  const url = textureMap[variant]
  try {
    const response = await fetch(url)
    const blob = await response.blob()
    const blobUrl = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = blobUrl
    link.download = `${variant}.png`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(blobUrl)
  } catch {
    const link = document.createElement('a')
    link.href = url
    link.download = `${variant}.png`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }
}
</script>

<template>
  <div class="space-y-8 p-6">
    <div class="rounded-lg border p-6">
      <h3 class="text-lg font-semibold mb-2">Texture Controls</h3>
      <p class="text-sm text-muted-foreground mb-4">Select a texture variant and adjust the opacity</p>
      <div class="space-y-4">
        <div class="flex flex-wrap gap-2">
          <button
            v-for="variant in textureVariants"
            :key="variant"
            class="rounded-md border px-3 py-1 text-sm"
            :class="selectedVariant === variant ? 'bg-primary text-primary-foreground' : ''"
            @click="selectedVariant = variant"
          >
            {{ variant === 'none' ? 'None' : variant }}
          </button>
        </div>
        <div>
          <label class="text-sm font-medium">Opacity: {{ opacity.toFixed(2) }}</label>
          <input type="range" :min="0" :max="1" :step="0.01" v-model.number="opacity" class="w-full" />
        </div>
      </div>
    </div>

    <div class="rounded-lg border p-6">
      <div class="flex items-center justify-between mb-4">
        <div>
          <h3 class="text-lg font-semibold">Preview with Content</h3>
          <p class="text-sm text-muted-foreground">See how the texture looks with content on top</p>
        </div>
        <button
          v-if="selectedVariant !== 'none'"
          class="inline-flex items-center gap-2 rounded-md border px-3 py-1.5 text-sm"
          @click="downloadTexture(selectedVariant as Exclude<TextureVariant, 'none'>)"
        >
          <Download class="h-4 w-4" /> Download Texture
        </button>
      </div>
      <BackgroundImageTexture
        :variant="selectedVariant"
        :opacity="opacity"
        class="rounded-lg border border-border p-8 min-h-[400px]"
      >
        <div class="space-y-6">
          <div>
            <h3 class="text-3xl font-bold text-foreground mb-2">Texture Background</h3>
            <p class="text-muted-foreground text-lg">
              This content sits on top of the texture layer. Adjust the opacity slider to see how the texture affects the background.
            </p>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div class="p-4 rounded-lg bg-card/50 border border-border">
              <h4 class="font-semibold mb-2">Feature 1</h4>
              <p class="text-sm text-muted-foreground">Content with texture background</p>
            </div>
            <div class="p-4 rounded-lg bg-card/50 border border-border">
              <h4 class="font-semibold mb-2">Feature 2</h4>
              <p class="text-sm text-muted-foreground">More content examples</p>
            </div>
          </div>
        </div>
      </BackgroundImageTexture>
    </div>

    <div class="space-y-4">
      <h3 class="text-2xl font-semibold">All Texture Variants</h3>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <div v-for="variant in textureVariants.filter(v => v !== 'none')" :key="variant" class="rounded-lg border p-4">
          <div class="flex items-center justify-between mb-3">
            <h4 class="text-lg capitalize">{{ variant.replace(/-/g, ' ') }}</h4>
            <button class="p-1" :title="`Download ${variant}.png`" @click="downloadTexture(variant as Exclude<TextureVariant, 'none'>)">
              <Download class="h-4 w-4" />
            </button>
          </div>
          <BackgroundImageTexture
            :variant="variant"
            :opacity="0.5"
            class="rounded-lg border border-border p-6 h-48 flex items-center justify-center"
          >
            <div class="text-center">
              <p class="text-sm font-medium text-foreground">{{ variant }}</p>
              <p class="text-xs text-muted-foreground mt-1">Opacity: 0.5</p>
            </div>
          </BackgroundImageTexture>
        </div>
      </div>
    </div>
  </div>
</template>
