// apps/www/components/landing/local-time.tsx
"use client";

import { useEffect, useState } from "react";

export const LocalTime = () => {
  const [timeOfDay, setTimeOfDay] = useState("today");

  useEffect(() => {
    const updateTimeOfDay = () => {
      const hour = new Date().getHours();

      if (hour >= 5 && hour < 12) {
        setTimeOfDay("this morning");
      } else if (hour >= 12 && hour < 17) {
        setTimeOfDay("this afternoon");
      } else if (hour >= 17 && hour < 22) {
        setTimeOfDay("this evening");
      } else {
        setTimeOfDay("today");
      }
    };

    updateTimeOfDay();

    // Update time of day every minute
    const intervalId = setInterval(updateTimeOfDay, 60_000);

    return () => clearInterval(intervalId);
  }, []);

  return <span>{timeOfDay}</span>;
};

// apps/vue/components/landing/LocalTime.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'

const timeOfDay = ref('today')
let intervalId: ReturnType<typeof setInterval> | null = null

function updateTimeOfDay() {
  const hour = new Date().getHours()
  if (hour >= 5 && hour < 12) {
    timeOfDay.value = 'this morning'
  } else if (hour >= 12 && hour < 17) {
    timeOfDay.value = 'this afternoon'
  } else if (hour >= 17 && hour < 22) {
    timeOfDay.value = 'this evening'
  } else {
    timeOfDay.value = 'today'
  }
}

onMounted(() => {
  updateTimeOfDay()
  intervalId = setInterval(updateTimeOfDay, 60_000)
})

onUnmounted(() => {
  if (intervalId) clearInterval(intervalId)
})
</script>

<template>
  <span>{{ timeOfDay }}</span>
</template>
