// apps/www/components/ai-elements/panel.tsx
import { Panel as PanelPrimitive } from "@xyflow/react";
import type { ComponentProps } from "react";

import { cn } from "@/lib/utils";

type PanelProps = ComponentProps<typeof PanelPrimitive>;

export const Panel = ({ className, ...props }: PanelProps) => (
  <PanelPrimitive
    className={cn(
      "bg-card m-4 overflow-hidden rounded-md border p-1",
      className
    )}
    {...props}
  />
);

// apps/vue/components/ai-elements/Panel.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { Panel as PanelPrimitive } from "@vue-flow/core"

defineOptions({ name: "Panel" })

const props = defineProps<{
  class?: string
  position?: InstanceType<typeof PanelPrimitive>["$props"]["position"]
}>()
</script>

<template>
  <PanelPrimitive
    :class="cn('m-4 overflow-hidden rounded-md border bg-card p-1', props.class)"
    :position="props.position"
  >
    <slot />
  </PanelPrimitive>
</template>
