// apps/www/components/ai-elements/persona.tsx
"use client";

import type { RiveParameters } from "@rive-app/react-webgl2";
import {
  useRive,
  useStateMachineInput,
  useViewModel,
  useViewModelInstance,
  useViewModelInstanceColor,
} from "@rive-app/react-webgl2";
import type { FC, ReactNode } from "react";
import { memo, useEffect, useMemo, useRef, useState } from "react";

import { cn } from "@/lib/utils";

export type PersonaState =
  | "idle"
  | "listening"
  | "thinking"
  | "speaking"
  | "asleep";

interface PersonaProps {
  state: PersonaState;
  onLoad?: RiveParameters["onLoad"];
  onLoadError?: RiveParameters["onLoadError"];
  onReady?: () => void;
  onPause?: RiveParameters["onPause"];
  onPlay?: RiveParameters["onPlay"];
  onStop?: RiveParameters["onStop"];
  className?: string;
  variant?: keyof typeof sources;
}

// The state machine name is always 'default' for Elements AI visuals
const stateMachine = "default";

const sources = {
  command: {
    dynamicColor: true,
    hasModel: true,
    source:
      "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/command-2.0.riv",
  },
  glint: {
    dynamicColor: true,
    hasModel: true,
    source:
      "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/glint-2.0.riv",
  },
  halo: {
    dynamicColor: true,
    hasModel: true,
    source:
      "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/halo-2.0.riv",
  },
  mana: {
    dynamicColor: false,
    hasModel: true,
    source:
      "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/mana-2.0.riv",
  },
  obsidian: {
    dynamicColor: true,
    hasModel: true,
    source:
      "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/obsidian-2.0.riv",
  },
  opal: {
    dynamicColor: false,
    hasModel: false,
    source:
      "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/orb-1.2.riv",
  },
};

const getCurrentTheme = (): "light" | "dark" => {
  if (typeof window !== "undefined") {
    if (document.documentElement.classList.contains("dark")) {
      return "dark";
    }
    if (window.matchMedia?.("(prefers-color-scheme: dark)").matches) {
      return "dark";
    }
  }
  return "light";
};

const useTheme = (enabled: boolean) => {
  const [theme, setTheme] = useState<"light" | "dark">(getCurrentTheme);

  useEffect(() => {
    // Skip if not enabled (avoids unnecessary observers for non-dynamic-color variants)
    if (!enabled) {
      return;
    }

    // Watch for classList changes
    const observer = new MutationObserver(() => {
      setTheme(getCurrentTheme());
    });

    observer.observe(document.documentElement, {
      attributeFilter: ["class"],
      attributes: true,
    });

    // Watch for OS-level theme changes
    let mql: MediaQueryList | null = null;
    const handleMediaChange = () => {
      setTheme(getCurrentTheme());
    };

    if (window.matchMedia) {
      mql = window.matchMedia("(prefers-color-scheme: dark)");
      mql.addEventListener("change", handleMediaChange);
    }

    return () => {
      observer.disconnect();
      if (mql) {
        mql.removeEventListener("change", handleMediaChange);
      }
    };
  }, [enabled]);

  return theme;
};

interface PersonaWithModelProps {
  rive: ReturnType<typeof useRive>["rive"];
  source: (typeof sources)[keyof typeof sources];
  children: React.ReactNode;
}

const PersonaWithModel = memo(
  ({ rive, source, children }: PersonaWithModelProps) => {
    const theme = useTheme(source.dynamicColor);
    const viewModel = useViewModel(rive, { useDefault: true });
    const viewModelInstance = useViewModelInstance(viewModel, {
      rive,
      useDefault: true,
    });
    const viewModelInstanceColor = useViewModelInstanceColor(
      "color",
      viewModelInstance
    );

    useEffect(() => {
      if (!(viewModelInstanceColor && source.dynamicColor)) {
        return;
      }

      const [r, g, b] = theme === "dark" ? [255, 255, 255] : [0, 0, 0];
      viewModelInstanceColor.setRgb(r, g, b);
    }, [viewModelInstanceColor, theme, source.dynamicColor]);

    return children;
  }
);

PersonaWithModel.displayName = "PersonaWithModel";

interface PersonaWithoutModelProps {
  children: ReactNode;
}

const PersonaWithoutModel = memo(
  ({ children }: PersonaWithoutModelProps) => children
);

PersonaWithoutModel.displayName = "PersonaWithoutModel";

export const Persona: FC<PersonaProps> = memo(
  ({
    variant = "obsidian",
    state = "idle",
    onLoad,
    onLoadError,
    onReady,
    onPause,
    onPlay,
    onStop,
    className,
  }) => {
    const source = sources[variant];

    if (!source) {
      throw new Error(`Invalid variant: ${variant}`);
    }

    // Stabilize callbacks to prevent useRive from reinitializing
    const callbacksRef = useRef({
      onLoad,
      onLoadError,
      onPause,
      onPlay,
      onReady,
      onStop,
    });

    useEffect(() => {
      callbacksRef.current = {
        onLoad,
        onLoadError,
        onPause,
        onPlay,
        onReady,
        onStop,
      };
    }, [onLoad, onLoadError, onPause, onPlay, onReady, onStop]);

    const stableCallbacks = useMemo(
      () => ({
        onLoad: ((loadedRive) =>
          callbacksRef.current.onLoad?.(
            loadedRive
          )) as RiveParameters["onLoad"],
        onLoadError: ((err) =>
          callbacksRef.current.onLoadError?.(
            err
          )) as RiveParameters["onLoadError"],
        onPause: ((event) =>
          callbacksRef.current.onPause?.(event)) as RiveParameters["onPause"],
        onPlay: ((event) =>
          callbacksRef.current.onPlay?.(event)) as RiveParameters["onPlay"],
        onReady: () => callbacksRef.current.onReady?.(),
        onStop: ((event) =>
          callbacksRef.current.onStop?.(event)) as RiveParameters["onStop"],
      }),
      []
    );

    const { rive, RiveComponent } = useRive({
      autoplay: true,
      onLoad: stableCallbacks.onLoad,
      onLoadError: stableCallbacks.onLoadError,
      onPause: stableCallbacks.onPause,
      onPlay: stableCallbacks.onPlay,
      onRiveReady: stableCallbacks.onReady,
      onStop: stableCallbacks.onStop,
      src: source.source,
      stateMachines: stateMachine,
    });

    const listeningInput = useStateMachineInput(
      rive,
      stateMachine,
      "listening"
    );
    const thinkingInput = useStateMachineInput(rive, stateMachine, "thinking");
    const speakingInput = useStateMachineInput(rive, stateMachine, "speaking");
    const asleepInput = useStateMachineInput(rive, stateMachine, "asleep");

    useEffect(() => {
      if (listeningInput) {
        listeningInput.value = state === "listening";
      }
      if (thinkingInput) {
        thinkingInput.value = state === "thinking";
      }
      if (speakingInput) {
        speakingInput.value = state === "speaking";
      }
      if (asleepInput) {
        asleepInput.value = state === "asleep";
      }
    }, [state, listeningInput, thinkingInput, speakingInput, asleepInput]);

    const Component = source.hasModel ? PersonaWithModel : PersonaWithoutModel;

    return (
      <Component rive={rive} source={source}>
        <RiveComponent className={cn("size-16 shrink-0", className)} />
      </Component>
    );
  }
);

Persona.displayName = "Persona";

// apps/vue/components/ai-elements/Persona.vue
<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted, computed } from "vue"
import { cn } from "@/lib/utils"
import Rive from "@rive-app/canvas"

defineOptions({ name: "Persona" })

export type PersonaState = "idle" | "listening" | "thinking" | "speaking" | "asleep"

type VariantKey = "command" | "glint" | "halo" | "mana" | "obsidian" | "opal"

const props = withDefaults(
  defineProps<{
    state?: PersonaState
    class?: string
    variant?: VariantKey
  }>(),
  {
    state: "idle",
    variant: "obsidian",
  }
)

const emit = defineEmits<{
  load: []
  loadError: [err: unknown]
  ready: []
  pause: []
  play: []
  stop: []
}>()

const stateMachine = "default"

const sources: Record<VariantKey, { source: string; dynamicColor: boolean; hasModel: boolean }> = {
  command: {
    dynamicColor: true,
    hasModel: true,
    source: "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/command-2.0.riv",
  },
  glint: {
    dynamicColor: true,
    hasModel: true,
    source: "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/glint-2.0.riv",
  },
  halo: {
    dynamicColor: true,
    hasModel: true,
    source: "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/halo-2.0.riv",
  },
  mana: {
    dynamicColor: false,
    hasModel: true,
    source: "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/mana-2.0.riv",
  },
  obsidian: {
    dynamicColor: true,
    hasModel: true,
    source: "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/obsidian-2.0.riv",
  },
  opal: {
    dynamicColor: false,
    hasModel: false,
    source: "https://ejiidnob33g9ap1r.public.blob.vercel-storage.com/orb-1.2.riv",
  },
}

const canvasRef = ref<HTMLCanvasElement | null>(null)
let riveInstance: InstanceType<typeof Rive> | null = null

function getCurrentTheme(): "light" | "dark" {
  if (typeof window !== "undefined") {
    if (document.documentElement.classList.contains("dark")) {
      return "dark"
    }
    if (window.matchMedia?.("(prefers-color-scheme: dark)").matches) {
      return "dark"
    }
  }
  return "light"
}

const theme = ref<"light" | "dark">(getCurrentTheme())
let observer: MutationObserver | null = null
let mql: MediaQueryList | null = null

const source = computed(() => sources[props.variant])

function updateStateMachineInputs() {
  if (!riveInstance) return
  const inputs = riveInstance.stateMachineInputs(stateMachine)
  if (!inputs) return

  for (const input of inputs) {
    if (input.name === "listening") {
      input.value = props.state === "listening"
    } else if (input.name === "thinking") {
      input.value = props.state === "thinking"
    } else if (input.name === "speaking") {
      input.value = props.state === "speaking"
    } else if (input.name === "asleep") {
      input.value = props.state === "asleep"
    }
  }
}

function updateDynamicColor() {
  if (!riveInstance || !source.value.dynamicColor || !source.value.hasModel) return

  try {
    const viewModel = riveInstance.viewModelByName?.("default")
    if (!viewModel) return
    const instance = viewModel.defaultInstance?.()
    if (!instance) return
    const colorProp = instance.color?.("color")
    if (!colorProp) return

    const [r, g, b] = theme.value === "dark" ? [255, 255, 255] : [0, 0, 0]
    colorProp.setRgb(r, g, b)
  } catch {
    // View model API may not be available on all Rive versions
  }
}

function initRive() {
  if (!canvasRef.value) return

  riveInstance?.cleanup()
  riveInstance = null

  riveInstance = new Rive({
    src: source.value.source,
    canvas: canvasRef.value,
    autoplay: true,
    stateMachines: stateMachine,
    onLoad: () => {
      riveInstance?.resizeDrawingSurfaceToCanvas()
      updateStateMachineInputs()
      updateDynamicColor()
      emit("load")
    },
    onLoadError: (err) => {
      emit("loadError", err)
    },
    onPlay: () => {
      emit("play")
    },
    onPause: () => {
      emit("pause")
    },
    onStop: () => {
      emit("stop")
    },
  })
}

onMounted(() => {
  initRive()

  // Watch theme changes for dynamic color
  if (source.value.dynamicColor) {
    observer = new MutationObserver(() => {
      theme.value = getCurrentTheme()
    })
    observer.observe(document.documentElement, {
      attributeFilter: ["class"],
      attributes: true,
    })

    if (window.matchMedia) {
      mql = window.matchMedia("(prefers-color-scheme: dark)")
      const handleMediaChange = () => {
        theme.value = getCurrentTheme()
      }
      mql.addEventListener("change", handleMediaChange)
    }
  }
})

onUnmounted(() => {
  riveInstance?.cleanup()
  riveInstance = null
  observer?.disconnect()
  if (mql) {
    mql.removeEventListener("change", () => {})
  }
})

watch(() => props.state, () => {
  updateStateMachineInputs()
})

watch(theme, () => {
  updateDynamicColor()
})

watch(() => props.variant, () => {
  initRive()
})
</script>

<template>
  <canvas
    ref="canvasRef"
    :class="cn('size-16 shrink-0', props.class)"
  />
</template>
