// apps/www/components/ai-elements/toolbar.tsx
import { NodeToolbar, Position } from "@xyflow/react";
import type { ComponentProps } from "react";

import { cn } from "@/lib/utils";

type ToolbarProps = ComponentProps<typeof NodeToolbar>;

export const Toolbar = ({ className, ...props }: ToolbarProps) => (
  <NodeToolbar
    className={cn(
      "bg-background flex items-center gap-1 rounded-sm border p-1.5",
      className
    )}
    position={Position.Bottom}
    {...props}
  />
);

// apps/vue/components/ai-elements/Toolbar.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import { NodeToolbar, Position } from "@vue-flow/core"

defineOptions({ name: "Toolbar" })

const props = defineProps<{
  class?: string
}>()
</script>

<template>
  <NodeToolbar
    :class="cn('flex items-center gap-1 rounded-sm border bg-background p-1.5', props.class)"
    :position="Position.Bottom"
  >
    <slot />
  </NodeToolbar>
</template>
