// apps/www/registry/default/ui/animated-number.tsx
"use client";

import { motion, MotionValue, useSpring, useTransform } from "motion/react";
import { useEffect } from "react";

interface AnimatedNumberProps {
  value: number;
  mass?: number;
  stiffness?: number;
  damping?: number;
  precision?: number;
  format?: (value: number) => string;
  onAnimationStart?: () => void;
  onAnimationComplete?: () => void;
}

export function AnimatedNumber({
  value,
  mass = 0.8,
  stiffness = 75,
  damping = 15,
  precision = 0,
  format = (num) => num.toLocaleString(),
  onAnimationStart,
  onAnimationComplete,
}: AnimatedNumberProps) {
  const spring = useSpring(value, { mass, stiffness, damping });
  const display: MotionValue<string> = useTransform(spring, (current) =>
    format(parseFloat(current.toFixed(precision)))
  );

  useEffect(() => {
    spring.set(value);
    if (onAnimationStart) onAnimationStart();
    const unsubscribe = spring.on("change", () => {
      if (spring.get() === value && onAnimationComplete) onAnimationComplete();
    });
    return () => unsubscribe();
  }, [spring, value, onAnimationStart, onAnimationComplete]);

  return <motion.span>{display}</motion.span>;
}

// apps/vue/components/animate/AnimatedNumber.vue
<script setup lang="ts">
import { ref, watch, onUnmounted, computed } from "vue"
import { useSpring } from "@vueuse/motion"

interface Props {
  value: number
  mass?: number
  stiffness?: number
  damping?: number
  precision?: number
  format?: (value: number) => string
}

const props = withDefaults(defineProps<Props>(), {
  mass: 0.8,
  stiffness: 75,
  damping: 15,
  precision: 0,
  format: (num: number) => num.toLocaleString(),
})

const emit = defineEmits<{
  animationStart: []
  animationComplete: []
}>()

const currentValue = ref(props.value)

const springValues = useSpring(currentValue, {
  mass: props.mass,
  stiffness: props.stiffness,
  damping: props.damping,
})

const displayText = computed(() =>
  props.format(parseFloat(Number(springValues.value).toFixed(props.precision)))
)

watch(
  () => props.value,
  (newVal) => {
    emit("animationStart")
    currentValue.value = newVal
  }
)

watch(springValues, (val) => {
  if (Math.abs(Number(val) - props.value) < 0.01) {
    emit("animationComplete")
  }
})
</script>

<template>
  <span>{{ displayText }}</span>
</template>
