// apps/vue/registry/default/ui/ExpandableScreen.vue
<script setup lang="ts">
import { ref, provide, inject, watch, type InjectionKey, type Ref } from 'vue'
import { X } from 'lucide-vue-next'

// Context type
interface ExpandableScreenContext {
  isExpanded: Ref<boolean>
  expand: () => void
  collapse: () => void
  layoutId: string
  triggerRadius: string
  contentRadius: string
  animationDuration: number
}

const EXPANDABLE_SCREEN_KEY: InjectionKey<ExpandableScreenContext> = Symbol('expandable-screen')

export function useExpandableScreen() {
  const context = inject(EXPANDABLE_SCREEN_KEY)
  if (!context) {
    throw new Error('useExpandableScreen must be used within an ExpandableScreen')
  }
  return context
}

// Root props
interface Props {
  defaultExpanded?: boolean
  layoutId?: string
  triggerRadius?: string
  contentRadius?: string
  animationDuration?: number
  lockScroll?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  defaultExpanded: false,
  layoutId: 'expandable-card',
  triggerRadius: '100px',
  contentRadius: '24px',
  animationDuration: 0.3,
  lockScroll: true,
})

const emit = defineEmits<{
  expandChange: [expanded: boolean]
}>()

const isExpanded = ref(props.defaultExpanded)

function expand() {
  isExpanded.value = true
  emit('expandChange', true)
}

function collapse() {
  isExpanded.value = false
  emit('expandChange', false)
}

watch(isExpanded, (val) => {
  if (props.lockScroll) {
    document.body.style.overflow = val ? 'hidden' : 'unset'
  }
})

provide(EXPANDABLE_SCREEN_KEY, {
  isExpanded,
  expand,
  collapse,
  layoutId: props.layoutId,
  triggerRadius: props.triggerRadius,
  contentRadius: props.contentRadius,
  animationDuration: props.animationDuration,
})
</script>

<template>
  <div>
    <!-- Trigger: shown when not expanded -->
    <Transition name="scale-fade">
      <div
        v-if="!isExpanded"
        class="inline-block relative cursor-pointer"
        @click="expand"
      >
        <slot name="trigger" />
      </div>
    </Transition>

    <!-- Content: shown when expanded -->
    <Transition name="expand">
      <div
        v-if="isExpanded"
        class="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-2"
      >
        <div
          class="relative flex h-full w-full overflow-y-auto transform-gpu will-change-transform"
          :style="{ borderRadius: contentRadius }"
        >
          <div class="relative z-20 w-full">
            <slot name="content" />
          </div>

          <button
            class="absolute right-6 top-6 z-30 flex h-10 w-10 items-center justify-center transition-colors rounded-full text-white bg-transparent hover:bg-white/10"
            aria-label="Close"
            @click="collapse"
          >
            <X class="h-5 w-5" />
          </button>
        </div>
      </div>
    </Transition>

    <!-- Background slot -->
    <slot name="background" :is-expanded="isExpanded" />
  </div>
</template>

<style scoped>
.scale-fade-enter-active,
.scale-fade-leave-active {
  transition: all 0.3s ease;
}
.scale-fade-enter-from {
  opacity: 0;
  transform: scale(0.8);
}
.scale-fade-leave-to {
  opacity: 0;
  transform: scale(0.8);
}

.expand-enter-active {
  transition: all 0.3s ease;
}
.expand-leave-active {
  transition: all 0.3s ease;
}
.expand-enter-from,
.expand-leave-to {
  opacity: 0;
}
</style>

// apps/www/registry/default/ui/expandable-screen.tsx
"use client"

import {
  createContext,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from "react"
import { X } from "lucide-react"
import { AnimatePresence, motion } from "motion/react"

// Context
interface ExpandableScreenContextValue {
  isExpanded: boolean
  expand: () => void
  collapse: () => void
  layoutId: string
  triggerRadius: string
  contentRadius: string
  animationDuration: number
}

const ExpandableScreenContext =
  createContext<ExpandableScreenContextValue | null>(null)

function useExpandableScreen() {
  const context = useContext(ExpandableScreenContext)
  if (!context) {
    throw new Error(
      "useExpandableScreen must be used within an ExpandableScreen"
    )
  }
  return context
}

// Root Component
interface ExpandableScreenProps {
  children: ReactNode
  defaultExpanded?: boolean
  onExpandChange?: (expanded: boolean) => void
  layoutId?: string
  triggerRadius?: string
  contentRadius?: string
  animationDuration?: number
  lockScroll?: boolean
}

export function ExpandableScreen({
  children,
  defaultExpanded = false,
  onExpandChange,
  layoutId = "expandable-card",
  triggerRadius = "100px",
  contentRadius = "24px",
  animationDuration = 0.3,
  lockScroll = true,
}: ExpandableScreenProps) {
  const [isExpanded, setIsExpanded] = useState(defaultExpanded)

  const expand = () => {
    setIsExpanded(true)
    onExpandChange?.(true)
  }

  const collapse = () => {
    setIsExpanded(false)
    onExpandChange?.(false)
  }

  useEffect(() => {
    if (lockScroll) {
      if (isExpanded) {
        document.body.style.overflow = "hidden"
      } else {
        document.body.style.overflow = "unset"
      }
    }
  }, [isExpanded, lockScroll])

  return (
    <ExpandableScreenContext.Provider
      value={{
        isExpanded,
        expand,
        collapse,
        layoutId,
        triggerRadius,
        contentRadius,
        animationDuration,
      }}
    >
      {children}
    </ExpandableScreenContext.Provider>
  )
}

// Trigger Component
interface ExpandableScreenTriggerProps {
  children: ReactNode
  className?: string
}

export function ExpandableScreenTrigger({
  children,
  className = "",
}: ExpandableScreenTriggerProps) {
  const { isExpanded, expand, layoutId, triggerRadius } = useExpandableScreen()

  return (
    <AnimatePresence initial={false}>
      {!isExpanded && (
        <motion.div className={`inline-block relative ${className}`}>
          {/* Background layer with shared layoutId for morphing */}
          <motion.div
            style={{
              borderRadius: triggerRadius,
            }}
            layout
            layoutId={layoutId}
            className="absolute inset-0 transform-gpu will-change-transform"
          />
          {/* Content layer that fades out on expand */}
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ delay: 0.2 }}
            exit={{ opacity: 0, scale: 0.8 }}
            layout={false}
            onClick={expand}
            className="relative cursor-pointer"
          >
            {children}
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

// Content Component
interface ExpandableScreenContentProps {
  children: ReactNode
  className?: string
  showCloseButton?: boolean
  closeButtonClassName?: string
}

export function ExpandableScreenContent({
  children,
  className = "",
  showCloseButton = true,
  closeButtonClassName = "",
}: ExpandableScreenContentProps) {
  const { isExpanded, collapse, layoutId, contentRadius, animationDuration } =
    useExpandableScreen()

  return (
    <AnimatePresence initial={false}>
      {isExpanded && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-2">
          {/* Morphing background with shared layoutId */}
          <motion.div
            layoutId={layoutId}
            transition={{ duration: animationDuration }}
            style={{
              borderRadius: contentRadius,
            }}
            layout
            className={`relative flex h-full w-full overflow-y-auto transform-gpu will-change-transform ${className}`}
          >
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.15, duration: 0.4 }}
              className="relative z-20 w-full"
            >
              {children}
            </motion.div>

            {showCloseButton && (
              <motion.button
                onClick={collapse}
                className={`absolute right-6 top-6 z-30 flex h-10 w-10 items-center justify-center transition-colors rounded-full ${
                  closeButtonClassName ||
                  "text-white bg-transparent hover:bg-white/10"
                }`}
                aria-label="Close"
              >
                <X className="h-5 w-5" />
              </motion.button>
            )}
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}

// Background Component (optional)
interface ExpandableScreenBackgroundProps {
  trigger?: ReactNode
  content?: ReactNode
  className?: string
}

export function ExpandableScreenBackground({
  trigger,
  content,
  className = "",
}: ExpandableScreenBackgroundProps) {
  const { isExpanded } = useExpandableScreen()

  if (isExpanded && content) {
    return <div className={className}>{content}</div>
  }

  if (!isExpanded && trigger) {
    return <div className={className}>{trigger}</div>
  }

  return null
}

export { useExpandableScreen }
