// apps/vue/registry/default/ui/PromptLibrary.vue
<script setup lang="ts">
import {
  ref,
  computed,
  provide,
  inject,
  watch,
  type InjectionKey,
  type Ref,
} from 'vue'
import { cn } from '@/lib/utils'

// ============================================================================
// Types
// ============================================================================

export interface Prompt {
  id: string
  title: string
  description: string
  prompt: string
  category?: string
  isCustom?: boolean
}

export interface PromptLibraryContextValue {
  prompts: Ref<Prompt[]>
  addCustom: (prompt: Omit<Prompt, 'id' | 'isCustom'>) => void
  removeCustom: (id: string) => void
  selectPrompt: (prompt: Prompt) => void
  lastSelectedId: Ref<string | null>
  open: Ref<boolean>
  setOpen: (open: boolean) => void
  createDialogOpen: Ref<boolean>
  setCreateDialogOpen: (open: boolean) => void
}

const PromptLibraryKey: InjectionKey<PromptLibraryContextValue> =
  Symbol('PromptLibrary')

export function usePromptLibrary(): PromptLibraryContextValue {
  const ctx = inject(PromptLibraryKey)
  if (!ctx) {
    throw new Error(
      'usePromptLibrary must be used within a PromptLibrary provider'
    )
  }
  return ctx
}

// ============================================================================
// Props
// ============================================================================

const props = withDefaults(
  defineProps<{
    prompts?: Prompt[]
    open?: boolean
  }>(),
  {
    prompts: undefined,
    open: undefined,
  }
)

const emit = defineEmits<{
  (e: 'promptsChange', prompts: Prompt[]): void
  (e: 'select', prompt: Prompt): void
  (e: 'update:open', open: boolean): void
}>()

// ============================================================================
// State
// ============================================================================

const internalPrompts = ref<Prompt[]>(props.prompts ?? [])
const resolvedPrompts = computed(() => props.prompts ?? internalPrompts.value)

const internalOpen = ref(false)
const resolvedOpen = computed(() =>
  props.open !== undefined ? props.open : internalOpen.value
)

function setOpen(val: boolean) {
  if (props.open !== undefined) {
    emit('update:open', val)
  } else {
    internalOpen.value = val
  }
}

const createDialogOpen = ref(false)
const lastSelectedId = ref<string | null>(null)

async function selectPrompt(prompt: Prompt) {
  lastSelectedId.value = prompt.id

  try {
    await navigator.clipboard.writeText(prompt.prompt)
  } catch (err) {
    console.error('Failed to copy to clipboard:', err)
  }

  setOpen(false)
  emit('select', prompt)
}

function addCustom(prompt: Omit<Prompt, 'id' | 'isCustom'>) {
  const newPrompt: Prompt = {
    ...prompt,
    id: `custom-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
    isCustom: true,
  }

  if (props.prompts) {
    emit('promptsChange', [...props.prompts, newPrompt])
  } else {
    internalPrompts.value = [...internalPrompts.value, newPrompt]
  }
}

function removeCustom(id: string) {
  if (props.prompts) {
    emit(
      'promptsChange',
      props.prompts.filter((p) => p.id !== id)
    )
  } else {
    internalPrompts.value = internalPrompts.value.filter((p) => p.id !== id)
  }
}

function setCreateDialogOpen(val: boolean) {
  createDialogOpen.value = val
}

provide(PromptLibraryKey, {
  prompts: resolvedPrompts as unknown as Ref<Prompt[]>,
  addCustom,
  removeCustom,
  selectPrompt,
  lastSelectedId,
  open: resolvedOpen as unknown as Ref<boolean>,
  setOpen,
  createDialogOpen,
  setCreateDialogOpen,
})
</script>

<template>
  <slot />
</template>

<script lang="ts">
import { defineComponent, h } from 'vue'

// ============================================================================
// PromptLibraryTrigger
// ============================================================================
export const PromptLibraryTrigger = defineComponent({
  name: 'PromptLibraryTrigger',
  props: {
    class: { type: String, default: '' },
    label: { type: String, default: 'Prompts' },
  },
  setup(props, { slots }) {
    const ctx = inject(PromptLibraryKey)!

    return () =>
      h(
        'button',
        {
          class: cn(
            'gap-1.5 inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground h-9 px-3',
            props.class
          ),
          type: 'button',
          onClick: () => ctx.setOpen(!ctx.open.value),
        },
        slots.default?.() ?? props.label
      )
  },
})

// ============================================================================
// PromptLibraryContent
// ============================================================================
export const PromptLibraryContent = defineComponent({
  name: 'PromptLibraryContent',
  props: {
    class: { type: String, default: '' },
  },
  setup(props, { slots }) {
    const ctx = inject(PromptLibraryKey)!

    return () =>
      ctx.open.value
        ? h(
            'div',
            {
              class: cn('w-80 p-0 border rounded-lg bg-popover shadow-md', props.class),
              'data-slot': 'prompt-library-content',
            },
            slots.default?.()
          )
        : null
  },
})

// ============================================================================
// PromptLibrarySearch
// ============================================================================
export const PromptLibrarySearch = defineComponent({
  name: 'PromptLibrarySearch',
  props: {
    placeholder: { type: String, default: 'Search prompts...' },
    class: { type: String, default: '' },
    modelValue: { type: String, default: '' },
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {
    return () =>
      h('input', {
        type: 'text',
        class: cn(
          'flex h-10 w-full rounded-md bg-transparent py-3 px-4 text-sm outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50 border-b',
          props.class
        ),
        placeholder: props.placeholder,
        value: props.modelValue,
        'data-slot': 'prompt-library-search',
        onInput: (e: Event) =>
          emit('update:modelValue', (e.target as HTMLInputElement).value),
      })
  },
})

// ============================================================================
// PromptLibraryList
// ============================================================================
export const PromptLibraryList = defineComponent({
  name: 'PromptLibraryList',
  props: {
    class: { type: String, default: '' },
  },
  setup(props, { slots }) {
    return () =>
      h(
        'div',
        {
          class: cn('max-h-64 overflow-y-auto', props.class),
          'data-slot': 'prompt-library-list',
        },
        slots.default?.()
      )
  },
})

// ============================================================================
// PromptLibraryEmpty
// ============================================================================
export const PromptLibraryEmpty = defineComponent({
  name: 'PromptLibraryEmpty',
  props: {
    class: { type: String, default: '' },
  },
  setup(props, { slots }) {
    return () =>
      h(
        'div',
        {
          class: cn('py-6 text-center text-sm text-muted-foreground', props.class),
          'data-slot': 'prompt-library-empty',
        },
        slots.default?.() ?? 'No prompts found.'
      )
  },
})

// ============================================================================
// PromptLibraryGroup
// ============================================================================
export const PromptLibraryGroup = defineComponent({
  name: 'PromptLibraryGroup',
  props: {
    class: { type: String, default: '' },
    heading: { type: String, default: '' },
  },
  setup(props, { slots }) {
    return () =>
      h('div', { class: cn('overflow-hidden p-1', props.class), 'data-slot': 'prompt-library-group' }, [
        props.heading
          ? h(
              'div',
              {
                class: 'px-2 py-1.5 text-xs font-medium text-muted-foreground',
              },
              props.heading
            )
          : null,
        slots.default?.(),
      ])
  },
})

// ============================================================================
// PromptLibrarySeparator
// ============================================================================
export const PromptLibrarySeparator = defineComponent({
  name: 'PromptLibrarySeparator',
  props: {
    class: { type: String, default: '' },
  },
  setup(props) {
    return () =>
      h('div', {
        class: cn('-mx-1 h-px bg-border', props.class),
        'data-slot': 'prompt-library-separator',
      })
  },
})

// ============================================================================
// PromptLibraryItem
// ============================================================================
export const PromptLibraryItem = defineComponent({
  name: 'PromptLibraryItem',
  props: {
    prompt: { type: Object as () => Prompt, required: true },
    disablePreview: { type: Boolean, default: false },
    class: { type: String, default: '' },
  },
  setup(props, { slots }) {
    const ctx = inject(PromptLibraryKey)!

    return () => {
      const isLastSelected = ctx.lastSelectedId.value === props.prompt.id

      return h(
        'div',
        {
          class: cn(
            'group/prompt-item flex cursor-pointer items-start gap-3 py-2 px-2 rounded-md hover:bg-accent text-sm',
            isLastSelected && 'bg-accent/50',
            props.class
          ),
          'data-slot': 'prompt-library-item',
          'data-state': isLastSelected ? 'selected' : 'idle',
          onClick: () => ctx.selectPrompt(props.prompt),
        },
        [
          h('div', { class: 'flex min-w-0 flex-1 flex-col gap-0.5' }, [
            slots.default?.() ?? [
              h(
                'span',
                {
                  class: 'font-medium text-foreground text-xs',
                  'data-slot': 'prompt-library-item-title',
                },
                props.prompt.title
              ),
              h(
                'span',
                {
                  class: 'line-clamp-2 text-muted-foreground text-xs',
                  'data-slot': 'prompt-library-item-description',
                },
                props.prompt.description
              ),
            ],
          ]),
        ]
      )
    }
  },
})

// ============================================================================
// PromptLibraryItemTitle
// ============================================================================
export const PromptLibraryItemTitle = defineComponent({
  name: 'PromptLibraryItemTitle',
  props: {
    class: { type: String, default: '' },
  },
  setup(props, { slots }) {
    return () =>
      h(
        'span',
        {
          class: cn('font-medium text-foreground text-xs', props.class),
          'data-slot': 'prompt-library-item-title',
        },
        slots.default?.()
      )
  },
})

// ============================================================================
// PromptLibraryItemDescription
// ============================================================================
export const PromptLibraryItemDescription = defineComponent({
  name: 'PromptLibraryItemDescription',
  props: {
    class: { type: String, default: '' },
  },
  setup(props, { slots }) {
    return () =>
      h(
        'span',
        {
          class: cn('line-clamp-2 text-muted-foreground text-xs', props.class),
          'data-slot': 'prompt-library-item-description',
        },
        slots.default?.()
      )
  },
})

// ============================================================================
// PromptLibraryFooter
// ============================================================================
export const PromptLibraryFooter = defineComponent({
  name: 'PromptLibraryFooter',
  props: {
    class: { type: String, default: '' },
  },
  setup(props, { slots }) {
    return () =>
      h(
        'div',
        {
          class: cn('border-t p-1', props.class),
          'data-slot': 'prompt-library-footer',
        },
        slots.default?.()
      )
  },
})

// ============================================================================
// PromptLibraryCreateTrigger
// ============================================================================
export const PromptLibraryCreateTrigger = defineComponent({
  name: 'PromptLibraryCreateTrigger',
  props: {
    label: { type: String, default: 'New Prompt' },
    class: { type: String, default: '' },
  },
  setup(props, { slots }) {
    const ctx = inject(PromptLibraryKey)!

    function handleSelect() {
      ctx.setOpen(false)
      ctx.setCreateDialogOpen(true)
    }

    return () =>
      h(
        'div',
        {
          class: cn(
            'flex cursor-pointer items-center gap-2 text-muted-foreground px-2 py-2 rounded-md hover:bg-accent text-sm',
            props.class
          ),
          'data-slot': 'prompt-library-create-trigger',
          onClick: handleSelect,
        },
        slots.default?.() ?? [h('span', '+'), ` ${props.label}`]
      )
  },
})

// ============================================================================
// PromptLibraryCreateDialog
// ============================================================================
export const PromptLibraryCreateDialog = defineComponent({
  name: 'PromptLibraryCreateDialog',
  props: {
    title: { type: String, default: 'Create Prompt' },
    description: {
      type: String,
      default: 'Create a custom prompt template for quick access.',
    },
  },
  setup(props, { slots }) {
    const ctx = inject(PromptLibraryKey)!
    const formTitle = ref('')
    const formDescription = ref('')
    const formPrompt = ref('')
    const formCategory = ref('')

    function handleSubmit(e: Event) {
      e.preventDefault()
      if (
        !(
          formTitle.value.trim() &&
          formDescription.value.trim() &&
          formPrompt.value.trim()
        )
      ) {
        return
      }

      ctx.addCustom({
        title: formTitle.value.trim(),
        description: formDescription.value.trim(),
        prompt: formPrompt.value.trim(),
        category: formCategory.value.trim() || undefined,
      })

      formTitle.value = ''
      formDescription.value = ''
      formPrompt.value = ''
      formCategory.value = ''
      ctx.setCreateDialogOpen(false)
    }

    function handleClose() {
      formTitle.value = ''
      formDescription.value = ''
      formPrompt.value = ''
      formCategory.value = ''
      ctx.setCreateDialogOpen(false)
    }

    return () =>
      ctx.createDialogOpen.value
        ? h(
            'div',
            {
              class:
                'fixed inset-0 z-50 flex items-center justify-center bg-black/50',
              onClick: (e: MouseEvent) => {
                if (e.target === e.currentTarget) handleClose()
              },
            },
            [
              h(
                'div',
                {
                  class:
                    'bg-background border rounded-lg shadow-lg w-full max-w-md p-6',
                  'data-slot': 'prompt-library-create-dialog',
                },
                [
                  h('div', { class: 'mb-4' }, [
                    h('h2', { class: 'text-lg font-semibold' }, props.title),
                    h(
                      'p',
                      { class: 'text-sm text-muted-foreground' },
                      props.description
                    ),
                  ]),
                  slots.default?.() ??
                    h(
                      'form',
                      { class: 'flex flex-col gap-4', onSubmit: handleSubmit },
                      [
                        h('div', { class: 'flex flex-col gap-2' }, [
                          h(
                            'label',
                            { class: 'font-medium text-xs', for: 'prompt-title' },
                            'Title'
                          ),
                          h('input', {
                            id: 'prompt-title',
                            class:
                              'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring',
                            placeholder: 'e.g., Code Review',
                            required: true,
                            value: formTitle.value,
                            onInput: (e: Event) =>
                              (formTitle.value = (
                                e.target as HTMLInputElement
                              ).value),
                          }),
                        ]),
                        h('div', { class: 'flex flex-col gap-2' }, [
                          h(
                            'label',
                            {
                              class: 'font-medium text-xs',
                              for: 'prompt-description',
                            },
                            'Description'
                          ),
                          h('input', {
                            id: 'prompt-description',
                            class:
                              'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring',
                            placeholder:
                              'e.g., Review code for best practices',
                            required: true,
                            value: formDescription.value,
                            onInput: (e: Event) =>
                              (formDescription.value = (
                                e.target as HTMLInputElement
                              ).value),
                          }),
                        ]),
                        h('div', { class: 'flex flex-col gap-2' }, [
                          h(
                            'label',
                            {
                              class: 'font-medium text-xs',
                              for: 'prompt-content',
                            },
                            'Prompt'
                          ),
                          h('textarea', {
                            id: 'prompt-content',
                            class:
                              'flex min-h-24 w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring resize-none',
                            placeholder: 'Enter the prompt text...',
                            required: true,
                            value: formPrompt.value,
                            onInput: (e: Event) =>
                              (formPrompt.value = (
                                e.target as HTMLTextAreaElement
                              ).value),
                          }),
                        ]),
                        h('div', { class: 'flex flex-col gap-2' }, [
                          h(
                            'label',
                            {
                              class: 'font-medium text-xs',
                              for: 'prompt-category',
                            },
                            'Category (optional)'
                          ),
                          h('input', {
                            id: 'prompt-category',
                            class:
                              'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring',
                            placeholder: 'e.g., Development',
                            value: formCategory.value,
                            onInput: (e: Event) =>
                              (formCategory.value = (
                                e.target as HTMLInputElement
                              ).value),
                          }),
                        ]),
                        h(
                          'div',
                          { class: 'flex justify-end gap-2 pt-2' },
                          [
                            h(
                              'button',
                              {
                                type: 'button',
                                class:
                                  'inline-flex items-center justify-center rounded-md text-sm font-medium border border-input bg-background hover:bg-accent hover:text-accent-foreground h-9 px-4',
                                onClick: handleClose,
                              },
                              'Cancel'
                            ),
                            h(
                              'button',
                              {
                                type: 'submit',
                                class:
                                  'inline-flex items-center justify-center rounded-md text-sm font-medium bg-primary text-primary-foreground hover:bg-primary/90 h-9 px-4',
                              },
                              'Create'
                            ),
                          ]
                        ),
                      ]
                    ),
                ]
              ),
            ]
          )
        : null
  },
})
</script>

// apps/www/registry/default/ui/prompt-library.tsx
"use client"

import {
  createContext,
  useCallback,
  useContext,
  useMemo,
  useState,
  type ComponentProps,
  type PropsWithChildren,
  type ReactNode,
} from "react"
import { LibraryIcon, PlusSignIcon } from "@hugeicons/core-free-icons"
import { HugeiconsIcon } from "@hugeicons/react"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
  CommandSeparator,
} from "@/components/ui/command"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  type DialogDescriptionProps,
  type DialogTitleProps,
} from "@/components/ui/dialog"
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card"
import { Input } from "@/components/ui/input"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"
import { Textarea } from "@/components/ui/textarea"

// ============================================================================
// Types
// ============================================================================

export interface Prompt {
  /** Unique identifier for the prompt */
  id: string
  /** Display title for the prompt */
  title: string
  /** Short description shown in the list */
  description: string
  /** The actual prompt content to insert/copy */
  prompt: string
  /** Optional category for grouping */
  category?: string
  /** Whether this is a user-created prompt */
  isCustom?: boolean
}

export interface PromptLibraryContextValue {
  /** All available prompts */
  prompts: Prompt[]
  /** Add a custom prompt */
  addCustom: (prompt: Omit<Prompt, "id" | "isCustom">) => void
  /** Remove a custom prompt */
  removeCustom: (id: string) => void
  /** Select a prompt (insert or copy) */
  selectPrompt: (prompt: Prompt) => void
  /** Last selected prompt ID */
  lastSelectedId: string | null
  /** Open state for the popover */
  open: boolean
  /** Set open state for the popover */
  setOpen: (open: boolean) => void
  /** Open state for the create dialog */
  createDialogOpen: boolean
  /** Set open state for the create dialog */
  setCreateDialogOpen: (open: boolean) => void
}

// ============================================================================
// Context
// ============================================================================

const PromptLibraryContext = createContext<PromptLibraryContextValue | null>(
  null
)

/**
 * Hook to access the PromptLibrary context
 * @throws Error if used outside of PromptLibrary provider
 */
export const usePromptLibrary = () => {
  const ctx = useContext(PromptLibraryContext)
  if (!ctx) {
    throw new Error(
      "usePromptLibrary must be used within a PromptLibrary provider"
    )
  }
  return ctx
}

// ============================================================================
// Controllable State Hook
// ============================================================================

function useControllableState<T>(
  controlledValue: T | undefined,
  defaultValue: T,
  onChange?: (value: T) => void
): [T, (value: T | ((prev: T) => T)) => void] {
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue)
  const isControlled = controlledValue !== undefined
  const value = isControlled ? controlledValue : uncontrolledValue

  const setValue = useCallback(
    (nextValue: T | ((prev: T) => T)) => {
      const resolvedValue =
        typeof nextValue === "function"
          ? (nextValue as (prev: T) => T)(value)
          : nextValue

      if (!isControlled) {
        setUncontrolledValue(resolvedValue)
      }
      onChange?.(resolvedValue)
    },
    [isControlled, onChange, value]
  )

  return [value, setValue]
}

// ============================================================================
// Root Component
// ============================================================================

export type PromptLibraryProps = PropsWithChildren<{
  /** Initial set of prompts */
  prompts?: Prompt[]
  /** Callback when prompts change (for custom prompts) */
  onPromptsChange?: (prompts: Prompt[]) => void
  /** Callback when a prompt is selected */
  onSelect?: (prompt: Prompt) => void
  /**
   * Inserts the selected prompt into your input instead of copying it to the
   * clipboard, e.g. AI Elements' `controller.textInput.setInput`.
   */
  onInsert?: (text: string) => void
  /** Controlled open state for popover */
  open?: boolean
  /** Callback when open state changes */
  onOpenChange?: (open: boolean) => void
}>

/**
 * Root component for the PromptLibrary widget.
 * Provides context for all child components.
 */
export function PromptLibrary({
  prompts: controlledPrompts,
  onPromptsChange,
  onSelect,
  onInsert,
  open: controlledOpen,
  onOpenChange,
  children,
}: PromptLibraryProps) {
  const [internalPrompts, setInternalPrompts] = useState<Prompt[]>(
    controlledPrompts ?? []
  )

  const prompts = controlledPrompts ?? internalPrompts

  const [open, setOpen] = useControllableState(
    controlledOpen,
    false,
    onOpenChange
  )
  const [createDialogOpen, setCreateDialogOpen] = useState(false)
  const [lastSelectedId, setLastSelectedId] = useState<string | null>(null)

  const selectPrompt = useCallback(
    async (prompt: Prompt) => {
      setLastSelectedId(prompt.id)

      if (onInsert) {
        onInsert(prompt.prompt)
      } else {
        try {
          await navigator.clipboard.writeText(prompt.prompt)
        } catch (err) {
          console.error("Failed to copy to clipboard:", err)
        }
      }

      // Close popover after selection
      setOpen(false)

      // Call onSelect callback
      onSelect?.(prompt)
    },
    [onInsert, setOpen, onSelect]
  )

  const addCustom = useCallback(
    (prompt: Omit<Prompt, "id" | "isCustom">) => {
      const newPrompt: Prompt = {
        ...prompt,
        id: `custom-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`,
        isCustom: true,
      }

      if (controlledPrompts) {
        onPromptsChange?.([...controlledPrompts, newPrompt])
      } else {
        setInternalPrompts((prev) => [...prev, newPrompt])
      }
    },
    [controlledPrompts, onPromptsChange]
  )

  const removeCustom = useCallback(
    (id: string) => {
      if (controlledPrompts) {
        onPromptsChange?.(controlledPrompts.filter((p) => p.id !== id))
      } else {
        setInternalPrompts((prev) => prev.filter((p) => p.id !== id))
      }
    },
    [controlledPrompts, onPromptsChange]
  )

  const contextValue = useMemo<PromptLibraryContextValue>(
    () => ({
      prompts,
      addCustom,
      removeCustom,
      selectPrompt,
      lastSelectedId,
      open,
      setOpen,
      createDialogOpen,
      setCreateDialogOpen,
    }),
    [
      prompts,
      addCustom,
      removeCustom,
      selectPrompt,
      lastSelectedId,
      open,
      setOpen,
      createDialogOpen,
    ]
  )

  return (
    <PromptLibraryContext.Provider value={contextValue}>
      <Popover onOpenChange={setOpen} open={open}>
        {children}
      </Popover>
    </PromptLibraryContext.Provider>
  )
}

// ============================================================================
// Trigger Component
// ============================================================================

export type PromptLibraryTriggerProps = ComponentProps<typeof Button> & {
  /** Custom label for the trigger button */
  label?: ReactNode
}

/**
 * Button that opens the prompt library popover.
 */
export function PromptLibraryTrigger({
  className,
  label,
  children,
  ...props
}: PromptLibraryTriggerProps) {
  return (
    <PopoverTrigger asChild>
      <Button
        className={cn("gap-1.5", className)}
        size="sm"
        type="button"
        variant="ghost"
        {...props}
      >
        {children ?? (
          <>
            <HugeiconsIcon
              className="size-3.5"
              icon={LibraryIcon}
              strokeWidth={2}
            />
            {label ?? "Prompts"}
          </>
        )}
      </Button>
    </PopoverTrigger>
  )
}

// ============================================================================
// Content Component
// ============================================================================

export type PromptLibraryContentProps = ComponentProps<typeof PopoverContent>

/**
 * Popover content container for the prompt library list.
 */
export function PromptLibraryContent({
  className,
  children,
  ...props
}: PromptLibraryContentProps) {
  return (
    <PopoverContent
      align="start"
      className={cn("w-80 p-0", className)}
      side="top"
      sideOffset={8}
      {...props}
    >
      <Command className="rounded-lg" data-slot="prompt-library-content">
        {children}
      </Command>
    </PopoverContent>
  )
}

// ============================================================================
// Search Component
// ============================================================================

export type PromptLibrarySearchProps = ComponentProps<typeof CommandInput>

/**
 * Search input for filtering prompts.
 */
export function PromptLibrarySearch({
  placeholder = "Search prompts...",
  className,
  ...props
}: PromptLibrarySearchProps) {
  return (
    <CommandInput
      className={cn(className)}
      data-slot="prompt-library-search"
      placeholder={placeholder}
      {...props}
    />
  )
}

// ============================================================================
// List Component
// ============================================================================

export type PromptLibraryListProps = ComponentProps<typeof CommandList>

/**
 * Scrollable list container for prompts.
 */
export function PromptLibraryList({
  className,
  children,
  ...props
}: PromptLibraryListProps) {
  return (
    <CommandList
      className={cn("max-h-64", className)}
      data-slot="prompt-library-list"
      {...props}
    >
      {children}
    </CommandList>
  )
}

// ============================================================================
// Empty Component
// ============================================================================

export type PromptLibraryEmptyProps = ComponentProps<typeof CommandEmpty>

/**
 * Empty state shown when no prompts match the search.
 */
export function PromptLibraryEmpty({
  children = "No prompts found.",
  className,
  ...props
}: PromptLibraryEmptyProps) {
  return (
    <CommandEmpty
      className={cn(className)}
      data-slot="prompt-library-empty"
      {...props}
    >
      {children}
    </CommandEmpty>
  )
}

// ============================================================================
// Group Component
// ============================================================================

export type PromptLibraryGroupProps = ComponentProps<typeof CommandGroup>

/**
 * Group container for categorizing prompts.
 */
export function PromptLibraryGroup({
  className,
  ...props
}: PromptLibraryGroupProps) {
  return (
    <CommandGroup
      className={cn(
        // Remove default rounding from all items
        "**:[[cmdk-item]]:rounded-none",
        // First child in group gets rounded top
        "[&_[cmdk-group-items]>:first-child_[cmdk-item]]:rounded-t-md",
        // Last child in group gets rounded bottom
        "[&_[cmdk-group-items]>:last-child_[cmdk-item]]:rounded-b-md",
        className
      )}
      data-slot="prompt-library-group"
      {...props}
    />
  )
}

// ============================================================================
// Separator Component
// ============================================================================

export type PromptLibrarySeparatorProps = ComponentProps<
  typeof CommandSeparator
>

/**
 * Visual separator between prompt groups.
 */
export function PromptLibrarySeparator({
  className,
  ...props
}: PromptLibrarySeparatorProps) {
  return (
    <CommandSeparator
      className={cn(className)}
      data-slot="prompt-library-separator"
      {...props}
    />
  )
}

// ============================================================================
// Item Component
// ============================================================================

export type PromptLibraryItemProps = Omit<
  ComponentProps<typeof CommandItem>,
  "value" | "onSelect"
> & {
  /** The prompt data */
  prompt: Prompt
  /** Disable hover card preview */
  disablePreview?: boolean
}

/**
 * Individual prompt item with click-to-select and optional hover preview.
 */
export function PromptLibraryItem({
  prompt,
  disablePreview = false,
  className,
  children,
  ...props
}: PromptLibraryItemProps) {
  const { selectPrompt, lastSelectedId } = usePromptLibrary()
  const isLastSelected = lastSelectedId === prompt.id

  const handleSelect = () => {
    selectPrompt(prompt)
  }

  const itemContent = (
    <CommandItem
      className={cn(
        "group/prompt-item flex cursor-pointer items-start gap-3 py-2",
        isLastSelected && "bg-accent/50",
        className
      )}
      data-slot="prompt-library-item"
      data-state={isLastSelected ? "selected" : "idle"}
      onSelect={handleSelect}
      value={prompt.title}
      {...props}
    >
      <div className="flex min-w-0 flex-1 flex-col gap-0.5">
        {children ?? (
          <>
            <PromptLibraryItemTitle>{prompt.title}</PromptLibraryItemTitle>
            <PromptLibraryItemDescription>
              {prompt.description}
            </PromptLibraryItemDescription>
          </>
        )}
      </div>
    </CommandItem>
  )

  if (disablePreview || !prompt.prompt) {
    return itemContent
  }

  return (
    <PromptLibraryHoverCard prompt={prompt}>
      {itemContent}
    </PromptLibraryHoverCard>
  )
}

// ============================================================================
// Item Title Component
// ============================================================================

export type PromptLibraryItemTitleProps = ComponentProps<"span">

/**
 * Title text for a prompt item.
 */
export function PromptLibraryItemTitle({
  className,
  ...props
}: PromptLibraryItemTitleProps) {
  return (
    <span
      className={cn("text-foreground text-xs font-medium", className)}
      data-slot="prompt-library-item-title"
      {...props}
    />
  )
}

// ============================================================================
// Item Description Component
// ============================================================================

export type PromptLibraryItemDescriptionProps = ComponentProps<"span">

/**
 * Description text for a prompt item.
 */
export function PromptLibraryItemDescription({
  className,
  ...props
}: PromptLibraryItemDescriptionProps) {
  return (
    <span
      className={cn("text-muted-foreground line-clamp-2 text-xs", className)}
      data-slot="prompt-library-item-description"
      {...props}
    />
  )
}

// ============================================================================
// Hover Card Component
// ============================================================================

export interface PromptLibraryHoverCardProps {
  /** The prompt to preview */
  prompt: Prompt
  /** The trigger element (prompt item) */
  children: ReactNode
}

/**
 * Hover card that shows the full prompt content on hover.
 */
export function PromptLibraryHoverCard({
  prompt,
  children,
}: PromptLibraryHoverCardProps) {
  return (
    <HoverCard openDelay={300} closeDelay={100}>
      <HoverCardTrigger>{children}</HoverCardTrigger>
      <HoverCardContent
        align="start"
        className="w-80"
        data-slot="prompt-library-hover-card"
        side="right"
        sideOffset={8}
      >
        <div className="flex flex-col gap-2">
          <div className="flex flex-col gap-1">
            <span className="text-sm font-medium">{prompt.title}</span>
            <span className="text-muted-foreground text-xs">
              {prompt.description}
            </span>
          </div>
          {prompt.prompt && (
            <div className="bg-muted/50 rounded-md p-2">
              <p className="text-muted-foreground line-clamp-6 text-xs whitespace-pre-wrap">
                {prompt.prompt}
              </p>
            </div>
          )}
          {prompt.category && (
            <span className="text-muted-foreground text-[0.625rem]">
              Category: {prompt.category}
            </span>
          )}
          {prompt.isCustom && (
            <span className="text-muted-foreground text-[0.625rem]">
              Custom prompt
            </span>
          )}
        </div>
      </HoverCardContent>
    </HoverCard>
  )
}

// ============================================================================
// Footer Component
// ============================================================================

export type PromptLibraryFooterProps = ComponentProps<"div">

/**
 * Footer container that stays fixed at the bottom of the popover.
 * Use this to place the create trigger outside the scrollable list.
 */
export function PromptLibraryFooter({
  className,
  children,
  ...props
}: PromptLibraryFooterProps) {
  return (
    <div
      className={cn("border-t p-1", className)}
      data-slot="prompt-library-footer"
      {...props}
    >
      {children}
    </div>
  )
}

// ============================================================================
// Create Trigger Component
// ============================================================================

export type PromptLibraryCreateTriggerProps = Omit<
  ComponentProps<typeof CommandItem>,
  "onSelect"
> & {
  /** Custom label for the create button */
  label?: ReactNode
}

/**
 * Button that opens the create prompt dialog.
 */
export function PromptLibraryCreateTrigger({
  label = "New Prompt",
  className,
  children,
  ...props
}: PromptLibraryCreateTriggerProps) {
  const { setCreateDialogOpen, setOpen } = usePromptLibrary()

  const handleSelect = () => {
    setOpen(false)
    setCreateDialogOpen(true)
  }

  return (
    <CommandItem
      className={cn(
        "text-muted-foreground flex cursor-pointer items-center gap-2",
        className
      )}
      data-slot="prompt-library-create-trigger"
      onSelect={handleSelect}
      value="__new_prompt__"
      {...props}
    >
      {children ?? (
        <>
          <HugeiconsIcon
            className="size-3.5"
            icon={PlusSignIcon}
            strokeWidth={2}
          />
          {label}
        </>
      )}
    </CommandItem>
  )
}

// ============================================================================
// Create Dialog Component
// ============================================================================

export type PromptLibraryCreateDialogProps = Omit<
  ComponentProps<typeof Dialog>,
  "open" | "onOpenChange" | "children"
> & {
  /** Dialog title */
  title?: DialogTitleProps["children"]
  /** Dialog description */
  description?: DialogDescriptionProps["children"]
  /** Custom form content to replace the default form */
  children?: ReactNode
}

/**
 * Modal dialog for creating custom prompts.
 */
export function PromptLibraryCreateDialog({
  title = "Create Prompt",
  description = "Create a custom prompt template for quick access.",
  children,
  ...props
}: PromptLibraryCreateDialogProps) {
  const { createDialogOpen, setCreateDialogOpen, addCustom } =
    usePromptLibrary()
  const [formTitle, setFormTitle] = useState("")
  const [formDescription, setFormDescription] = useState("")
  const [formPrompt, setFormPrompt] = useState("")
  const [formCategory, setFormCategory] = useState("")

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()

    if (!(formTitle.trim() && formDescription.trim() && formPrompt.trim())) {
      return
    }

    addCustom({
      title: formTitle.trim(),
      description: formDescription.trim(),
      prompt: formPrompt.trim(),
      category: formCategory.trim() || undefined,
    })

    // Reset form
    setFormTitle("")
    setFormDescription("")
    setFormPrompt("")
    setFormCategory("")
    setCreateDialogOpen(false)
  }

  const handleOpenChange = (open: boolean) => {
    setCreateDialogOpen(open)
    if (!open) {
      // Reset form when closing
      setFormTitle("")
      setFormDescription("")
      setFormPrompt("")
      setFormCategory("")
    }
  }

  return (
    <Dialog
      data-slot="prompt-library-create-dialog"
      onOpenChange={handleOpenChange}
      open={createDialogOpen}
      {...props}
    >
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
          <DialogDescription>{description}</DialogDescription>
        </DialogHeader>
        {children ?? (
          <form className="flex flex-col gap-4" onSubmit={handleSubmit}>
            <div className="flex flex-col gap-2">
              <label className="text-xs font-medium" htmlFor="prompt-title">
                Title
              </label>
              <Input
                id="prompt-title"
                onChange={(e) => setFormTitle(e.target.value)}
                placeholder="e.g., Code Review"
                required
                value={formTitle}
              />
            </div>
            <div className="flex flex-col gap-2">
              <label
                className="text-xs font-medium"
                htmlFor="prompt-description"
              >
                Description
              </label>
              <Input
                id="prompt-description"
                onChange={(e) => setFormDescription(e.target.value)}
                placeholder="e.g., Review code for best practices"
                required
                value={formDescription}
              />
            </div>
            <div className="flex flex-col gap-2">
              <label className="text-xs font-medium" htmlFor="prompt-content">
                Prompt
              </label>
              <Textarea
                className="min-h-24 resize-none"
                id="prompt-content"
                onChange={(e) => setFormPrompt(e.target.value)}
                placeholder="Enter the prompt text..."
                required
                value={formPrompt}
              />
            </div>
            <div className="flex flex-col gap-2">
              <label className="text-xs font-medium" htmlFor="prompt-category">
                Category (optional)
              </label>
              <Input
                id="prompt-category"
                onChange={(e) => setFormCategory(e.target.value)}
                placeholder="e.g., Development"
                value={formCategory}
              />
            </div>
            <DialogFooter>
              <DialogClose asChild>
                <Button type="button" variant="outline">
                  Cancel
                </Button>
              </DialogClose>
              <Button type="submit">Create</Button>
            </DialogFooter>
          </form>
        )}
      </DialogContent>
    </Dialog>
  )
}

// ============================================================================
// Compound Export
// ============================================================================

export const PromptLibraryWidget = Object.assign(PromptLibrary, {
  Trigger: PromptLibraryTrigger,
  Content: PromptLibraryContent,
  Search: PromptLibrarySearch,
  List: PromptLibraryList,
  Empty: PromptLibraryEmpty,
  Group: PromptLibraryGroup,
  Separator: PromptLibrarySeparator,
  Item: PromptLibraryItem,
  ItemTitle: PromptLibraryItemTitle,
  ItemDescription: PromptLibraryItemDescription,
  HoverCard: PromptLibraryHoverCard,
  Footer: PromptLibraryFooter,
  CreateTrigger: PromptLibraryCreateTrigger,
  CreateDialog: PromptLibraryCreateDialog,
})
