// apps/vue/registry/default/ui/VoteTally.vue
<script setup lang="ts">
import { ref, computed, provide, inject, type InjectionKey } from 'vue'

// ---- Types ----

export type VoteTallyValue = Record<string, number>

// ---- Context ----

interface VoteTallyContextValue {
  votes: () => VoteTallyValue
  votedItems: () => Set<string>
  disabled: () => boolean
  vote: (itemId: string) => void
  unvote: (itemId: string) => void
  toggleVote: (itemId: string) => void
  getVoteCount: (itemId: string) => number
  hasVoted: (itemId: string) => boolean
}

interface VoteTallyItemContextValue {
  itemId: string
  disabled: () => boolean
}

const VoteTallyKey: InjectionKey<VoteTallyContextValue> = Symbol('VoteTally')
const VoteTallyItemKey: InjectionKey<VoteTallyItemContextValue> = Symbol('VoteTallyItem')

// This file exports sub-components; see below.
// Usage in parent: <VoteTallyRoot>, <VoteTallyItem>, etc.

defineOptions({ name: 'VoteTally' })
</script>

<script lang="ts">
import { defineComponent, h, type PropType } from 'vue'

// ---- Root ----
export const VoteTallyRoot = defineComponent({
  name: 'VoteTallyRoot',
  props: {
    modelValue: { type: Object as PropType<VoteTallyValue>, default: undefined },
    defaultValue: { type: Object as PropType<VoteTallyValue>, default: () => ({}) },
    votedItems: { type: Object as PropType<Set<string>>, default: undefined },
    defaultVotedItems: { type: Object as PropType<Set<string>>, default: () => new Set<string>() },
    disabled: { type: Boolean, default: false },
  },
  emits: ['update:modelValue', 'update:votedItems'],
  setup(props, { slots, emit }) {
    const internalVotes = ref<VoteTallyValue>({ ...props.defaultValue })
    const internalVotedItems = ref<Set<string>>(new Set(props.defaultVotedItems))

    const votes = computed(() => props.modelValue !== undefined ? props.modelValue : internalVotes.value)
    const votedItemsSet = computed(() => props.votedItems !== undefined ? props.votedItems : internalVotedItems.value)

    function setVotes(updater: (prev: VoteTallyValue) => VoteTallyValue) {
      const newVal = updater(votes.value)
      if (props.modelValue !== undefined) {
        emit('update:modelValue', newVal)
      } else {
        internalVotes.value = newVal
      }
    }

    function setVotedItems(updater: (prev: Set<string>) => Set<string>) {
      const newVal = updater(votedItemsSet.value)
      if (props.votedItems !== undefined) {
        emit('update:votedItems', newVal)
      } else {
        internalVotedItems.value = newVal
      }
    }

    function vote(itemId: string) {
      if (props.disabled || votedItemsSet.value.has(itemId)) return
      setVotes((prev) => ({ ...prev, [itemId]: (prev[itemId] ?? 0) + 1 }))
      setVotedItems((prev) => new Set([...prev, itemId]))
    }

    function unvote(itemId: string) {
      if (props.disabled || !votedItemsSet.value.has(itemId)) return
      setVotes((prev) => ({ ...prev, [itemId]: Math.max((prev[itemId] ?? 0) - 1, 0) }))
      setVotedItems((prev) => { const s = new Set(prev); s.delete(itemId); return s })
    }

    function toggleVote(itemId: string) {
      votedItemsSet.value.has(itemId) ? unvote(itemId) : vote(itemId)
    }

    function getVoteCount(itemId: string) {
      return votes.value[itemId] ?? 0
    }

    function hasVoted(itemId: string) {
      return votedItemsSet.value.has(itemId)
    }

    const ctx: VoteTallyContextValue = {
      votes: () => votes.value,
      votedItems: () => votedItemsSet.value,
      disabled: () => props.disabled,
      vote,
      unvote,
      toggleVote,
      getVoteCount,
      hasVoted,
    }

    provide(Symbol.for('VoteTally'), ctx)

    return () =>
      h('ul', { 'aria-label': 'Vote tally list', 'data-disabled': props.disabled || undefined }, slots.default?.())
  },
})

// ---- Item ----
export const VoteTallyItem = defineComponent({
  name: 'VoteTallyItem',
  props: {
    value: { type: String, required: true },
    disabled: { type: Boolean, default: false },
  },
  setup(props, { slots }) {
    const ctx = inject<VoteTallyContextValue>(Symbol.for('VoteTally'))!
    const disabled = computed(() => ctx.disabled() || props.disabled)
    const voted = computed(() => ctx.hasVoted(props.value))
    const voteCount = computed(() => ctx.getVoteCount(props.value))

    const itemCtx: VoteTallyItemContextValue = {
      itemId: props.value,
      disabled: () => disabled.value,
    }

    provide(Symbol.for('VoteTallyItem'), itemCtx)

    return () =>
      h('li', {
        'data-disabled': disabled.value || undefined,
        'data-item': props.value,
        'data-slot': 'vote-tally-item',
        'data-vote-count': voteCount.value,
        'data-voted': voted.value || undefined,
      }, slots.default?.())
  },
})

// ---- Group ----
export const VoteTallyGroup = defineComponent({
  name: 'VoteTallyGroup',
  props: {
    sortBy: { type: String as PropType<'votes-asc' | 'votes-desc' | 'none'>, default: 'none' },
  },
  setup(props, { slots }) {
    const ctx = inject<VoteTallyContextValue>(Symbol.for('VoteTally'))!

    return () => {
      const children = slots.default?.() || []

      if (props.sortBy === 'none') {
        return h('div', {}, children)
      }

      const sorted = [...children].sort((a, b) => {
        const aValue = (a.props as any)?.value as string
        const bValue = (b.props as any)?.value as string
        const aVotes = ctx.getVoteCount(aValue)
        const bVotes = ctx.getVoteCount(bValue)
        return props.sortBy === 'votes-desc' ? bVotes - aVotes : aVotes - bVotes
      })

      return h('div', {}, sorted)
    }
  },
})

// ---- Trigger ----
export const VoteTallyTrigger = defineComponent({
  name: 'VoteTallyTrigger',
  setup(_, { slots, attrs }) {
    const ctx = inject<VoteTallyContextValue>(Symbol.for('VoteTally'))!
    const itemCtx = inject<VoteTallyItemContextValue>(Symbol.for('VoteTallyItem'))!

    const voted = computed(() => ctx.hasVoted(itemCtx.itemId))
    const disabled = computed(() => ctx.disabled() || itemCtx.disabled())

    function handleClick(event: MouseEvent) {
      if (event.defaultPrevented || disabled.value) return
      ctx.toggleVote(itemCtx.itemId)
    }

    return () =>
      h('button', {
        ...attrs,
        'aria-label': voted.value ? 'Remove vote' : 'Vote',
        'aria-pressed': voted.value,
        'data-slot': 'vote-tally-trigger',
        'data-state': voted.value ? 'voted' : 'idle',
        disabled: disabled.value,
        onClick: handleClick,
        type: 'button',
      }, slots.default?.())
  },
})

// ---- Count ----
export const VoteTallyCount = defineComponent({
  name: 'VoteTallyCount',
  setup(_, { slots, attrs }) {
    const ctx = inject<VoteTallyContextValue>(Symbol.for('VoteTally'))!
    const itemCtx = inject<VoteTallyItemContextValue>(Symbol.for('VoteTallyItem'))!

    const count = computed(() => ctx.getVoteCount(itemCtx.itemId))

    return () =>
      h('span', { ...attrs, 'data-slot': 'vote-tally-count' }, slots.default?.() ?? count.value)
  },
})

// ---- Title ----
export const VoteTallyTitle = defineComponent({
  name: 'VoteTallyTitle',
  setup(_, { slots, attrs }) {
    return () =>
      h('span', { ...attrs, 'data-slot': 'vote-tally-title' }, slots.default?.())
  },
})

// ---- Description ----
export const VoteTallyDescription = defineComponent({
  name: 'VoteTallyDescription',
  setup(_, { slots, attrs }) {
    return () =>
      h('span', { ...attrs, 'data-slot': 'vote-tally-description' }, slots.default?.())
  },
})

// ---- Composable for external access ----
export function useVoteTally() {
  const ctx = inject<VoteTallyContextValue>(Symbol.for('VoteTally'))
  if (!ctx) {
    throw new Error('useVoteTally must be used within VoteTallyRoot')
  }
  return ctx
}

// ---- Compound export ----
export const VoteTally = {
  Root: VoteTallyRoot,
  Group: VoteTallyGroup,
  Item: VoteTallyItem,
  Trigger: VoteTallyTrigger,
  Count: VoteTallyCount,
  Title: VoteTallyTitle,
  Description: VoteTallyDescription,
}
</script>

<template>
  <!-- This file exports renderless components. Import them from this module. -->
  <slot />
</template>

// apps/www/registry/default/ui/vote-tally.tsx
"use client";

import { useControllableState } from "@radix-ui/react-use-controllable-state";
import {
  Children,
  createContext,
  isValidElement,
  useCallback,
  useContext,
  useMemo,
  type ComponentProps,
  type MouseEvent,
} from "react";

/* -----------------------------------------------------------------------------
 * Types
 * -------------------------------------------------------------------------- */

export type VoteTallyValue = Record<string, number>;

export interface VoteTallyRootProps extends Omit<
  ComponentProps<"ul">,
  "defaultValue"
> {
  /** Current vote counts (controlled) */
  value?: VoteTallyValue;
  /** Initial vote counts (uncontrolled) */
  defaultValue?: VoteTallyValue;
  /** Callback when votes change */
  onValueChange?: (value: VoteTallyValue) => void;
  /** Set of item IDs the current user has voted for */
  votedItems?: Set<string>;
  /** Default voted items (uncontrolled) */
  defaultVotedItems?: Set<string>;
  /** Callback when user votes/unvotes */
  onVotedItemsChange?: (votedItems: Set<string>) => void;
  /** Whether voting is disabled */
  disabled?: boolean;
}

export interface VoteTallyItemProps extends ComponentProps<"li"> {
  /** Unique identifier for this item */
  value: string;
  /** Whether this specific item is disabled */
  disabled?: boolean;
}

export type VoteTallyTriggerProps = ComponentProps<"button">;

export type VoteTallyCountProps = ComponentProps<"span">;

export type VoteTallyTitleProps = ComponentProps<"span">;

export type VoteTallyDescriptionProps = ComponentProps<"span">;

export interface VoteTallyGroupProps extends ComponentProps<"div"> {
  /** Sort items by vote count */
  sortBy?: "votes-asc" | "votes-desc" | "none";
}

/* -----------------------------------------------------------------------------
 * Context
 * -------------------------------------------------------------------------- */

interface VoteTallyContextValue {
  votes: VoteTallyValue;
  votedItems: Set<string>;
  disabled: boolean;
  vote: (itemId: string) => void;
  unvote: (itemId: string) => void;
  toggleVote: (itemId: string) => void;
  getVoteCount: (itemId: string) => number;
  hasVoted: (itemId: string) => boolean;
}

const VoteTallyContext = createContext<VoteTallyContextValue | null>(null);

function useVoteTallyContext() {
  const context = useContext(VoteTallyContext);
  if (!context) {
    throw new Error("VoteTally components must be used within VoteTally.Root");
  }
  return context;
}

interface VoteTallyItemContextValue {
  itemId: string;
  disabled: boolean;
}

const VoteTallyItemContext = createContext<VoteTallyItemContextValue | null>(
  null
);

function useVoteTallyItemContext() {
  const context = useContext(VoteTallyItemContext);
  if (!context) {
    throw new Error(
      "VoteTally.Item sub-components must be used within VoteTally.Item"
    );
  }
  return context;
}

/* -----------------------------------------------------------------------------
 * Root
 * -------------------------------------------------------------------------- */

function VoteTallyRoot({
  value: controlledValue,
  defaultValue = {},
  onValueChange,
  votedItems: controlledVotedItems,
  defaultVotedItems,
  onVotedItemsChange,
  disabled = false,
  children,
  ...props
}: VoteTallyRootProps) {
  const [votes, setVotes] = useControllableState<VoteTallyValue>({
    prop: controlledValue,
    defaultProp: defaultValue,
    onChange: onValueChange,
  });

  const [votedItemsArray, setVotedItemsArray] = useControllableState({
    prop: controlledVotedItems ? Array.from(controlledVotedItems) : undefined,
    defaultProp: defaultVotedItems ? Array.from(defaultVotedItems) : [],
    onChange: (arr) => onVotedItemsChange?.(new Set(arr)),
  });

  const votedItems = useMemo(() => new Set(votedItemsArray), [votedItemsArray]);

  const vote = useCallback(
    (itemId: string) => {
      if (disabled || votedItems.has(itemId)) {
        return;
      }

      setVotes((prev) => ({
        ...prev,
        [itemId]: (prev?.[itemId] ?? 0) + 1,
      }));
      setVotedItemsArray((prev) => [...(prev ?? []), itemId]);
    },
    [disabled, votedItems, setVotes, setVotedItemsArray]
  );

  const unvote = useCallback(
    (itemId: string) => {
      if (disabled || !votedItems.has(itemId)) {
        return;
      }

      setVotes((prev) => ({
        ...prev,
        [itemId]: Math.max((prev?.[itemId] ?? 0) - 1, 0),
      }));
      setVotedItemsArray((prev) => (prev ?? []).filter((id) => id !== itemId));
    },
    [disabled, votedItems, setVotes, setVotedItemsArray]
  );

  const toggleVote = useCallback(
    (itemId: string) => {
      if (votedItems.has(itemId)) {
        unvote(itemId);
      } else {
        vote(itemId);
      }
    },
    [votedItems, vote, unvote]
  );

  const getVoteCount = useCallback(
    (itemId: string) => votes?.[itemId] ?? 0,
    [votes]
  );

  const hasVoted = useCallback(
    (itemId: string) => votedItems.has(itemId),
    [votedItems]
  );

  const contextValue = useMemo(
    () => ({
      votes: votes ?? {},
      votedItems,
      disabled,
      vote,
      unvote,
      toggleVote,
      getVoteCount,
      hasVoted,
    }),
    [
      votes,
      votedItems,
      disabled,
      vote,
      unvote,
      toggleVote,
      getVoteCount,
      hasVoted,
    ]
  );

  return (
    <VoteTallyContext.Provider value={contextValue}>
      <ul
        aria-label="Vote tally list"
        data-disabled={disabled ? true : undefined}
        {...props}
      >
        {children}
      </ul>
    </VoteTallyContext.Provider>
  );
}

/* -----------------------------------------------------------------------------
 * Group (optional sorting wrapper)
 * -------------------------------------------------------------------------- */

function VoteTallyGroup({
  sortBy = "none",
  children,
  ...props
}: VoteTallyGroupProps) {
  const { votes } = useVoteTallyContext();

  const sortedChildren = useMemo(() => {
    if (sortBy === "none") {
      return children;
    }

    const childArray = Children.toArray(children);

    return childArray.sort((a, b) => {
      if (!(isValidElement(a) && isValidElement(b))) {
        return 0;
      }

      const aValue = (a.props as VoteTallyItemProps).value;
      const bValue = (b.props as VoteTallyItemProps).value;
      const aVotes = votes[aValue] ?? 0;
      const bVotes = votes[bValue] ?? 0;

      return sortBy === "votes-desc" ? bVotes - aVotes : aVotes - bVotes;
    });
  }, [children, sortBy, votes]);

  return <div {...props}>{sortedChildren}</div>;
}

/* -----------------------------------------------------------------------------
 * Item
 * -------------------------------------------------------------------------- */

function VoteTallyItem({
  value,
  disabled: itemDisabled = false,
  children,
  ...props
}: VoteTallyItemProps) {
  const {
    disabled: rootDisabled,
    hasVoted,
    getVoteCount,
  } = useVoteTallyContext();
  const disabled = rootDisabled || itemDisabled;
  const voted = hasVoted(value);
  const voteCount = getVoteCount(value);

  const itemContextValue = useMemo(
    () => ({ itemId: value, disabled }),
    [value, disabled]
  );

  return (
    <VoteTallyItemContext.Provider value={itemContextValue}>
      <li
        data-disabled={disabled ? true : undefined}
        data-item={value}
        data-slot="vote-tally-item"
        data-vote-count={voteCount}
        data-voted={voted ? true : undefined}
        {...props}
      >
        {children}
      </li>
    </VoteTallyItemContext.Provider>
  );
}

/* -----------------------------------------------------------------------------
 * Trigger
 * -------------------------------------------------------------------------- */

function VoteTallyTrigger({
  children,
  onClick,
  ...props
}: VoteTallyTriggerProps) {
  const {
    toggleVote,
    hasVoted,
    disabled: rootDisabled,
  } = useVoteTallyContext();
  const { itemId, disabled: itemDisabled } = useVoteTallyItemContext();

  const disabled = rootDisabled || itemDisabled;
  const voted = hasVoted(itemId);

  const handleClick = useCallback(
    (event: MouseEvent<HTMLButtonElement>) => {
      onClick?.(event);
      if (!(event.defaultPrevented || disabled)) {
        toggleVote(itemId);
      }
    },
    [onClick, disabled, toggleVote, itemId]
  );

  return (
    <button
      aria-label={voted ? "Remove vote" : "Vote"}
      aria-pressed={voted}
      data-slot="vote-tally-trigger"
      data-state={voted ? "voted" : "idle"}
      disabled={disabled}
      onClick={handleClick}
      type="button"
      {...props}
    >
      {children}
    </button>
  );
}

/* -----------------------------------------------------------------------------
 * Count
 * -------------------------------------------------------------------------- */

function VoteTallyCount({ children, ...props }: VoteTallyCountProps) {
  const { getVoteCount } = useVoteTallyContext();
  const { itemId } = useVoteTallyItemContext();

  const count = getVoteCount(itemId);

  return (
    <span data-slot="vote-tally-count" {...props}>
      {children ?? count}
    </span>
  );
}

/* -----------------------------------------------------------------------------
 * Title
 * -------------------------------------------------------------------------- */

function VoteTallyTitle({ children, ...props }: VoteTallyTitleProps) {
  return (
    <span data-slot="vote-tally-title" {...props}>
      {children}
    </span>
  );
}

/* -----------------------------------------------------------------------------
 * Description
 * -------------------------------------------------------------------------- */

function VoteTallyDescription({
  children,
  ...props
}: VoteTallyDescriptionProps) {
  return (
    <span data-slot="vote-tally-description" {...props}>
      {children}
    </span>
  );
}

/* -----------------------------------------------------------------------------
 * Hook for external access
 * -------------------------------------------------------------------------- */

export function useVoteTally() {
  return useVoteTallyContext();
}

/* -----------------------------------------------------------------------------
 * Export
 * -------------------------------------------------------------------------- */

export const VoteTally = {
  Root: VoteTallyRoot,
  Group: VoteTallyGroup,
  Item: VoteTallyItem,
  Trigger: VoteTallyTrigger,
  Count: VoteTallyCount,
  Title: VoteTallyTitle,
  Description: VoteTallyDescription,
};

export {
  VoteTallyRoot,
  VoteTallyGroup,
  VoteTallyItem,
  VoteTallyTrigger,
  VoteTallyCount,
  VoteTallyTitle,
  VoteTallyDescription,
};
