// apps/vue/registry/default/ui/YoutubeVideoPlayer.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { Maximize2, Minimize2, Play } from 'lucide-vue-next'
import { cn } from '@/lib/utils'

const props = withDefaults(defineProps<{
  videoId: string
  title?: string
  defaultExpanded?: boolean
  customThumbnail?: string
  class?: string
  containerClassName?: string
  expandedClassName?: string
  thumbnailClassName?: string
  thumbnailImageClassName?: string
  playButtonClassName?: string
  playIconClassName?: string
  titleClassName?: string
  controlsClassName?: string
  expandButtonClassName?: string
  backdropClassName?: string
  playerClassName?: string
}>(), {
  defaultExpanded: false,
})

const expanded = ref(props.defaultExpanded)
const playing = ref(false)
const isHovered = ref(false)

const actualVideoId = computed(() => {
  const id = props.videoId
  if (id.includes('youtube.com') || id.includes('youtu.be')) {
    try {
      const url = new URL(id)
      if (id.includes('youtube.com')) {
        return url.searchParams.get('v') || ''
      } else {
        return url.pathname.substring(1)
      }
    } catch {
      return id
    }
  }
  return id
})

const thumbnailUrl = computed(() => {
  if (props.customThumbnail) return props.customThumbnail
  return actualVideoId.value
    ? `https://i.ytimg.com/vi/${actualVideoId.value}/hqdefault.jpg`
    : ''
})

const embedUrl = computed(() =>
  `https://www.youtube.com/embed/${actualVideoId.value}?autoplay=1&rel=0&modestbranding=1&iv_load_policy=3&showinfo=0&controls=1`
)

const shouldShowControls = computed(() => !playing.value || isHovered.value || expanded.value)

function handlePlay() {
  playing.value = true
}

function toggleExpand() {
  expanded.value = !expanded.value
}

// Handle Escape key
function handleKeyDown(event: KeyboardEvent) {
  if (event.key === 'Escape' && expanded.value) {
    expanded.value = false
  }
}

onMounted(() => {
  document.addEventListener('keydown', handleKeyDown)
})

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeyDown)
})
</script>

<template>
  <!-- Main container -->
  <div
    :class="cn(
      'relative',
      expanded ? 'invisible' : 'visible',
      props.class
    )"
  >
    <div
      :class="cn(
        'overflow-hidden border bg-card text-card-foreground shadow-lg rounded-xl',
        containerClassName
      )"
    >
      <div :class="cn('relative aspect-video bg-muted', playerClassName)">
        <!-- Thumbnail state -->
        <template v-if="!playing">
          <div
            :class="cn(
              'absolute inset-0 bg-gradient-to-br from-muted to-muted/80',
              thumbnailClassName
            )"
          >
            <img
              v-if="thumbnailUrl"
              :src="thumbnailUrl"
              :alt="title || 'Video thumbnail'"
              :class="cn(
                'absolute inset-0 h-full w-full object-cover opacity-70',
                thumbnailImageClassName
              )"
            />
          </div>

          <div class="absolute inset-0 flex flex-col items-center justify-center z-10">
            <button
              :class="cn(
                'relative h-16 w-16 rounded-full border border-border/20 bg-background/80 backdrop-blur-sm md:h-20 md:w-20 p-0 inline-flex items-center justify-center',
                'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background',
                playButtonClassName
              )"
              aria-label="Play video"
              @click="handlePlay"
            >
              <Play
                :class="cn(
                  'h-6 w-6 translate-x-[2px] fill-primary text-primary md:h-8 md:w-8',
                  playIconClassName
                )"
              />
            </button>

            <h3
              v-if="title"
              :class="cn(
                'mt-4 max-w-xs text-center text-sm font-medium text-secondary/90 md:max-w-md md:text-base',
                titleClassName
              )"
            >
              {{ title }}
            </h3>
          </div>
        </template>

        <!-- Playing state -->
        <iframe
          v-if="playing"
          :src="embedUrl"
          :title="title"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen
          class="h-full w-full border-0"
        />

        <!-- Controls overlay -->
        <Transition name="fade">
          <div
            v-if="shouldShowControls"
            :class="cn('absolute right-2 top-2 z-20', controlsClassName)"
          >
            <button
              :class="cn(
                'h-8 w-8 rounded-full bg-background/40 backdrop-blur-sm hover:bg-background/60 focus-visible:ring-ring/50 md:h-9 md:w-9 inline-flex items-center justify-center transition-transform hover:scale-105 active:scale-95',
                expandButtonClassName
              )"
              :aria-label="expanded ? 'Minimize video' : 'Maximize video'"
              @click="toggleExpand"
            >
              <Minimize2 v-if="expanded" class="h-4 w-4 md:h-5 md:w-5" />
              <Maximize2 v-else class="h-4 w-4 md:h-5 md:w-5" />
            </button>
          </div>
        </Transition>
      </div>
    </div>
  </div>

  <!-- Expanded state -->
  <Teleport to="body">
    <Transition name="fade">
      <div
        v-if="expanded"
        :class="cn(
          'fixed inset-0 z-40 bg-background/80 backdrop-blur-sm',
          backdropClassName
        )"
        aria-label="Close expanded video"
        @click="toggleExpand"
      />
    </Transition>

    <Transition name="scale">
      <div
        v-if="expanded"
        class="fixed inset-0 z-50 flex items-center justify-center pointer-events-none"
      >
        <div
          :class="cn(
            'overflow-hidden border bg-card text-card-foreground shadow-xl rounded-lg pointer-events-auto',
            'w-[90vw] max-w-[1200px] max-h-[90vh] aspect-video',
            expandedClassName
          )"
        >
          <div :class="cn('relative aspect-video bg-muted', playerClassName)">
            <template v-if="!playing">
              <div
                :class="cn(
                  'absolute inset-0 bg-gradient-to-br from-muted to-muted/80',
                  thumbnailClassName
                )"
              >
                <img
                  v-if="thumbnailUrl"
                  :src="thumbnailUrl"
                  :alt="title || 'Video thumbnail'"
                  :class="cn(
                    'absolute inset-0 h-full w-full object-cover opacity-70',
                    thumbnailImageClassName
                  )"
                />
              </div>

              <div class="absolute inset-0 flex flex-col items-center justify-center z-10">
                <button
                  :class="cn(
                    'relative h-16 w-16 rounded-full border border-border/20 bg-background/80 backdrop-blur-sm md:h-20 md:w-20 p-0 inline-flex items-center justify-center',
                    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background',
                    playButtonClassName
                  )"
                  aria-label="Play video"
                  @click="handlePlay"
                >
                  <Play
                    :class="cn(
                      'h-6 w-6 translate-x-[2px] fill-primary text-primary md:h-8 md:w-8',
                      playIconClassName
                    )"
                  />
                </button>

                <h3
                  v-if="title"
                  :class="cn(
                    'mt-4 max-w-xs text-center text-sm font-medium text-foreground/90 md:max-w-md md:text-base',
                    titleClassName
                  )"
                >
                  {{ title }}
                </h3>
              </div>
            </template>

            <iframe
              v-if="playing"
              :src="embedUrl"
              :title="title"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowfullscreen
              class="h-full w-full border-0"
            />

            <!-- Controls overlay -->
            <Transition name="fade">
              <div
                v-if="shouldShowControls"
                :class="cn('absolute right-2 top-2 z-20', controlsClassName)"
              >
                <button
                  :class="cn(
                    'h-8 w-8 rounded-full bg-background/40 backdrop-blur-sm hover:bg-background/60 focus-visible:ring-ring/50 md:h-9 md:w-9 inline-flex items-center justify-center transition-transform hover:scale-105 active:scale-95',
                    expandButtonClassName
                  )"
                  :aria-label="expanded ? 'Minimize video' : 'Maximize video'"
                  @click="toggleExpand"
                >
                  <Minimize2 v-if="expanded" class="h-4 w-4 md:h-5 md:w-5" />
                  <Maximize2 v-else class="h-4 w-4 md:h-5 md:w-5" />
                </button>
              </div>
            </Transition>
          </div>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.scale-enter-active,
.scale-leave-active {
  transition: transform 0.3s ease, opacity 0.3s ease;
}

.scale-enter-from,
.scale-leave-to {
  transform: scale(0.95);
  opacity: 0;
}
</style>

// apps/www/registry/default/ui/youtube-video-player.tsx
"use client";

import { Maximize2, Minimize2, Play } from "lucide-react";
import { AnimatePresence, motion } from "motion/react";
import { useEffect, useState } from "react";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

interface YouTubePlayerProps {
  videoId: string;
  title?: string;
  defaultExpanded?: boolean;
  customThumbnail?: string;

  // Container & Layout
  className?: string;
  containerClassName?: string;
  expandedClassName?: string;

  // Thumbnail & Media
  thumbnailClassName?: string;
  thumbnailImageClassName?: string;

  // Play Button
  playButtonClassName?: string;
  playIconClassName?: string;

  // Title
  titleClassName?: string;

  // Controls
  controlsClassName?: string;
  expandButtonClassName?: string;

  // Backdrop
  backdropClassName?: string;

  // Player
  playerClassName?: string;
}

export function YouTubePlayer({
  videoId,
  title,
  defaultExpanded = false,
  customThumbnail,

  // Styling props
  className,
  containerClassName,
  expandedClassName,
  thumbnailClassName,
  thumbnailImageClassName,
  playButtonClassName,
  playIconClassName,
  titleClassName,
  controlsClassName,
  expandButtonClassName,
  backdropClassName,
  playerClassName,
}: YouTubePlayerProps) {
  const [expanded, setExpanded] = useState(defaultExpanded);
  const [playing, setPlaying] = useState(false);
  const [isHovered, setIsHovered] = useState(false);

  // Extract video ID from full URL if needed
  const extractVideoId = (id: string) => {
    if (id.includes("youtube.com") || id.includes("youtu.be")) {
      try {
        const url = new URL(id);
        if (id.includes("youtube.com")) {
          return url.searchParams.get("v") || "";
        } else {
          return url.pathname.substring(1);
        }
      } catch (error) {
        console.error("Invalid YouTube URL:", error);
        return id;
      }
    }
    return id;
  };

  const actualVideoId = extractVideoId(videoId);

  const handlePlay = () => {
    setPlaying(true);
  };

  const toggleExpand = () => {
    setExpanded(!expanded);
  };

  // Handle Escape key to minimize when expanded
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape" && expanded) {
        setExpanded(false);
      }
    };
    if (expanded) {
      document.addEventListener("keydown", handleKeyDown);
    }
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
    };
  }, [expanded]);

  const getThumbnailUrl = () => {
    if (customThumbnail) return customThumbnail;
    return actualVideoId
      ? `https://i.ytimg.com/vi/${actualVideoId}/hqdefault.jpg`
      : "";
  };

  return (
    <>
      {/* Main container - always in the document flow */}
      <div
        className={cn(
          "relative",
          expanded ? "invisible" : "visible",
          className
        )}
      >
        <motion.div
          layoutId={`youtube-player-${videoId}`}
          className={cn(
            "bg-card text-card-foreground overflow-hidden rounded-xl border shadow-lg",
            containerClassName
          )}
        >
          <motion.div
            layoutId={`youtube-player-content-${videoId}`}
            className={cn("bg-muted relative aspect-video", playerClassName)}
          >
            {!playing && (
              <>
                <motion.div
                  layoutId={`youtube-player-thumbnail-container-${videoId}`}
                  className={cn(
                    "from-muted to-muted/80 absolute inset-0 bg-gradient-to-br",
                    thumbnailClassName
                  )}
                >
                  {getThumbnailUrl() && (
                    <motion.img
                      layoutId={`youtube-player-thumbnail-${videoId}`}
                      src={getThumbnailUrl()}
                      alt={title || "Video thumbnail"}
                      className={cn(
                        "absolute inset-0 h-full w-full object-cover opacity-70",
                        thumbnailImageClassName
                      )}
                    />
                  )}
                </motion.div>

                <motion.div
                  layoutId={`youtube-player-content-overlay-${videoId}`}
                  className="absolute inset-0 z-10 flex flex-col items-center justify-center"
                >
                  <Button
                    size="lg"
                    variant="secondary"
                    className={cn(
                      "border-border/20 bg-background/80 relative h-16 w-16 rounded-full border p-0 backdrop-blur-sm md:h-20 md:w-20",
                      "focus-visible:ring-ring focus-visible:ring-offset-background focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none",
                      playButtonClassName
                    )}
                    onClick={handlePlay}
                    aria-label="Play video"
                  >
                    <Play
                      className={cn(
                        "fill-primary text-primary h-6 w-6 translate-x-[2px] md:h-8 md:w-8",
                        playIconClassName
                      )}
                    />
                  </Button>

                  {title && (
                    <motion.h3
                      layoutId={`youtube-player-title-${videoId}`}
                      className={cn(
                        "text-secondary/90 mt-4 max-w-xs text-center text-sm font-medium md:max-w-md md:text-base",
                        titleClassName
                      )}
                    >
                      {title}
                    </motion.h3>
                  )}
                </motion.div>
              </>
            )}

            {playing && (
              <iframe
                src={`https://www.youtube.com/embed/${actualVideoId}?autoplay=1&rel=0&modestbranding=1&iv_load_policy=3&showinfo=0&controls=1`}
                title={title}
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowFullScreen
                className="h-full w-full border-0"
              />
            )}

            {/* Controls Overlay */}
            <YouTubePlayerControls
              videoId={videoId}
              expanded={expanded}
              playing={playing}
              isHovered={isHovered}
              onToggleExpand={toggleExpand}
              controlsClassName={controlsClassName}
              expandButtonClassName={expandButtonClassName}
            />
          </motion.div>
        </motion.div>
      </div>

      {/* Expanded state - fixed position */}
      <AnimatePresence>
        {expanded && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              className={cn(
                "bg-background/80 fixed inset-0 z-40 backdrop-blur-sm",
                backdropClassName
              )}
              onClick={toggleExpand}
              aria-label="Close expanded video"
            />

            <div className="pointer-events-none fixed inset-0 z-50 flex items-center justify-center">
              <motion.div
                layoutId={`youtube-player-${videoId}`}
                className={cn(
                  "bg-card text-card-foreground pointer-events-auto overflow-hidden rounded-lg border shadow-xl",
                  "aspect-video max-h-[90vh] w-[90vw] max-w-[1200px]",
                  expandedClassName
                )}
              >
                <motion.div
                  layoutId={`youtube-player-content-${videoId}`}
                  className={cn(
                    "bg-muted relative aspect-video",
                    playerClassName
                  )}
                >
                  {!playing && (
                    <>
                      <motion.div
                        layoutId={`youtube-player-thumbnail-container-${videoId}`}
                        className={cn(
                          "from-muted to-muted/80 absolute inset-0 bg-gradient-to-br",
                          thumbnailClassName
                        )}
                      >
                        {getThumbnailUrl() && (
                          <motion.img
                            layoutId={`youtube-player-thumbnail-${videoId}`}
                            src={getThumbnailUrl()}
                            alt={title || "Video thumbnail"}
                            className={cn(
                              "absolute inset-0 h-full w-full object-cover opacity-70",
                              thumbnailImageClassName
                            )}
                          />
                        )}
                      </motion.div>

                      <motion.div
                        layoutId={`youtube-player-content-overlay-${videoId}`}
                        className="absolute inset-0 z-10 flex flex-col items-center justify-center"
                      >
                        <Button
                          size="lg"
                          variant="secondary"
                          className={cn(
                            "border-border/20 bg-background/80 relative h-16 w-16 rounded-full border p-0 backdrop-blur-sm md:h-20 md:w-20",
                            "focus-visible:ring-ring focus-visible:ring-offset-background focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:outline-none",
                            playButtonClassName
                          )}
                          onClick={handlePlay}
                          aria-label="Play video"
                        >
                          <Play
                            className={cn(
                              "fill-primary text-primary h-6 w-6 translate-x-[2px] md:h-8 md:w-8",
                              playIconClassName
                            )}
                          />
                        </Button>

                        {title && (
                          <motion.h3
                            layoutId={`youtube-player-title-${videoId}`}
                            className={cn(
                              "text-foreground/90 mt-4 max-w-xs text-center text-sm font-medium md:max-w-md md:text-base",
                              titleClassName
                            )}
                          >
                            {title}
                          </motion.h3>
                        )}
                      </motion.div>
                    </>
                  )}

                  {playing && (
                    <iframe
                      src={`https://www.youtube.com/embed/${actualVideoId}?autoplay=1&rel=0&modestbranding=1&iv_load_policy=3&showinfo=0&controls=1`}
                      title={title}
                      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                      allowFullScreen
                      className="h-full w-full border-0"
                    />
                  )}

                  {/* Controls Overlay */}
                  <YouTubePlayerControls
                    videoId={videoId}
                    expanded={expanded}
                    playing={playing}
                    isHovered={isHovered}
                    onToggleExpand={toggleExpand}
                    controlsClassName={controlsClassName}
                    expandButtonClassName={expandButtonClassName}
                  />
                </motion.div>
              </motion.div>
            </div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}

// Controls Component
interface YouTubePlayerControlsProps {
  videoId: string;
  expanded: boolean;
  playing: boolean;
  isHovered: boolean;
  onToggleExpand: () => void;
  controlsClassName?: string;
  expandButtonClassName?: string;
}

function YouTubePlayerControls({
  videoId,
  expanded,
  playing,
  isHovered,
  onToggleExpand,
  controlsClassName,
  expandButtonClassName,
}: YouTubePlayerControlsProps) {
  const shouldShow = !playing || isHovered || expanded;

  return (
    <AnimatePresence>
      {shouldShow && (
        <motion.div
          layoutId={`youtube-player-controls-${videoId}`}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          className={cn("absolute top-2 right-2 z-20", controlsClassName)}
        >
          <motion.div whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>
            <Button
              variant="secondary"
              size="icon"
              onClick={onToggleExpand}
              className={cn(
                "bg-background/40 hover:bg-background/60 focus-visible:ring-ring/50 h-8 w-8 rounded-full backdrop-blur-sm md:h-9 md:w-9",
                expandButtonClassName
              )}
              aria-label={expanded ? "Minimize video" : "Maximize video"}
            >
              <motion.div
                animate={{ rotate: expanded ? 180 : 0 }}
                transition={{ type: "spring", stiffness: 300, damping: 20 }}
              >
                {expanded ? (
                  <Minimize2 className="h-4 w-4 md:h-5 md:w-5" />
                ) : (
                  <Maximize2 className="h-4 w-4 md:h-5 md:w-5" />
                )}
              </motion.div>
            </Button>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// Export sub-components for advanced customization
export { YouTubePlayerControls };
