// apps/vue/registry/default/example/BgMediaDemo.vue
<script setup lang="ts">
import BackgroundMedia from '../ui/bg-media'
</script>

<template>
  <div class="w-full">
    <div class="md:min-w-[20rem]">
      <BackgroundMedia
        type="video"
        variant="light"
        src="https://openaicomproductionae4b.blob.core.windows.net/production-twill-01/c74791d0-75d2-48e6-acae-96d13bc97c56/paper-planes.mp4"
      />
    </div>
  </div>
</template>

// apps/www/registry/default/example/bg-media-demo.tsx
import BackgroundMedia from "../ui/bg-media"

export default function BgMediaDemo() {
  return (
    <div className="w-full ">
      <div className="md:min-w-[20rem] ">
        <BackgroundMedia
          type="video"
          variant="light"
          src="https://openaicomproductionae4b.blob.core.windows.net/production-twill-01/c74791d0-75d2-48e6-acae-96d13bc97c56/paper-planes.mp4"
        />
      </div>
    </div>
  )
}
