// apps/vue/registry/default/example/CosmicButtonDemo.vue
<script setup lang="ts">
import { CosmicButton } from '@/registry/default/ui/cosmic-button'
</script>

<template>
  <div class="p-6 rounded-3xl flex justify-center">
    <div>
      <div class="grid place-items-center">
        <CosmicButton as="button" type="button">
          Cosmic button goes brrr
        </CosmicButton>
      </div>
    </div>
  </div>
</template>

// apps/www/registry/default/example/cosmic-button-demo.tsx
"use client";

import { CosmicButton } from "@/registry/default/ui/cosmic-button";

export default function CosmicButtonDemo() {
  return (
    <div className="flex justify-center rounded-3xl p-6">
      <div>
        <div className="grid place-items-center">
          <CosmicButton as="button" type="button">
            Cosmic button goes brrr
          </CosmicButton>
        </div>
      </div>
    </div>
  );
}
