// apps/vue/registry/default/example/ExpandableDemo.vue
<script setup lang="ts">
import {
  Battery,
  Bluetooth,
  Calendar,
  Clock,
  Cloud,
  Droplets,
  Fingerprint,
  MapPin,
  MessageSquare,
  Mic,
  ShoppingCart,
  Star,
  Sun,
  Users,
  Video,
  Wind,
} from 'lucide-vue-next'
import {
  Expandable,
  ExpandableCard,
  ExpandableCardContent,
  ExpandableCardFooter,
  ExpandableCardHeader,
  ExpandableContent,
  ExpandableTrigger,
} from '@/registry/default/ui/expandable'
</script>

<template>
  <div class="w-full max-w-7xl mx-auto space-y-12">
    <div class="flex flex-col items-center space-y-24 p-8">
      <!-- Design Sync Example -->
      <Expandable
        expand-direction="both"
        expand-behavior="replace"
        :initial-delay="0.2"
      >
        <template #default="{ isExpanded }">
          <ExpandableTrigger>
            <ExpandableCard
              class="w-full relative"
              :collapsed-size="{ width: 320, height: 240 }"
              :expanded-size="{ width: 420, height: 480 }"
              :hover-to-expand="false"
              :expand-delay="200"
              :collapse-delay="500"
            >
              <ExpandableCardHeader>
                <div class="flex justify-between items-start w-full">
                  <div class="flex items-start flex-col">
                    <span class="bg-red-100 text-red-600 dark:bg-red-900 dark:text-red-100 mb-2 rounded-md px-2 py-0.5 text-xs">In 15 mins</span>
                    <h3 class="font-semibold text-xl text-gray-800 dark:text-white">Design Sync</h3>
                  </div>
                  <button class="h-8 w-8 rounded-md border flex items-center justify-center">
                    <Calendar class="h-4 w-4" />
                  </button>
                </div>
              </ExpandableCardHeader>
              <ExpandableCardContent>
                <div class="flex flex-col items-start justify-between mb-4">
                  <div class="flex items-center text-sm text-gray-600 dark:text-gray-300">
                    <Clock class="h-4 w-4 mr-1" />
                    <span>1:30PM → 2:30PM</span>
                  </div>
                  <ExpandableContent preset="blur-md">
                    <div class="flex items-center text-sm text-gray-600 dark:text-gray-300">
                      <MapPin class="h-4 w-4 mr-1" />
                      <span>Conference Room A</span>
                    </div>
                  </ExpandableContent>
                </div>
                <ExpandableContent preset="blur-md" stagger :stagger-children="0.2">
                  <p class="text-sm text-gray-700 dark:text-gray-200 mb-4">
                    Weekly design sync to discuss ongoing projects, share updates, and address any design-related challenges.
                  </p>
                  <div class="mb-4">
                    <h4 class="font-medium text-sm text-gray-800 dark:text-gray-100 mb-2 flex items-center">
                      <Users class="h-4 w-4 mr-2" /> Attendees:
                    </h4>
                    <div class="flex -space-x-2 overflow-hidden">
                      <div v-for="(name, index) in ['Alice', 'Bob', 'Charlie', 'David']" :key="index" class="w-8 h-8 rounded-full bg-muted border-2 border-white dark:border-gray-800 flex items-center justify-center text-xs font-medium">
                        {{ name[0] }}
                      </div>
                    </div>
                  </div>
                  <div class="space-y-2">
                    <button class="w-full bg-red-600 hover:bg-red-700 text-white rounded-md px-4 py-2 text-sm inline-flex items-center justify-center">
                      <Video class="h-4 w-4 mr-2" /> Join Meeting
                    </button>
                    <button v-if="isExpanded" class="w-full rounded-md border px-4 py-2 text-sm inline-flex items-center justify-center">
                      <MessageSquare class="h-4 w-4 mr-2" /> Open Chat
                    </button>
                  </div>
                </ExpandableContent>
              </ExpandableCardContent>
              <ExpandableContent preset="slide-up">
                <ExpandableCardFooter>
                  <div class="flex items-center justify-between w-full text-sm text-gray-600 dark:text-gray-300">
                    <span>Weekly</span>
                    <span>Next: Mon, 10:00 AM</span>
                  </div>
                </ExpandableCardFooter>
              </ExpandableContent>
            </ExpandableCard>
          </ExpandableTrigger>
        </template>
      </Expandable>

      <!-- Product Showcase Card -->
      <Expandable expand-direction="both" expand-behavior="replace">
        <template #default="{ isExpanded }">
          <ExpandableTrigger>
            <ExpandableCard
              class="w-full relative"
              :collapsed-size="{ width: 330, height: 220 }"
              :expanded-size="{ width: 500, height: 520 }"
              :hover-to-expand="false"
              :expand-delay="500"
              :collapse-delay="700"
            >
              <ExpandableCardHeader>
                <div class="flex justify-between items-center">
                  <span class="bg-blue-100 text-blue-800 rounded-md px-2 py-0.5 text-xs">New Arrival</span>
                  <span class="rounded-md border px-2 py-0.5 text-xs ml-2">$129.99</span>
                </div>
              </ExpandableCardHeader>
              <ExpandableCardContent>
                <div class="flex items-start mb-4">
                  <img
                    src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6505/6505727_rd.jpg;maxHeight=640;maxWidth=550;format=webp"
                    alt="Product"
                    class="object-cover rounded-md mr-4"
                    :style="{ width: isExpanded ? '120px' : '80px', height: isExpanded ? '120px' : '80px', transition: 'width 0.3s, height 0.3s' }"
                  />
                  <div class="flex-1">
                    <h3
                      class="font-medium text-gray-800 dark:text-white tracking-tight transition-all duration-300"
                      :style="{ fontSize: isExpanded ? '24px' : '18px', fontWeight: isExpanded ? '700' : '400' }"
                    >
                      Sony Headphones
                    </h3>
                    <div class="flex items-center mt-1">
                      <Star v-for="star in 5" :key="star" class="w-4 h-4 text-yellow-400 fill-current" />
                      <span class="ml-2 text-sm text-gray-600 dark:text-gray-400">
                        {{ isExpanded ? '(128 reviews)' : '(128)' }}
                      </span>
                    </div>
                  </div>
                </div>
                <ExpandableContent preset="fade" :keep-mounted="false">
                  <p class="text-sm text-gray-600 dark:text-gray-400 mb-4 max-w-xs">
                    Experience crystal-clear audio with our latest noise-cancelling technology.
                  </p>
                  <div class="space-y-4">
                    <div class="flex items-center text-sm text-gray-600 dark:text-gray-400">
                      <Battery class="w-4 h-4 mr-2" /><span>30-hour battery life</span>
                    </div>
                    <div class="flex items-center text-sm text-gray-600 dark:text-gray-400">
                      <Bluetooth class="w-4 h-4 mr-2" /><span>Bluetooth 5.0</span>
                    </div>
                    <div class="flex items-center text-sm text-gray-600 dark:text-gray-400">
                      <Fingerprint class="w-4 h-4 mr-2" /><span>Touch controls</span>
                    </div>
                    <div class="flex items-center text-sm text-gray-600 dark:text-gray-400">
                      <Mic class="w-4 h-4 mr-2" /><span>Voice assistant compatible</span>
                    </div>
                    <button class="w-full bg-blue-600 hover:bg-blue-700 text-white rounded-md px-4 py-2 text-sm inline-flex items-center justify-center">
                      <ShoppingCart class="w-4 h-4 mr-2" /> Add to Cart
                    </button>
                  </div>
                </ExpandableContent>
              </ExpandableCardContent>
              <ExpandableContent preset="slide-up">
                <ExpandableCardFooter>
                  <div class="flex justify-between text-sm text-gray-600 dark:text-gray-400 w-full">
                    <span>Free shipping</span>
                    <span>30-day return policy</span>
                  </div>
                </ExpandableCardFooter>
              </ExpandableContent>
            </ExpandableCard>
          </ExpandableTrigger>
        </template>
      </Expandable>

      <!-- Weather Forecast Card -->
      <Expandable expand-direction="both" expand-behavior="replace">
        <ExpandableTrigger>
          <ExpandableCard
            :collapsed-size="{ width: 300, height: 220 }"
            :expanded-size="{ width: 500, height: 420 }"
            :hover-to-expand="false"
            :expand-delay="100"
            :collapse-delay="400"
          >
            <ExpandableCardHeader>
              <div class="flex items-center justify-between">
                <div class="flex items-center">
                  <Sun class="w-8 h-8 text-yellow-400 mr-2" />
                  <ExpandableContent preset="blur-sm" :keep-mounted="true">
                    <h3 class="font-medium text-lg">Today's Weather</h3>
                    <span class="bg-blue-100 text-blue-800 rounded-md px-2 py-0.5 text-xs">72°F</span>
                  </ExpandableContent>
                </div>
              </div>
            </ExpandableCardHeader>
            <ExpandableCardContent>
              <div class="flex justify-between items-center mb-4">
                <div>
                  <p class="text-2xl font-bold">72°F</p>
                  <p class="text-sm text-gray-600 dark:text-gray-400">Feels like 75°F</p>
                </div>
                <div class="text-right">
                  <p class="font-medium">Sunny</p>
                  <ExpandableContent preset="blur-sm" stagger :stagger-children="0.1" :keep-mounted="true">
                    <p class="text-sm text-gray-600 dark:text-gray-400">High 78° / Low 65°</p>
                  </ExpandableContent>
                </div>
              </div>
              <ExpandableContent preset="blur-sm" stagger :stagger-children="0.1" :keep-mounted="true">
                <div class="space-y-2 mb-4">
                  <div class="flex justify-between items-center">
                    <div class="flex items-center"><Cloud class="w-5 h-5 mr-2 text-gray-400" /><span>Humidity</span></div>
                    <span>45%</span>
                  </div>
                  <div class="flex justify-between items-center">
                    <div class="flex items-center"><Wind class="w-5 h-5 mr-2 text-gray-400" /><span>Wind</span></div>
                    <span>8 mph</span>
                  </div>
                  <div class="flex justify-between items-center">
                    <div class="flex items-center"><Droplets class="w-5 h-5 mr-2 text-gray-400" /><span>Precipitation</span></div>
                    <span>0%</span>
                  </div>
                </div>
                <div class="space-y-2">
                  <h4 class="font-medium">5-Day Forecast</h4>
                  <div v-for="(day, index) in ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']" :key="day" class="flex justify-between items-center">
                    <span>{{ day }}</span>
                    <div class="flex items-center">
                      <Sun class="w-4 h-4 text-yellow-400 mr-2" />
                      <span>{{ 70 + index }}°F</span>
                    </div>
                  </div>
                </div>
              </ExpandableContent>
            </ExpandableCardContent>
            <ExpandableCardFooter>
              <p class="text-xs text-gray-500 dark:text-gray-400">Last updated: 5 minutes ago</p>
            </ExpandableCardFooter>
          </ExpandableCard>
        </ExpandableTrigger>
      </Expandable>

      <div class="flex gap-24 min-h-[600px]" />
    </div>
  </div>
</template>

// apps/www/registry/default/example/expandable-demo.tsx
"use client"

import React, { useState } from "react"
import {
  Battery,
  Bluetooth,
  Calendar,
  Clock,
  Cloud,
  Droplets,
  Fingerprint,
  MapPin,
  MessageSquare,
  Mic,
  ShoppingCart,
  Star,
  Sun,
  Users,
  Video,
  Wind,
} from "lucide-react"
import { AnimatePresence, motion, useReducedMotion } from "motion/react"

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import {
  Expandable,
  ExpandableCard,
  ExpandableCardContent,
  ExpandableCardFooter,
  ExpandableCardHeader,
  ExpandableContent,
  ExpandableTrigger,
} from "@/registry/default/ui/expandable"

// _____________________EXAMPLES______________________
function DesignSyncExample() {
  return (
    <Expandable
      expandDirection="both"
      expandBehavior="replace"
      initialDelay={0.2}
      onExpandStart={() => console.log("Expanding meeting card...")}
      onExpandEnd={() => console.log("Meeting card expanded!")}
    >
      {({ isExpanded }) => (
        <ExpandableTrigger>
          <ExpandableCard
            className="relative w-full"
            collapsedSize={{ width: 320, height: 240 }}
            expandedSize={{ width: 420, height: 480 }}
            hoverToExpand={false}
            expandDelay={200}
            collapseDelay={500}
          >
            <ExpandableCardHeader>
              <div className="flex w-full items-start justify-between">
                <div className="flex flex-col items-start">
                  <Badge
                    variant="secondary"
                    className="mb-2 bg-red-100 text-red-600 dark:bg-red-900 dark:text-red-100"
                  >
                    In 15 mins
                  </Badge>
                  <h3 className="text-xl font-semibold text-gray-800 dark:text-white">
                    Design Sync
                  </h3>
                </div>
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button size="icon" variant="outline" className="h-8 w-8">
                        <Calendar className="h-4 w-4" />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p>Add to Calendar</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              </div>
            </ExpandableCardHeader>

            <ExpandableCardContent>
              <div className="mb-4 flex flex-col items-start justify-between">
                <div className="flex items-center text-sm text-gray-600 dark:text-gray-300">
                  <Clock className="mr-1 h-4 w-4" />
                  <span>1:30PM → 2:30PM</span>
                </div>

                <ExpandableContent preset="blur-md">
                  <div className="flex items-center text-sm text-gray-600 dark:text-gray-300">
                    <MapPin className="mr-1 h-4 w-4" />
                    <span>Conference Room A</span>
                  </div>
                </ExpandableContent>
              </div>
              <ExpandableContent preset="blur-md" stagger staggerChildren={0.2}>
                <p className="mb-4 text-sm text-gray-700 dark:text-gray-200">
                  Weekly design sync to discuss ongoing projects, share updates,
                  and address any design-related challenges.
                </p>
                <div className="mb-4">
                  <h4 className="mb-2 flex items-center text-sm font-medium text-gray-800 dark:text-gray-100">
                    <Users className="mr-2 h-4 w-4" />
                    Attendees:
                  </h4>
                  <div className="flex -space-x-2 overflow-hidden">
                    {["Alice", "Bob", "Charlie", "David"].map((name, index) => (
                      <TooltipProvider key={index}>
                        <Tooltip>
                          <TooltipTrigger asChild>
                            <Avatar className="border-2 border-white dark:border-gray-800">
                              <AvatarImage
                                src={`/placeholder.svg?height=32&width=32&text=${name[0]}`}
                                alt={name}
                              />
                              <AvatarFallback>{name[0]}</AvatarFallback>
                            </Avatar>
                          </TooltipTrigger>
                          <TooltipContent>
                            <p>{name}</p>
                          </TooltipContent>
                        </Tooltip>
                      </TooltipProvider>
                    ))}
                  </div>
                </div>
                <div className="space-y-2">
                  <Button className="w-full bg-red-600 text-white hover:bg-red-700">
                    <Video className="mr-2 h-4 w-4" />
                    Join Meeting
                  </Button>
                  {isExpanded && (
                    <Button variant="outline" className="w-full">
                      <MessageSquare className="mr-2 h-4 w-4" />
                      Open Chat
                    </Button>
                  )}
                </div>
              </ExpandableContent>
            </ExpandableCardContent>
            <ExpandableContent preset="slide-up">
              <ExpandableCardFooter>
                <div className="flex w-full items-center justify-between text-sm text-gray-600 dark:text-gray-300">
                  <span>Weekly</span>
                  <span>Next: Mon, 10:00 AM</span>
                </div>
              </ExpandableCardFooter>
            </ExpandableContent>
          </ExpandableCard>
        </ExpandableTrigger>
      )}
    </Expandable>
  )
}

export function ProductShowcaseCard() {
  return (
    <Expandable
      expandDirection="both"
      expandBehavior="replace"
      onExpandStart={() => console.log("Expanding product card...")}
      onExpandEnd={() => console.log("Product card expanded!")}
    >
      {({ isExpanded }) => (
        <ExpandableTrigger>
          <ExpandableCard
            className="relative w-full"
            collapsedSize={{ width: 330, height: 220 }}
            expandedSize={{ width: 500, height: 520 }}
            hoverToExpand={false}
            expandDelay={500}
            collapseDelay={700}
          >
            <ExpandableCardHeader>
              <div className="flex items-center justify-between">
                <Badge
                  variant="secondary"
                  className="bg-blue-100 text-blue-800"
                >
                  New Arrival
                </Badge>
                <Badge variant="outline" className="ml-2">
                  $129.99
                </Badge>
              </div>
            </ExpandableCardHeader>

            <ExpandableCardContent>
              <div className="mb-4 flex items-start">
                <img
                  src="https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6505/6505727_rd.jpg;maxHeight=640;maxWidth=550;format=webp"
                  alt="Product"
                  className="mr-4 rounded-md object-cover"
                  style={{
                    width: isExpanded ? "120px" : "80px",
                    height: isExpanded ? "120px" : "80px",
                    transition: "width 0.3s, height 0.3s",
                  }}
                />
                <div className="flex-1">
                  <h3
                    className="font-medium tracking-tight text-gray-800 transition-all duration-300 dark:text-white"
                    style={{
                      fontSize: isExpanded ? "24px" : "18px",
                      fontWeight: isExpanded ? "700" : "400",
                    }}
                  >
                    Sony Headphones
                  </h3>
                  <div className="mt-1 flex items-center">
                    {[1, 2, 3, 4, 5].map((star) => (
                      <Star
                        key={star}
                        className="h-4 w-4 fill-current text-yellow-400"
                      />
                    ))}
                    <AnimatePresence mode="wait">
                      {isExpanded ? (
                        <motion.span
                          key="expanded"
                          initial={{ opacity: 0, width: 0 }}
                          animate={{ opacity: 1, width: "auto" }}
                          exit={{ opacity: 0, width: 0 }}
                          transition={{ duration: 0.2 }}
                          className="ml-2 overflow-hidden text-sm whitespace-nowrap text-gray-600 dark:text-gray-400"
                        >
                          (128 reviews)
                        </motion.span>
                      ) : (
                        <motion.span
                          key="collapsed"
                          initial={{ opacity: 0, width: 0 }}
                          animate={{ opacity: 1, width: "auto" }}
                          exit={{ opacity: 0, width: 0 }}
                          transition={{ duration: 0.2 }}
                          className="ml-2 overflow-hidden text-sm whitespace-nowrap text-gray-600 dark:text-gray-400"
                        >
                          (128)
                        </motion.span>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              </div>
              <ExpandableContent
                preset="fade"
                keepMounted={false}
                animateIn={{
                  initial: { opacity: 0, y: 20 },
                  animate: { opacity: 1, y: 0 },
                  transition: { type: "spring", stiffness: 300, damping: 20 },
                }}
              >
                <p className="mb-4 max-w-xs text-sm text-gray-600 dark:text-gray-400">
                  Experience crystal-clear audio with our latest
                  noise-cancelling technology. Perfect for work, travel, or
                  relaxation.
                </p>

                <div className="space-y-4">
                  {[
                    { icon: Battery, text: "30-hour battery life" },
                    { icon: Bluetooth, text: "Bluetooth 5.0" },
                    { icon: Fingerprint, text: "Touch controls" },
                    { icon: Mic, text: "Voice assistant compatible" },
                  ].map((feature, index) => (
                    <div
                      key={index}
                      className="flex items-center text-sm text-gray-600 dark:text-gray-400"
                    >
                      <feature.icon className="mr-2 h-4 w-4" />
                      <span>{feature.text}</span>
                    </div>
                  ))}

                  <Button className="w-full bg-blue-600 text-white hover:bg-blue-700">
                    <ShoppingCart className="mr-2 h-4 w-4" />
                    Add to Cart
                  </Button>
                </div>
              </ExpandableContent>
            </ExpandableCardContent>
            <ExpandableContent preset="slide-up">
              <ExpandableCardFooter>
                <div className="flex w-full justify-between text-sm text-gray-600 dark:text-gray-400">
                  <span>Free shipping</span>
                  <span>30-day return policy</span>
                </div>
              </ExpandableCardFooter>
            </ExpandableContent>
          </ExpandableCard>
        </ExpandableTrigger>
      )}
    </Expandable>
  )
}

export function WeatherForecastCard() {
  return (
    <Expandable expandDirection="both" expandBehavior="replace">
      <ExpandableTrigger>
        <ExpandableCard
          collapsedSize={{ width: 300, height: 220 }}
          expandedSize={{ width: 500, height: 420 }}
          hoverToExpand={false}
          expandDelay={100}
          collapseDelay={400}
        >
          <ExpandableCardHeader>
            <div className="flex items-center justify-between">
              <div className="flex items-center">
                <Sun className="mr-2 h-8 w-8 text-yellow-400" />
                <ExpandableContent preset="blur-sm" keepMounted={true}>
                  <h3 className="text-lg font-medium">Today's Weather</h3>
                  <Badge
                    variant="secondary"
                    className="bg-blue-100 text-blue-800"
                  >
                    72°F
                  </Badge>
                </ExpandableContent>
              </div>
            </div>
          </ExpandableCardHeader>

          <ExpandableCardContent>
            <div className="mb-4 flex items-center justify-between">
              <div>
                <p className="text-2xl font-bold">72°F</p>
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Feels like 75°F
                </p>
              </div>
              <div className="text-right">
                <p className="font-medium">Sunny</p>
                <ExpandableContent
                  preset="blur-sm"
                  stagger
                  staggerChildren={0.1}
                  keepMounted={true}
                  animateIn={{
                    initial: { opacity: 0, y: 20, rotate: -5 },
                    animate: { opacity: 1, y: 0, rotate: 0 },
                    transition: { type: "spring", stiffness: 300, damping: 20 },
                  }}
                >
                  <p className="text-sm text-gray-600 dark:text-gray-400">
                    High 78° / Low 65°
                  </p>
                </ExpandableContent>
              </div>
            </div>
            <ExpandableContent
              preset="blur-sm"
              stagger
              staggerChildren={0.1}
              keepMounted={true}
              animateIn={{
                initial: { opacity: 0, y: 20, rotate: -5 },
                animate: { opacity: 1, y: 0, rotate: 0 },
                transition: { type: "spring", stiffness: 300, damping: 20 },
              }}
            >
              <div className="mb-4 space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center">
                    <Cloud className="mr-2 h-5 w-5 text-gray-400" />
                    <span>Humidity</span>
                  </div>
                  <span>45%</span>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center">
                    <Wind className="mr-2 h-5 w-5 text-gray-400" />
                    <span>Wind</span>
                  </div>
                  <span>8 mph</span>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center">
                    <Droplets className="mr-2 h-5 w-5 text-gray-400" />
                    <span>Precipitation</span>
                  </div>
                  <span>0%</span>
                </div>
              </div>
              <div className="space-y-2">
                <h4 className="font-medium">5-Day Forecast</h4>
                {["Mon", "Tue", "Wed", "Thu", "Fri"].map((day, index) => (
                  <div key={day} className="flex items-center justify-between">
                    <span>{day}</span>
                    <div className="flex items-center">
                      <Sun className="mr-2 h-4 w-4 text-yellow-400" />
                      <span>{70 + index}°F</span>
                    </div>
                  </div>
                ))}
              </div>
            </ExpandableContent>
          </ExpandableCardContent>
          <ExpandableCardFooter>
            <p className="text-xs text-gray-500 dark:text-gray-400">
              Last updated: 5 minutes ago
            </p>
          </ExpandableCardFooter>
        </ExpandableCard>
      </ExpandableTrigger>
    </Expandable>
  )
}

export default function ExpandableCardExamples() {
  return (
    <div className="mx-auto w-full max-w-7xl space-y-12">
      <div className="flex flex-col items-center space-y-24 p-8">
        <DesignSyncExample />
        <ProductShowcaseCard />
        <WeatherForecastCard />

        <div className="flex min-h-[600px] gap-24"></div>
      </div>
    </div>
  )
}
