// apps/vue/registry/default/example/GradientHeadingDemo.vue
<script setup lang="ts">
import { GradientHeading, type Size, type Variant, type Weight } from '../ui/gradient-heading'

const variants: Variant[] = ['default', 'pink', 'light']
const sizes: Size[] = ['lg', 'xl', 'xxl', 'xxxl']
const weights: Weight[] = ['thin', 'base', 'semi', 'bold', 'black']
</script>

<template>
  <div class="space-y-8 p-4">
    <div v-for="variant in variants" :key="variant">
      <h2 class="text-xl font-semibold mb-4">Variant: {{ variant }}</h2>
      <div v-for="size in sizes" :key="size" class="mb-2">
        <GradientHeading
          v-for="weight in weights"
          :key="`${variant}-${size}-${weight}`"
          :variant="variant"
          :size="size"
          :weight="weight"
          class="mb-2"
        >
          Heading - {{ size }}
        </GradientHeading>
      </div>
    </div>
  </div>
</template>

// apps/www/registry/default/example/gradient-heading-demo.tsx
"use client"

import * as React from "react"

import { GradientHeading, Size, Variant, Weight } from "../ui/gradient-heading"

export default function GradientHeadingDemo() {
  const variants: Variant[] = ["default", "pink", "light"]
  const sizes: Size[] = ["lg", "xl", "xxl", "xxxl"]
  const weights: Weight[] = ["thin", "base", "semi", "bold", "black"]

  return (
    <div className="space-y-8 p-4">
      {variants.map((variant) => (
        <div key={variant}>
          <h2 className="text-xl font-semibold mb-4">Variant: {variant}</h2>
          {sizes.map((size) => (
            <div key={size} className="mb-2">
              {weights.map((weight) => (
                <GradientHeading
                  key={`${variant}-${size}-${weight}`}
                  variant={variant}
                  size={size}
                  weight={weight}
                  className="mb-2"
                >
                  {`Heading - ${size}`}
                </GradientHeading>
              ))}
            </div>
          ))}
        </div>
      ))}
    </div>
  )
}
