// apps/vue/registry/default/example/LoadingCarouselDemo.vue
<script setup lang="ts">
import { LoadingCarousel } from '../ui/loading-carousel'
</script>

<template>
  <div class="space-y-8 p-4 w-full">
    <div class="w-full">
      <div class="p-4">
        <h3 class="text-lg font-semibold">Default LoadingCarousel</h3>
      </div>
      <div class="p-4">
        <LoadingCarousel />
      </div>
    </div>

    <div class="w-full">
      <div class="p-4">
        <h3 class="text-lg font-semibold">Wide Aspect Ratio with Top Text</h3>
      </div>
      <div class="p-4">
        <LoadingCarousel aspect-ratio="wide" text-position="top" :show-indicators="false" />
      </div>
    </div>

    <div class="w-full">
      <div class="p-4">
        <h3 class="text-lg font-semibold">Background Tips + Gradient</h3>
      </div>
      <div class="p-4">
        <LoadingCarousel aspect-ratio="wide" :background-tips="true" :background-gradient="true" />
      </div>
    </div>

    <div class="w-full">
      <div class="p-4">
        <h3 class="text-lg font-semibold">Custom Interval and Navigation</h3>
      </div>
      <div class="p-4">
        <LoadingCarousel :autoplay-interval="2000" :show-navigation="true" />
      </div>
    </div>

    <div class="w-full">
      <div class="p-4">
        <h3 class="text-lg font-semibold">Shuffled Tips with Custom Interval</h3>
      </div>
      <div class="p-4">
        <LoadingCarousel :shuffle-tips="true" :autoplay-interval="3000" :show-progress="false" />
      </div>
    </div>

    <div class="w-full">
      <div class="p-4">
        <h3 class="text-lg font-semibold">Square Aspect Ratio with Background Tips</h3>
      </div>
      <div class="p-4">
        <LoadingCarousel aspect-ratio="square" :background-tips="true" :background-gradient="true" />
      </div>
    </div>
  </div>
</template>

// apps/www/registry/default/example/loading-carousel-demo.tsx
"use client";

import React from "react";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

import { LoadingCarousel } from "../ui/loading-carousel";

export default function LoadingCarouselDemo() {
  return (
    <div className="w-full space-y-8 p-4">
      <div className="w-full">
        <CardHeader>
          <CardTitle>Default LoadingCarousel</CardTitle>
        </CardHeader>
        <CardContent>
          <LoadingCarousel />
        </CardContent>
      </div>

      <div className="w-full">
        <CardHeader>
          <CardTitle>Wide Aspect Ratio with Top Text</CardTitle>
        </CardHeader>
        <CardContent>
          <LoadingCarousel
            aspectRatio="wide"
            textPosition="top"
            showIndicators={false}
          />
        </CardContent>
      </div>

      <div className="w-full">
        <CardHeader>
          <CardTitle>Background Tips + Gradient</CardTitle>
        </CardHeader>
        <CardContent>
          <LoadingCarousel
            aspectRatio="wide"
            backgroundTips={true}
            backgroundGradient={true}
          />
        </CardContent>
      </div>

      <div className="w-full">
        <CardHeader>
          <CardTitle>Custom Interval and Navigation</CardTitle>
        </CardHeader>
        <CardContent>
          <LoadingCarousel autoplayInterval={2000} showNavigation={true} />
        </CardContent>
      </div>

      <div className="w-full">
        <CardHeader>
          <CardTitle>Shuffled Tips with Custom Interval</CardTitle>
        </CardHeader>
        <CardContent>
          <LoadingCarousel
            shuffleTips={true}
            autoplayInterval={3000}
            showProgress={false}
          />
        </CardContent>
      </div>

      <div className="w-full">
        <CardHeader>
          <CardTitle>Square Aspect Ratio with Background Tips</CardTitle>
        </CardHeader>
        <CardContent>
          <LoadingCarousel
            aspectRatio="square"
            backgroundTips={true}
            backgroundGradient={true}
          />
        </CardContent>
      </div>
    </div>
  );
}
