// apps/vue/registry/default/example/MockBrowserWindowDemo.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { BrowserWindow } from '../ui/mock-browser-window'

const config = reactive({
  variant: 'chrome' as 'chrome' | 'safari',
  headerStyle: 'full' as 'minimal' | 'full',
  size: 'lg' as 'sm' | 'md' | 'lg' | 'xl',
  showSidebar: true,
  sidebarPosition: 'left' as 'left' | 'right' | 'top' | 'bottom',
  url: 'https://example.com/dashboard',
})

const sidebarItems = [
  { label: 'Overview', active: true },
  { label: 'Users', badge: '12' },
  { label: 'Analytics', badge: 'new' },
  { label: 'Settings' },
]
</script>

<template>
  <div class="min-h-screen">
    <main class="container">
      <div class="mx-auto max-w-7xl">
        <div class="space-y-12">
          <div class="space-y-8">
            <div>
              <h2 class="text-lg font-semibold mb-6">Preview</h2>
              <div class="flex justify-center p-8 bg-muted/30 rounded-xl border">
                <BrowserWindow
                  :variant="config.variant"
                  :header-style="config.headerStyle"
                  :size="config.size"
                  :show-sidebar="config.showSidebar"
                  :sidebar-position="config.sidebarPosition"
                  :url="config.url"
                  :sidebar-items="config.showSidebar ? sidebarItems : undefined"
                  class="w-full max-w-4xl"
                />
              </div>
            </div>
          </div>

          <div class="space-y-8">
            <h2 class="text-lg font-semibold">Window Settings</h2>
            <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <div class="space-y-2">
                <label class="text-sm">Browser</label>
                <select v-model="config.variant" class="w-full h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="chrome">Chrome</option>
                  <option value="safari">Safari</option>
                </select>
              </div>
              <div class="space-y-2">
                <label class="text-sm">Header Style</label>
                <select v-model="config.headerStyle" class="w-full h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="minimal">Minimal</option>
                  <option value="full">Address Bar</option>
                </select>
              </div>
              <div class="space-y-2">
                <label class="text-sm">Size</label>
                <select v-model="config.size" class="w-full h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="sm">Small</option>
                  <option value="md">Medium</option>
                  <option value="lg">Large</option>
                  <option value="xl">Extra Large</option>
                </select>
              </div>
              <div class="space-y-2 md:col-span-2 lg:col-span-1">
                <label class="text-sm">URL</label>
                <input v-model="config.url" class="w-full h-10 rounded-md border border-input bg-background px-3 text-sm" placeholder="https://example.com" />
              </div>
              <div class="space-y-2">
                <div class="flex items-center justify-between">
                  <label class="text-sm">Show Sidebar</label>
                  <input type="checkbox" v-model="config.showSidebar" />
                </div>
              </div>
              <div v-if="config.showSidebar" class="space-y-2">
                <label class="text-sm">Sidebar Position</label>
                <select v-model="config.sidebarPosition" class="w-full h-10 rounded-md border border-input bg-background px-3 text-sm">
                  <option value="left">Left</option>
                  <option value="right">Right</option>
                </select>
              </div>
              <div class="space-y-2 md:col-span-2 lg:col-span-1">
                <label class="text-sm">Quick Presets</label>
                <div class="flex gap-2">
                  <button class="flex-1 h-9 rounded-md border border-input bg-transparent px-3 text-sm hover:bg-accent" @click="Object.assign(config, { variant: 'chrome', headerStyle: 'full', showSidebar: true, size: 'lg' })">
                    Chrome Dashboard
                  </button>
                  <button class="flex-1 h-9 rounded-md border border-input bg-transparent px-3 text-sm hover:bg-accent" @click="Object.assign(config, { variant: 'safari', headerStyle: 'minimal', showSidebar: false, size: 'md' })">
                    Safari Minimal
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  </div>
</template>

// apps/www/registry/default/example/mock-browser-window-demo.tsx
"use client"

import { useState } from "react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Switch } from "@/components/ui/switch"
import { BrowserWindow } from "@/registry/default/ui/mock-browser-window"

export default function DemoPage() {
  const [config, setConfig] = useState({
    variant: "chrome" as "chrome" | "safari",
    headerStyle: "full" as "minimal" | "full",
    size: "lg" as "sm" | "md" | "lg" | "xl",
    showSidebar: true,
    sidebarPosition: "left" as "left" | "right" | "top" | "bottom",
    url: "https://example.com/dashboard",
  })

  const [sidebarItems] = useState([
    { label: "Overview", active: true },
    { label: "Users", badge: "12" },
    { label: "Analytics", badge: "new" },
    { label: "Settings" },
  ])

  return (
    <div className="min-h-screen">
      <main className="container">
        <div className="mx-auto max-w-7xl">
          <div className="space-y-12">
            <div className="space-y-8">
              <div>
                <h2 className="mb-6 text-lg font-semibold">Preview</h2>
                <div className="bg-muted/30 flex justify-center rounded-xl border p-8">
                  <BrowserWindow
                    variant={config.variant}
                    headerStyle={config.headerStyle}
                    size={config.size}
                    showSidebar={config.showSidebar}
                    sidebarPosition={config.sidebarPosition}
                    url={config.url}
                    sidebarItems={config.showSidebar ? sidebarItems : undefined}
                    className="w-full max-w-4xl"
                  />
                </div>
              </div>
            </div>

            <div className="space-y-8">
              <h2 className="text-lg font-semibold">Window Settings</h2>
              <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                <div className="space-y-2">
                  <Label className="text-sm">Browser</Label>
                  <Select
                    value={config.variant}
                    onValueChange={(value: "chrome" | "safari") =>
                      setConfig((prev) => ({ ...prev, variant: value }))
                    }
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="chrome">Chrome</SelectItem>
                      <SelectItem value="safari">Safari</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label className="text-sm">Header Style</Label>
                  <Select
                    value={config.headerStyle}
                    onValueChange={(value: "minimal" | "full") =>
                      setConfig((prev) => ({ ...prev, headerStyle: value }))
                    }
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="minimal">Minimal</SelectItem>
                      <SelectItem value="full">Address Bar</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label className="text-sm">Size</Label>
                  <Select
                    value={config.size}
                    onValueChange={(value: "sm" | "md" | "lg" | "xl") =>
                      setConfig((prev) => ({ ...prev, size: value }))
                    }
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="sm">Small</SelectItem>
                      <SelectItem value="md">Medium</SelectItem>
                      <SelectItem value="lg">Large</SelectItem>
                      <SelectItem value="xl">Extra Large</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2 md:col-span-2 lg:col-span-1">
                  <Label className="text-sm">URL</Label>
                  <Input
                    value={config.url}
                    onChange={(e) =>
                      setConfig((prev) => ({
                        ...prev,
                        url: e.target.value,
                      }))
                    }
                    placeholder="https://example.com"
                  />
                </div>

                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <Label className="text-sm">Show Sidebar</Label>
                    <Switch
                      checked={config.showSidebar}
                      onCheckedChange={(checked) =>
                        setConfig((prev) => ({
                          ...prev,
                          showSidebar: checked,
                        }))
                      }
                    />
                  </div>
                </div>

                {config.showSidebar && (
                  <div className="space-y-2">
                    <Label className="text-sm">Sidebar Position</Label>
                    <Select
                      value={config.sidebarPosition}
                      onValueChange={(
                        value: "left" | "right" | "top" | "bottom"
                      ) =>
                        setConfig((prev) => ({
                          ...prev,
                          sidebarPosition: value,
                        }))
                      }
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="left">Left</SelectItem>
                        <SelectItem value="right">Right</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                )}

                <div className="space-y-2 md:col-span-2 lg:col-span-1">
                  <Label className="text-sm">Quick Presets</Label>
                  <div className="flex gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      className="flex-1 bg-transparent"
                      onClick={() =>
                        setConfig((prev) => ({
                          ...prev,
                          variant: "chrome",
                          headerStyle: "full",
                          showSidebar: true,
                          size: "lg",
                        }))
                      }
                    >
                      Chrome Dashboard
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      className="flex-1 bg-transparent"
                      onClick={() =>
                        setConfig((prev) => ({
                          ...prev,
                          variant: "safari",
                          headerStyle: "minimal",
                          showSidebar: false,
                          size: "md",
                        }))
                      }
                    >
                      Safari Minimal
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
