// apps/vue/registry/default/example/NeumorphEyebrowDemo.vue
<script setup lang="ts">
import { NeumorphEyebrow } from '../ui/neumorph-eyebrow'
</script>

<template>
  <div class="space-y-4 flex flex-col items-center justify-center w-full">
    <NeumorphEyebrow>A milestone in scraping</NeumorphEyebrow>
    <NeumorphEyebrow intent="primary">Primary variant</NeumorphEyebrow>
    <NeumorphEyebrow intent="secondary">Secondary variant</NeumorphEyebrow>
  </div>
</template>

// apps/www/registry/default/example/neumorph-eyebrow-demo.tsx
import { NeumorphEyebrow } from "../ui/neumorph-eyebrow"

export default function NeumorphEyebrowDemo() {
  return (
    <div className="flex w-full flex-col items-center justify-center space-y-4">
      <NeumorphEyebrow>A milestone in scraping</NeumorphEyebrow>
      <NeumorphEyebrow intent="primary">Primary variant</NeumorphEyebrow>
      <NeumorphEyebrow intent="secondary">Secondary variant</NeumorphEyebrow>
    </div>
  )
}
