// apps/vue/registry/default/example/PixelParagraphWordsDemo.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { PixelParagraph } from '../ui/pixel-paragraph-words'

const PIXEL_FONTS = ['square', 'grid', 'circle', 'triangle', 'line'] as const
type PixelFont = typeof PIXEL_FONTS[number]
const WRAPPER_TAGS = ['p', 'span', 'div'] as const

const text = ref('54+ animated components and effects. Free, open source, and built to drop into any shadcn/ui project.')
const pixelWordsInput = ref('animated,shadcn/ui')
const font = ref<PixelFont>('square')
const wrapperTag = ref<typeof WRAPPER_TAGS[number]>('p')

const pixelWords = computed(() => pixelWordsInput.value.split(',').map(w => w.trim()).filter(Boolean))
</script>

<template>
  <div class="w-full space-y-8 py-4">
    <div class="flex min-h-[120px] items-center justify-center rounded-lg border border-border/40 bg-background p-8">
      <PixelParagraph
        :text="text"
        :pixel-words="pixelWords"
        :as="wrapperTag"
        :font="font"
        class="max-w-xl text-lg leading-relaxed text-muted-foreground"
        pixel-word-class-name="text-foreground font-medium"
      />
    </div>

    <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
      <div class="space-y-2 sm:col-span-2 lg:col-span-3">
        <span class="block text-xs font-medium uppercase tracking-wider text-muted-foreground">Paragraph Text</span>
        <textarea v-model="text" :rows="3" class="w-full rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm" placeholder="Enter paragraph text" />
      </div>

      <div class="space-y-2 sm:col-span-2 lg:col-span-3">
        <span class="block text-xs font-medium uppercase tracking-wider text-muted-foreground">Pixel Words (comma-separated)</span>
        <input v-model="pixelWordsInput" type="text" class="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm shadow-sm" placeholder="e.g. animated,shadcn/ui,open source" />
        <p class="text-xs text-muted-foreground">These words render in a pixel font while the rest stays in the normal typeface</p>
      </div>

      <div class="space-y-2">
        <span class="block text-xs font-medium uppercase tracking-wider text-muted-foreground">Pixel Font</span>
        <div class="flex flex-wrap gap-1.5">
          <button
            v-for="f in PIXEL_FONTS"
            :key="f"
            type="button"
            class="rounded-md px-3 py-1.5 text-xs font-medium transition-colors"
            :class="font === f ? 'bg-foreground text-background' : 'bg-muted text-muted-foreground hover:bg-muted/80'"
            @click="font = f"
          >
            {{ f }}
          </button>
        </div>
      </div>

      <div class="space-y-2">
        <span class="block text-xs font-medium uppercase tracking-wider text-muted-foreground">Wrapper Element</span>
        <select v-model="wrapperTag" class="h-9 w-full rounded-md border border-input bg-transparent px-3 text-sm shadow-sm">
          <option v-for="t in WRAPPER_TAGS" :key="t" :value="t">&lt;{{ t }}&gt;</option>
        </select>
      </div>
    </div>
  </div>
</template>

// apps/www/registry/default/example/pixel-paragraph-words-demo.tsx
"use client"

import { useState } from "react"

import { PixelParagraph } from "@/registry/default/ui/pixel-paragraph-words"

/* ─── Constants ─── */

const PIXEL_FONTS = ["square", "grid", "circle", "triangle", "line"] as const
type PixelFont = (typeof PIXEL_FONTS)[number]

const WRAPPER_TAGS = ["p", "span", "div"] as const

const DEFAULT_TEXT =
  "54+ animated components and effects. Free, open source, and built to drop into any shadcn/ui project."
const DEFAULT_PIXEL_WORDS = "animated,shadcn/ui"

/* ─── Demo ─── */

export default function PixelParagraphWordsDemo() {
  const [text, setText] = useState(DEFAULT_TEXT)
  const [pixelWordsInput, setPixelWordsInput] = useState(DEFAULT_PIXEL_WORDS)
  const [font, setFont] = useState<PixelFont>("square")
  const [wrapperTag, setWrapperTag] =
    useState<(typeof WRAPPER_TAGS)[number]>("p")

  const pixelWords = pixelWordsInput
    .split(",")
    .map((w) => w.trim())
    .filter(Boolean)

  return (
    <div className="w-full space-y-8 py-4">
      {/* ── Preview ── */}
      <div className="border-border/40 bg-background flex min-h-[120px] items-center justify-center rounded-lg border p-8">
        <PixelParagraph
          text={text}
          pixelWords={pixelWords}
          as={wrapperTag}
          font={font}
          className="text-muted-foreground max-w-xl text-lg leading-relaxed"
          pixelWordClassName="text-foreground font-medium"
        />
      </div>

      {/* ── Controls ── */}
      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {/* Text */}
        <ControlGroup
          label="Paragraph Text"
          className="sm:col-span-2 lg:col-span-3"
        >
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            rows={3}
            className="border-input placeholder:text-muted-foreground focus-visible:ring-ring w-full rounded-md border bg-transparent px-3 py-2 text-sm shadow-sm focus-visible:ring-1 focus-visible:outline-none"
            placeholder="Enter paragraph text"
          />
        </ControlGroup>

        {/* Pixel Words */}
        <ControlGroup
          label="Pixel Words (comma-separated)"
          className="sm:col-span-2 lg:col-span-3"
        >
          <input
            type="text"
            value={pixelWordsInput}
            onChange={(e) => setPixelWordsInput(e.target.value)}
            className="border-input placeholder:text-muted-foreground focus-visible:ring-ring h-9 w-full rounded-md border bg-transparent px-3 text-sm shadow-sm focus-visible:ring-1 focus-visible:outline-none"
            placeholder="e.g. animated,shadcn/ui,open source"
          />
          <p className="text-muted-foreground text-xs">
            These words render in a pixel font while the rest stays in the
            normal typeface
          </p>
        </ControlGroup>

        {/* Pixel Font */}
        <ControlGroup label="Pixel Font">
          <div className="flex flex-wrap gap-1.5">
            {PIXEL_FONTS.map((f) => (
              <button
                type="button"
                key={f}
                onClick={() => setFont(f)}
                className={`rounded-md px-3 py-1.5 text-xs font-medium transition-colors ${
                  font === f
                    ? "bg-foreground text-background"
                    : "bg-muted text-muted-foreground hover:bg-muted/80"
                }`}
              >
                {f}
              </button>
            ))}
          </div>
        </ControlGroup>

        {/* Wrapper Tag */}
        <ControlGroup label="Wrapper Element">
          <select
            value={wrapperTag}
            onChange={(e) =>
              setWrapperTag(e.target.value as (typeof WRAPPER_TAGS)[number])
            }
            className="border-input focus-visible:ring-ring h-9 w-full rounded-md border bg-transparent px-3 text-sm shadow-sm focus-visible:ring-1 focus-visible:outline-none"
          >
            {WRAPPER_TAGS.map((t) => (
              <option key={t} value={t}>
                {"<" + t + ">"}
              </option>
            ))}
          </select>
        </ControlGroup>
      </div>
    </div>
  )
}

/* ─── Shared control primitives ─── */

function ControlGroup({
  label,
  children,
  className,
}: {
  label: string
  children: React.ReactNode
  className?: string
}) {
  return (
    <div className={`space-y-2 ${className ?? ""}`}>
      <span className="text-muted-foreground block text-xs font-medium tracking-wider uppercase">
        {label}
      </span>
      {children}
    </div>
  )
}
