// apps/vue/registry/default/example/StripeBgGuidesDemo.vue
<script setup lang="ts">
import { StripeBgGuides } from '../ui/stripe-bg-guides'
</script>

<template>
  <div class="relative w-full h-[400px] overflow-hidden rounded-lg border bg-background">
    <StripeBgGuides
      :column-count="6"
      :animated="true"
      :animation-duration="8"
      glow-color="hsl(var(--primary))"
      :randomize="true"
      :random-interval="3000"
      :contained="true"
    />
    <div class="relative z-10 flex h-full items-center justify-center">
      <div class="max-w-md text-center">
        <h3 class="text-2xl font-bold mb-2">Stripe Background Guides</h3>
        <p class="text-muted-foreground">
          Animated background guides with glowing effects, inspired by Stripe's design system.
        </p>
      </div>
    </div>
  </div>
</template>

// apps/www/registry/default/example/stripe-bg-guides-demo.tsx
"use client"

import { StripeBgGuides } from "../ui/stripe-bg-guides"

export default function StripeBgGuidesDemo() {
  return (
    <div className="bg-background relative h-[400px] w-full overflow-hidden rounded-lg border">
      {/* Modified StripeBgGuides to work within a container */}
      <StripeBgGuides
        columnCount={6}
        animated={true}
        animationDuration={8}
        glowColor="hsl(var(--primary))"
        randomize={true}
        randomInterval={3000}
        contained={true}
      />

      {/* Content to demonstrate the background effect */}
      <div className="relative z-10 flex h-full items-center justify-center">
        <div className="max-w-md text-center">
          <h3 className="mb-2 text-2xl font-bold">Stripe Background Guides</h3>
          <p className="text-muted-foreground">
            Animated background guides with glowing effects, inspired by
            Stripe's design system.
          </p>
        </div>
      </div>
    </div>
  )
}
