// apps/vue/registry/default/example/ThreeDCarouselDemo.vue
<script setup lang="ts">
import ThreeDPhotoCarousel from '../ui/three-d-carousel'
</script>

<template>
  <div class="w-full max-w-4xl">
    <div class="min-h-[500px] flex flex-col justify-center border border-dashed rounded-lg space-y-4">
      <div class="p-2">
        <ThreeDPhotoCarousel />
      </div>
    </div>
  </div>
</template>

// apps/www/registry/default/example/three-d-carousel-demo.tsx
import ThreeDPhotoCarousel from "../ui/three-d-carousel"

export default function ThreeDPhotoCarouselDemo() {
  return (
    <div className="w-full max-w-4xl">
      <div className="min-h-[500px]  flex flex-col justify-center border border-dashed rounded-lg space-y-4">
        <div className="p-2">
          <ThreeDPhotoCarousel />
        </div>
      </div>
    </div>
  )
}
