// apps/vue/components/landing/PlugGrid.vue
<script setup lang="ts">
const cards = [
  {
    title: 'Free AI Marketing',
    description:
      'An AI Cofounder that knows your brand. Start creating marketing copy that converts.',
    href: 'https://www.newcopy.ai',
  },
  {
    title: 'Free SEO Improvement Tool',
    description:
      "Quickly evaluate your website's SEO performance for free. Open graph preview included.",
    href: 'https://cleanmyseo.com',
  },
  {
    title: 'Full Stack Shadcn Templates',
    description:
      'Comprehensive Next.js + Supabase templates built with Tailwind CSS, Cult components, and shadcn.',
    href: 'https://www.newcult.co',
  },
]
</script>

<template>
  <section class="w-full py-16 md:pt-6 md:pb-12">
    <!-- Section Header -->
    <div class="mb-12 text-center">
      <div class="mx-auto mb-6 flex max-w-2xl items-center justify-center gap-4">
        <div class="h-px flex-1 bg-border" />
        <div class="flex items-center gap-2 border border-border bg-background px-3 py-1.5">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="size-4 fill-pink-400/30"
          >
            <path d="M15.5 3H5a2 2 0 0 0-2 2v14c0 1.1.9 2 2 2h14a2 2 0 0 0 2-2V8.5L15.5 3Z" />
            <path d="M14 3v4a2 2 0 0 0 2 2h4" />
            <path d="M8 13h0" />
            <path d="M16 13h0" />
            <path d="M10 17c.5.3 1.2.5 2 .5s1.5-.2 2-.5" />
          </svg>
          <span class="font-mono text-[11px] uppercase tracking-wider">
            Additional Goods
          </span>
        </div>
        <div class="h-px flex-1 bg-border" />
      </div>
    </div>

    <!-- Cards Grid -->
    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <a
        v-for="card in cards"
        :key="card.title"
        target="_blank"
        rel="noopener noreferrer"
        :href="card.href"
        class="group relative flex flex-col border border-border bg-background p-4 transition-all duration-150 hover:border-foreground/10 hover:shadow-lg hover:shadow-primary/5"
      >
        <!-- Corner accents -->
        <div class="-top-px -left-px pointer-events-none absolute h-3 w-3 border-primary/50 border-t-2 border-l-2 opacity-0 transition-all duration-200 group-hover:opacity-100" />
        <div class="-top-px -right-px pointer-events-none absolute h-3 w-3 border-primary/50 border-t-2 border-r-2 opacity-0 transition-all duration-200 group-hover:opacity-100" />
        <div class="-bottom-px -left-px pointer-events-none absolute h-3 w-3 border-primary/50 border-b-2 border-l-2 opacity-0 transition-all duration-200 group-hover:opacity-100" />
        <div class="-bottom-px -right-px pointer-events-none absolute h-3 w-3 border-primary/50 border-r-2 border-b-2 opacity-0 transition-all duration-200 group-hover:opacity-100" />

        <!-- Title -->
        <h3 class="mb-2 font-medium text-sm leading-tight tracking-tight">
          {{ card.title }}
        </h3>

        <!-- Description -->
        <p class="mb-4 flex-1 font-light text-muted-foreground text-xs leading-relaxed">
          {{ card.description }}
        </p>

        <!-- Footer -->
        <div class="flex items-center justify-end border-border border-t pt-3">
          <span class="flex items-center gap-1 font-mono text-[10px] text-muted-foreground uppercase tracking-wider transition-colors group-hover:text-primary">
            Visit
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="12"
              height="12"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="size-3 transition-transform group-hover:translate-x-0.5"
            >
              <path d="M5 12h14" />
              <path d="m12 5 7 7-7 7" />
            </svg>
          </span>
        </div>
      </a>
    </div>
  </section>
</template>

// apps/www/components/landing/plug-grid.tsx
import { ArrowRight, StickerIcon } from "lucide-react";

export function PlugCardGrid() {
	const cards = [
		{
			title: "Free AI Marketing",
			description:
				"An AI Cofounder that knows your brand. Start creating marketing copy that converts.",
			href: "https://www.newcopy.ai",
		},
		{
			title: "Free SEO Improvement Tool",
			description:
				"Quickly evaluate your website's SEO performance for free. Open graph preview included.",
			href: "https://cleanmyseo.com",
		},
		{
			title: "Full Stack Shadcn Templates",
			description:
				"Comprehensive Next.js + Supabase templates built with Tailwind CSS, Cult components, and shadcn.",
			href: "https://www.newcult.co",
		},
	];

	return (
		<section className="w-full py-16 md:pt-6 md:pb-12">
			{/* Section Header */}
			<div className="mb-12 text-center">
				<div className="mx-auto mb-6 flex max-w-2xl items-center justify-center gap-4">
					<div className="h-px flex-1 bg-border" />
					<div className="flex items-center gap-2 rounded-md border border-border bg-background px-3 py-1.5">
						<StickerIcon className="size-4  fill-pink-400/30" />
						<span className="font-mono text-[11px] uppercase tracking-wider">
							Additional Goods
						</span>
					</div>
					<div className="h-px flex-1 bg-border" />
				</div>
			</div>

			{/* Cards Grid */}
			<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
				{cards.map((card) => (
					<a
						key={card.title}
						target="_blank"
						rel="noopener noreferrer"
						href={card.href}
						className="group relative flex flex-col rounded-xl border border-border bg-background p-4 transition-all duration-150 "
					>
						{/* Title */}
						<h3 className="mb-2 font-medium text-sm leading-tight tracking-tight">
							{card.title}
						</h3>

						{/* Description */}
						<p className="mb-4 flex-1 font-light text-muted-foreground text-xs leading-relaxed">
							{card.description}
						</p>

						{/* Footer */}
						<div className="flex items-center justify-end border-border border-t pt-3">
							<span className="flex items-center gap-1 font-mono text-[10px] text-muted-foreground uppercase tracking-wider transition-colors group-hover:text-primary">
								Visit
								<ArrowRight className="size-3 transition-transform group-hover:translate-x-0.5" />
							</span>
						</div>
					</a>
				))}
			</div>
		</section>
	);
}
