// apps/vue/components/ai-elements/Controls.vue
<script setup lang="ts">
/**
 * Controls component - Flow canvas controls wrapper.
 * Vue equivalent uses @vue-flow/core Controls.
 * This is a styled container for flow control buttons.
 */
import { cn } from "@/lib/utils"

defineOptions({ name: "Controls" })

const props = defineProps<{
  class?: string
}>()
</script>

<template>
  <div
    :class="cn(
      'gap-px overflow-hidden rounded-md border bg-card p-1 shadow-none',
      '[&>button]:rounded-md [&>button]:border-none [&>button]:bg-transparent [&>button]:hover:bg-secondary',
      props.class
    )"
  >
    <slot />
  </div>
</template>

// apps/www/components/ai-elements/controls.tsx
"use client";

import { Controls as ControlsPrimitive } from "@xyflow/react";
import type { ComponentProps } from "react";

import { cn } from "@/lib/utils";

export type ControlsProps = ComponentProps<typeof ControlsPrimitive>;

export const Controls = ({ className, ...props }: ControlsProps) => (
  <ControlsPrimitive
    className={cn(
      "bg-card gap-px overflow-hidden rounded-md border p-1 shadow-none!",
      "[&>button]:hover:bg-secondary! [&>button]:rounded-md [&>button]:border-none! [&>button]:bg-transparent!",
      className
    )}
    {...props}
  />
);
